Repository foody-moody/foodymoody, pull requests merged in 2023-10, with the labels that each got.

#6 [BE] 프로젝트 환경 세팅
  be/build.gradle
  be/settings.gradle
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/com/foodymoody/be/BeApplication.java
  be/src/main/java/com/foodymoody/be/DocumentController.java
  be/src/test/java/com/foodymoody/be/BeApplicationTests.java
  be/src/test/java/com/foodymoody/be/docs/Document.java
Labels: BE, chore

#9 [FE] 프로젝트 환경 세팅
  fe/.eslintrc.cjs
  fe/.gitignore
  fe/.prettierrc
  fe/README.md
  fe/index.html
  fe/package-lock.json
  fe/package.json
  fe/public/vite.svg
  fe/src/App.tsx
  fe/src/assets/react.svg
  fe/src/constants/path.ts
  fe/src/index.css
  fe/src/main.tsx
  fe/src/pages/HomePage.tsx
  fe/src/routes/router.tsx
  fe/src/types/custom.d.ts
  fe/src/vite-env.d.ts
  fe/tsconfig.json
  fe/tsconfig.node.json
  fe/vite.config.ts
Labels: chore, FE

#11 Be/feat/#5 project setting
  .gitignore
  be/.gitattributes
  be/build.gradle
  be/gradle/wrapper/gradle-wrapper.jar
  be/gradle/wrapper/gradle-wrapper.properties
  be/gradlew
  be/gradlew.bat
  be/settings.gradle
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/com/foodymoody/be/BeApplication.java
  be/src/main/java/com/foodymoody/be/DocumentController.java
  be/src/main/java/com/foodymoody/be/feed/controller/FeedController.java
  be/src/main/java/com/foodymoody/be/feed/domain/Feed.java
  be/src/main/java/com/foodymoody/be/feed/dto/FeedRegisterRequest.java
  be/src/main/java/com/foodymoody/be/feed/dto/FeedRegisterRequestMenu.java
  be/src/main/java/com/foodymoody/be/feed/dto/FeedRegisterResponse.java
  be/src/main/java/com/foodymoody/be/feed/repository/FeedRepository.java
  be/src/main/java/com/foodymoody/be/feed/service/FeedService.java
  be/src/main/java/com/foodymoody/be/feed/util/FeedMapper.java
  be/src/main/java/com/foodymoody/be/image/domain/Image.java
  be/src/main/java/com/foodymoody/be/image/util/ImageMapper.java
  be/src/main/java/com/foodymoody/be/menu/domain/Menu.java
  be/src/main/java/com/foodymoody/be/menu/util/MenuMapper.java
  be/src/test/java/com/foodymoody/be/docs/Document.java
  be/src/test/java/com/foodymoody/be/docs/Feed.java
  be/src/test/java/com/foodymoody/be/docs/FeedSteps.java
  be/src/test/java/com/foodymoody/be/feed/mapper/MenuMapperTest.java
  be/src/test/resources/application-db.yml
  be/src/test/resources/application.yml
Labels: chore

#17 [FE] 디자인시스템 - 컬러, radius추가
  fe/src/assets/area.svg
  fe/src/assets/bell.svg
  fe/src/assets/chatDots.svg
  fe/src/assets/closeLarge.svg
  fe/src/assets/closeSmall.svg
  fe/src/assets/collectableAdd.svg
  fe/src/assets/collectableDefault.svg
  fe/src/assets/dotGhost.svg
  fe/src/assets/dotRound.svg
  fe/src/assets/edit.svg
  fe/src/assets/gear.svg
  fe/src/assets/heartBg.svg
  fe/src/assets/heartFill.svg
  fe/src/assets/heartNoBg.svg
  fe/src/assets/home.svg
  fe/src/assets/logoLarge.svg
  fe/src/assets/logoSmall.svg
  fe/src/assets/mapPinLarge.svg
  fe/src/assets/menu.svg
  fe/src/assets/pencilLine.svg
  fe/src/assets/plus.svg
  fe/src/assets/react.svg
  fe/src/assets/search.svg
  fe/src/assets/starLargeEmpty.svg
  fe/src/assets/starLargeFill.svg
  fe/src/assets/starSmall.svg
  fe/src/assets/user.svg
  fe/src/styles/designSystem.ts
Labels: design, FE

#19 [FE] chore: 미디어 쿼리 설정
  fe/src/styles/mediaQuery.ts
Labels: chore, FE, review

#21 Be/feat/14 be 인증 이미지 인수 테스트
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/com/foodymoody/be/auth/AuthController.java
  be/src/main/java/com/foodymoody/be/common/RestDocsController.java
  be/src/test/java/com/foodymoody/be/docs/Document.java
  be/src/test/java/com/foodymoody/be/docs/auth/AuthSteps.java
  be/src/test/java/com/foodymoody/be/docs/auth/AuthTest.java
Labels: BE, feat

#28 [FE] 디자인시스템 - 타입선언
  fe/src/App.tsx
  fe/src/styles/designSystem.ts
  fe/src/types/theme.d.ts
Labels: chore, FE, review

#29 [FE] Badge 컴포넌트 구현
  fe/src/App.tsx
  fe/src/components/Badge.tsx
Labels: FE, feat, review

#30 [FE] Textarea 컴포넌트 구현
  fe/src/components/common/textarea/Textarea.tsx
  fe/src/constants/path.ts
  fe/src/pages/test/TestPage.tsx
  fe/src/routes/router.tsx
  fe/tsconfig.json
Labels: FE, feat, review

#31 [FE] 로고 컴포넌트 구현
  fe/src/components/common/icons.ts
  fe/src/components/common/logo/Logo.tsx
  fe/src/pages/test/TestPage.tsx
Labels: FE, feat, review

#37 [Be] ci 구현
  .github/workflows/be-ci.yml
  .gitignore
  README.md
  be/build.gradle
Labels: BE, chore

#38 [FE] prettier import sort 세팅 추가
  fe/.prettierrc
  fe/package-lock.json
  fe/package.json
  fe/src/pages/test/TestPage.tsx
Labels: chore, FE

#41 [FE] styled-reset 삭제, globalStyle 추가
  fe/package.json
  fe/src/App.tsx
  fe/src/components/common/icon/icons.ts
  fe/src/components/common/icons.ts
  fe/src/components/common/logo/Logo.tsx
  fe/src/pages/test/TestPage.tsx
  fe/src/styles/globalStyles.ts
Labels: FE, fix, review

#39 [FE] FeedAction 구현
  fe/src/components/common/feedAction/FeedAction.tsx
  fe/src/pages/test/TestPage.tsx
Labels: FE, review

#43 [FE] userImage, userImageEdit 컴포넌트구현
  fe/src/components/common/userImage/UserImage.tsx
  fe/src/components/common/userImage/UserImageEdit.tsx
  fe/src/pages/test/TestPage.tsx
Labels: FE, feat

#45 [FE] NaviBar 컴포넌트 구현
  fe/package-lock.json
  fe/package.json
  fe/src/components/common/badge/Badge.tsx
  fe/src/components/common/logo/Logo.tsx
  fe/src/components/common/navibar/NaviBar.tsx
  fe/src/constants/path.ts
  fe/src/hooks/usePageNavigator.ts
  fe/src/pages/CollectionPage.tsx
  fe/src/pages/DetailFeedPage.tsx
  fe/src/pages/ErrorPage.tsx
  fe/src/pages/Layout.tsx
  fe/src/pages/LoginPage.tsx
  fe/src/pages/NewFeedPage.tsx
  fe/src/pages/NotiPage.tsx
  fe/src/pages/ProfilePage.tsx
  fe/src/pages/RegisterPage.tsx
  fe/src/pages/SearchPage.tsx
  fe/src/routes/router.tsx
  fe/src/styles/globalStyles.ts
Labels: FE, feat, review

#40 [Be] Feed 전체 페이지 조회 슬라이싱 구현 후 테스트 코드 작성
  be/src/main/java/com/foodymoody/be/feed/controller/FeedController.java
  be/src/main/java/com/foodymoody/be/feed/domain/Feed.java
  be/src/main/java/com/foodymoody/be/feed/dto/response/FeedReadAllResponse.java
  be/src/main/java/com/foodymoody/be/feed/dto/response/FeedReadResponse.java
  be/src/main/java/com/foodymoody/be/feed/service/FeedService.java
  be/src/test/java/com/foodymoody/be/feed/FeedSteps.java
  be/src/test/java/com/foodymoody/be/feed/FeedTest.java
Labels: BE, feat, test

#50 [Be] 2주차 PR
  .github/workflows/be-ci.yml
  .gitignore
  README.md
  be/.gitattributes
  be/build.gradle
  be/gradle/wrapper/gradle-wrapper.jar
  be/gradle/wrapper/gradle-wrapper.properties
  be/gradlew
  be/gradlew.bat
  be/settings.gradle
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/com/foodymoody/be/BeApplication.java
  be/src/main/java/com/foodymoody/be/DocumentController.java
  be/src/main/java/com/foodymoody/be/auth/AuthController.java
  be/src/main/java/com/foodymoody/be/common/RestDocsController.java
  be/src/main/java/com/foodymoody/be/feed/controller/FeedController.java
  be/src/main/java/com/foodymoody/be/feed/domain/Feed.java
  be/src/main/java/com/foodymoody/be/feed/domain/Images.java
  be/src/main/java/com/foodymoody/be/feed/domain/Menus.java
  be/src/main/java/com/foodymoody/be/feed/dto/request/FeedRegisterRequest.java
  be/src/main/java/com/foodymoody/be/feed/dto/request/FeedRegisterRequestMenu.java
  be/src/main/java/com/foodymoody/be/feed/dto/request/FeedServiceRegisterRequest.java
  be/src/main/java/com/foodymoody/be/feed/dto/request/FeedServiceUpdateRequest.java
  be/src/main/java/com/foodymoody/be/feed/dto/request/FeedUpdateRequest.java
  be/src/main/java/com/foodymoody/be/feed/dto/request/ImageMenuPair.java
  be/src/main/java/com/foodymoody/be/feed/dto/response/FeedImageMenuResponse.java
  be/src/main/java/com/foodymoody/be/feed/dto/response/FeedMemberResponse.java
  be/src/main/java/com/foodymoody/be/feed/dto/response/FeedMenuResponse.java
  be/src/main/java/com/foodymoody/be/feed/dto/response/FeedReadAllResponse.java
  be/src/main/java/com/foodymoody/be/feed/dto/response/FeedReadResponse.java
  be/src/main/java/com/foodymoody/be/feed/dto/response/FeedRegisterResponse.java
  be/src/main/java/com/foodymoody/be/feed/repository/FeedRepository.java
  be/src/main/java/com/foodymoody/be/feed/service/FeedService.java
  be/src/main/java/com/foodymoody/be/feed/util/FeedMapper.java
  be/src/main/java/com/foodymoody/be/feed/util/validator/FeedValidator.java
  be/src/main/java/com/foodymoody/be/image/domain/Image.java
  be/src/main/java/com/foodymoody/be/image/util/ImageMapper.java
  be/src/main/java/com/foodymoody/be/menu/domain/Menu.java
  be/src/main/java/com/foodymoody/be/menu/util/MenuMapper.java
  be/src/main/resources/application.yml
  be/src/test/java/com/foodymoody/be/docs/Document.java
  be/src/test/java/com/foodymoody/be/docs/auth/AuthSteps.java
  be/src/test/java/com/foodymoody/be/docs/auth/AuthTest.java
  be/src/test/java/com/foodymoody/be/docs/member/MemberAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/docs/member/MemberFixture.java
  be/src/test/java/com/foodymoody/be/docs/member/MemberSteps.java
  be/src/test/java/com/foodymoody/be/feed/FeedSteps.java
  be/src/test/java/com/foodymoody/be/feed/FeedTest.java
  be/src/test/java/com/foodymoody/be/feed/mapper/FeedMapperTest.java
  be/src/test/java/com/foodymoody/be/feed/mapper/ImageMapperTest.java
  be/src/test/java/com/foodymoody/be/feed/mapper/MenuMapperTest.java
  be/src/test/resources/application-db.yml
  be/src/test/resources/application.yml
Labels: BE

#52 [FE] Button 컴포넌트 구현
  fe/src/components/common/Button/Button.tsx
  fe/src/styles/globalStyles.ts
Labels: FE, feat, review

#51 [FE] 인풋 컴포넌트 구현
  fe/src/components/common/input/Input.tsx
  fe/src/components/common/input/InputCore.tsx
  fe/src/hooks/useInput.ts
  fe/src/pages/test/TestPage.tsx
  fe/src/styles/designSystem.ts
Labels: FE, feat, review

#56 [FE] TextButton 컴포넌트 구현
  fe/src/components/common/Button/TextButton.tsx
Labels: FE, feat, review

#63 Be/feat/#55 be 피드에 댓글 등록
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/com/foodymoody/be/comment/controller/CommentController.java
  be/src/main/java/com/foodymoody/be/comment/controller/RegisterCommentRequest.java
  be/src/main/java/com/foodymoody/be/comment/domain/Comment.java
  be/src/main/java/com/foodymoody/be/comment/repository/CommentRepository.java
  be/src/main/java/com/foodymoody/be/comment/service/CommentService.java
  be/src/main/java/com/foodymoody/be/comment/util/CommentMapper.java
  be/src/main/java/com/foodymoody/be/comment/util/CommentValidator.java
  be/src/main/java/com/foodymoody/be/common/exception/BusinessException.java
  be/src/main/java/com/foodymoody/be/common/exception/ContentIsEmptyException.java
  be/src/main/java/com/foodymoody/be/common/exception/ContentIsOver200Exception.java
  be/src/main/java/com/foodymoody/be/common/exception/ContentIsSpaceException.java
  be/src/main/java/com/foodymoody/be/common/exception/ContentNotExistsException.java
  be/src/main/java/com/foodymoody/be/common/exception/FeedIdNotExistsException.java
  be/src/main/java/com/foodymoody/be/common/exception/GlobalExceptionHandler.java
  be/src/main/java/com/foodymoody/be/common/exception/RegisterCommentRequestNotNullException.java
  be/src/main/java/com/foodymoody/be/common/util/IdGenerator.java
  be/src/main/java/com/foodymoody/be/feed/service/FeedService.java
  be/src/test/java/com/foodymoody/be/acceptance/AcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/comment/CommentSteps.java
  be/src/test/java/com/foodymoody/be/acceptance/comment/CommentTest.java
  be/src/test/java/com/foodymoody/be/comment/service/CommentServiceTest.java
  be/src/test/java/com/foodymoody/be/comment/util/CommentFixture.java
  be/src/test/java/com/foodymoody/be/comment/util/CommentMapperTest.java
  be/src/test/java/com/foodymoody/be/comment/util/CommentValidatorTest.java
  be/src/test/java/com/foodymoody/be/common/util/IdGeneratorTest.java
  be/src/test/java/com/foodymoody/be/docs/Document.java
  be/src/test/java/com/foodymoody/be/docs/auth/AuthTest.java
  be/src/test/java/com/foodymoody/be/feed/FeedSteps.java
Labels: BE, feat

#67 [FE] BadgeSelector 컴포넌트 구현
  fe/src/components/common/badge/Badge.tsx
  fe/src/components/common/badgeSelector/BadgeSelector.tsx
  fe/src/types/type.d.ts
Labels: FE, feat, review

#61 [FE] StarRating 컴포넌트 구현
  fe/src/components/common/icons.ts
  fe/src/components/common/starRating/StarRating.tsx
Labels: FE, feat, review

#64 [FE] Dropdown 컴포넌트 구현
  fe/src/components/common/dropdown/Dropdown.tsx
  fe/src/components/common/dropdown/DropdownRow.tsx
  fe/src/hooks/useAnimation.ts
  fe/src/hooks/useDropdown.ts
Labels: FE, feat, review

#70 [FE] MenuRateTag 컴포넌트 구현
  fe/src/components/common/menuRateTag/MenuRateTag.tsx
Labels: FE, feat, review

#72 Be/feat/#66 be 인증로직 리펙토링
  be/build.gradle
  be/src/main/java/com/foodymoody/be/comment/controller/CommentController.java
  be/src/main/java/com/foodymoody/be/comment/controller/RegisterCommentRequest.java
  be/src/main/java/com/foodymoody/be/comment/domain/Comment.java
  be/src/main/java/com/foodymoody/be/comment/domain/CommentValidator.java
  be/src/main/java/com/foodymoody/be/comment/service/CommentMapper.java
  be/src/main/java/com/foodymoody/be/comment/service/CommentService.java
  be/src/main/java/com/foodymoody/be/comment/util/CommentValidator.java
  be/src/main/java/com/foodymoody/be/common/RestDocsController.java
  be/src/main/java/com/foodymoody/be/common/exception/BusinessException.java
  be/src/main/java/com/foodymoody/be/common/exception/ContentIsEmptyException.java
  be/src/main/java/com/foodymoody/be/common/exception/ContentIsOver200Exception.java
  be/src/main/java/com/foodymoody/be/common/exception/ContentIsSpaceException.java
  be/src/main/java/com/foodymoody/be/common/exception/ContentNotExistsException.java
  be/src/main/java/com/foodymoody/be/common/exception/ErrorMessage.java
  be/src/main/java/com/foodymoody/be/common/exception/ErrorResponse.java
  be/src/main/java/com/foodymoody/be/common/exception/FeedIdNotExistsException.java
  be/src/main/java/com/foodymoody/be/common/exception/GlobalExceptionHandler.java
  be/src/main/java/com/foodymoody/be/common/exception/InvalidIdException.java
  be/src/main/java/com/foodymoody/be/common/exception/RegisterCommentRequestNotNullException.java
  be/src/main/java/com/foodymoody/be/common/util/Constants.java
  be/src/main/java/com/foodymoody/be/common/util/IdGenerator.java
  be/src/test/java/com/foodymoody/be/comment/service/CommentServiceTest.java
  be/src/test/java/com/foodymoody/be/comment/util/CommentMapperTest.java
  be/src/test/java/com/foodymoody/be/comment/util/CommentValidatorTest.java
Labels: BE, feat

#75 [BE] Feed 로직 API 명세서가 바뀜에 따라 리팩토링
  be/src/main/java/com/foodymoody/be/DocumentController.java
  be/src/main/java/com/foodymoody/be/comment/controller/RegisterCommentRequest.java
  be/src/main/java/com/foodymoody/be/comment/domain/Comment.java
  be/src/main/java/com/foodymoody/be/comment/util/CommentValidator.java
  be/src/main/java/com/foodymoody/be/feed/controller/FeedController.java
  be/src/main/java/com/foodymoody/be/feed/domain/Feed.java
  be/src/main/java/com/foodymoody/be/feed/domain/Images.java
  be/src/main/java/com/foodymoody/be/feed/domain/Menus.java
  be/src/main/java/com/foodymoody/be/feed/domain/StoreMood.java
  be/src/main/java/com/foodymoody/be/feed/dto/request/FeedRegisterRequest.java
  be/src/main/java/com/foodymoody/be/feed/dto/request/FeedRegisterRequestMenu.java
  be/src/main/java/com/foodymoody/be/feed/dto/request/FeedServiceRegisterRequest.java
  be/src/main/java/com/foodymoody/be/feed/dto/request/FeedServiceUpdateRequest.java
  be/src/main/java/com/foodymoody/be/feed/dto/request/FeedUpdateRequest.java
  be/src/main/java/com/foodymoody/be/feed/dto/response/FeedImageMenuResponse.java
  be/src/main/java/com/foodymoody/be/feed/dto/response/FeedMemberResponse.java
  be/src/main/java/com/foodymoody/be/feed/dto/response/FeedMenuResponse.java
  be/src/main/java/com/foodymoody/be/feed/dto/response/FeedReadAllResponse.java
  be/src/main/java/com/foodymoody/be/feed/dto/response/FeedReadResponse.java
  be/src/main/java/com/foodymoody/be/feed/dto/response/FeedRegisterResponse.java
  be/src/main/java/com/foodymoody/be/feed/repository/FeedRepository.java
  be/src/main/java/com/foodymoody/be/feed/service/FeedService.java
  be/src/main/java/com/foodymoody/be/feed/util/FeedMapper.java
  be/src/main/java/com/foodymoody/be/image/domain/Image.java
  be/src/main/java/com/foodymoody/be/image/util/ImageMapper.java
  be/src/main/java/com/foodymoody/be/menu/domain/Menu.java
  be/src/main/java/com/foodymoody/be/menu/util/MenuMapper.java
  be/src/test/java/com/foodymoody/be/acceptance/comment/CommentSteps.java
  be/src/test/java/com/foodymoody/be/acceptance/comment/CommentTest.java
  be/src/test/java/com/foodymoody/be/comment/util/CommentFixture.java
  be/src/test/java/com/foodymoody/be/feed/FeedSteps.java
  be/src/test/java/com/foodymoody/be/feed/FeedTest.java
  be/src/test/java/com/foodymoody/be/feed/mapper/FeedMapperTest.java
  be/src/test/java/com/foodymoody/be/feed/mapper/ImageMapperTest.java
  be/src/test/java/com/foodymoody/be/feed/mapper/MenuMapperTest.java
Labels: BE, feat, fix, refactor, test

#79 [FE] 로그인, 회원가입 페이지 UI
  fe/src/assets/arrowDown.svg
  fe/src/assets/logoXLarge.svg
  fe/src/components/common/icon/icons.ts
  fe/src/components/common/input/Input.tsx
  fe/src/components/common/input/InputCore.tsx
  fe/src/components/login/Login.tsx
  fe/src/components/register/Register.tsx
  fe/src/index.css
  fe/src/main.tsx
  fe/src/pages/LoginPage.tsx
  fe/src/pages/RegisterPage.tsx
  fe/src/styles/globalStyles.ts
Labels: FE, feat, review

#81 [FE] 모바일 header 컴포넌트 구현
  fe/src/assets/notiFalse.svg
  fe/src/assets/notiTrue.svg
  fe/src/components/common/headerMob/HeaderMob.tsx
  fe/src/components/common/icon/icons.ts
  fe/src/components/common/input/Input.tsx
  fe/src/components/common/navibar/NaviBar.tsx
  fe/src/components/common/notiIcon/NotiIcon.tsx
  fe/src/constants/path.ts
  fe/src/main.tsx
Labels: FE, feat, review

#83 [FE] UserFeedTabs구현
  fe/src/components/common/userFeedTabs/UserFeedTabs.tsx
Labels: FE, feat, review

#77 [BE] Feed 로직에 createdAt과 updatedAt 추가 후 테스트
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/com/foodymoody/be/feed/domain/Feed.java
  be/src/main/java/com/foodymoody/be/feed/dto/response/FeedReadAllResponse.java
  be/src/main/java/com/foodymoody/be/feed/dto/response/FeedReadResponse.java
  be/src/main/java/com/foodymoody/be/feed/service/FeedService.java
  be/src/main/java/com/foodymoody/be/feed/util/FeedMapper.java
  be/src/test/java/com/foodymoody/be/feed/FeedSteps.java
  be/src/test/java/com/foodymoody/be/feed/FeedTest.java
Labels: BE, feat, refactor, test

#85 [FE] Modal 관리 로직 구현
  fe/index.html
  fe/src/App.tsx
  fe/src/components/common/modal/Modal.tsx
Labels: FE, feat, review

#97 Be/feat/#94 be 댓글 삭제
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/com/foodymoody/be/comment/controller/CommentController.java
  be/src/main/java/com/foodymoody/be/comment/domain/Comment.java
  be/src/main/java/com/foodymoody/be/comment/domain/CommentId.java
  be/src/main/java/com/foodymoody/be/comment/domain/CommentValidator.java
  be/src/main/java/com/foodymoody/be/comment/repository/CommentRepository.java
  be/src/main/java/com/foodymoody/be/comment/service/CommentMapper.java
  be/src/main/java/com/foodymoody/be/comment/service/CommentService.java
  be/src/main/java/com/foodymoody/be/common/exception/BusinessException.java
  be/src/main/java/com/foodymoody/be/common/exception/CommentDeletedException.java
  be/src/main/java/com/foodymoody/be/common/exception/CommentNotExistsException.java
  be/src/main/java/com/foodymoody/be/common/exception/ContentIsEmptyException.java
  be/src/main/java/com/foodymoody/be/common/exception/ContentIsOver200Exception.java
  be/src/main/java/com/foodymoody/be/common/exception/ContentIsSpaceException.java
  be/src/main/java/com/foodymoody/be/common/exception/ContentNotExistsException.java
  be/src/main/java/com/foodymoody/be/common/exception/CreateTimeIsNullException.java
  be/src/main/java/com/foodymoody/be/common/exception/ErrorMessage.java
  be/src/main/java/com/foodymoody/be/common/exception/FeedIdNotExistsException.java
  be/src/main/java/com/foodymoody/be/common/exception/InvalidIdException.java
  be/src/test/java/com/foodymoody/be/acceptance/comment/CommentSteps.java
  be/src/test/java/com/foodymoody/be/acceptance/comment/CommentTest.java
  be/src/test/java/com/foodymoody/be/comment/domain/CommentTest.java
  be/src/test/java/com/foodymoody/be/comment/service/CommentServiceTest.java
  be/src/test/java/com/foodymoody/be/comment/util/CommentFixture.java
  be/src/test/java/com/foodymoody/be/comment/util/CommentMapperTest.java
Labels: BE, feat

#101 fix: /api/docs 작동 안하는 오류 수정
  be/build.gradle
Labels: BE, fix

#90 [FE] 프로필 페이지UI
  fe/src/components/common/headerMob/HeaderMob.tsx
  fe/src/components/common/notiIcon/NotiIcon.tsx
  fe/src/components/common/userFeedTabs/UserFeedTabs.tsx
  fe/src/components/common/userImage/UserImageEdit.tsx
  fe/src/components/profileUserInfo/ProfileUserInfo.tsx
  fe/src/pages/Layout.tsx
  fe/src/pages/LoginPage.tsx
  fe/src/pages/ProfilePage.tsx
  fe/src/pages/RegisterPage.tsx
  fe/src/types/type.d.ts
Labels: FE, feat

#99 [FE] 로그인 기능 구현
  fe/package-lock.json
  fe/package.json
  fe/src/App.tsx
  fe/src/api/auth/login.ts
  fe/src/api/fetcher.ts
  fe/src/components/common/badge/Badge.tsx
  fe/src/components/common/badgeSelector/BadgeSelector.tsx
  fe/src/components/common/feedUserInfo/FeedUserInfo.tsx
  fe/src/components/login/Login.tsx
  fe/src/components/profileUserInfo/ProfileUserInfo.tsx
  fe/src/components/register/Register.tsx
  fe/src/constants/endpoint.ts
  fe/src/hooks/auth/useAuth.ts
  fe/src/hooks/usePageNavigator.ts
  fe/src/pages/ProfilePage.tsx
  fe/src/pages/ProtectedRoute.tsx
  fe/src/queries/auth.ts
  fe/src/routes/router.tsx
  fe/src/types/auth.d.ts
  fe/src/utils/localStorage.ts
Labels: FE, feat, review

#102 [FE] commentitem 컴포넌트 UI
  fe/src/components/common/commentItem/CommentItem.tsx
Labels: FE, feat, review

#108 [FE] FeedMain 컴포넌트 구현
  fe/package-lock.json
  fe/package.json
  fe/src/components/common/badge/Badge.tsx
  fe/src/components/common/badgeSelector/BadgeSelector.tsx
  fe/src/components/common/carousel/Carousel.tsx
  fe/src/components/common/feedAction/FeedAction.tsx
  fe/src/components/common/feedUserInfo/FeedUserInfo.tsx
  fe/src/components/common/menuRateTag/MenuRateTag.tsx
  fe/src/components/common/navibar/NaviBar.tsx
  fe/src/components/feedMain/FeedMain.tsx
  fe/src/hooks/useReadMore.ts
  fe/src/pages/HomePage.tsx
  fe/src/types/feed.d.ts
  fe/src/types/mood.d.ts
  fe/src/types/type.d.ts
Labels: FE, feat, review

#74 [FE] MenuItemEditor 컴포넌트
  fe/src/assets/plusGhost.svg
  fe/src/components/common/icon/icons.ts
  fe/src/components/common/input/Input.tsx
  fe/src/components/common/input/InputCore.tsx
  fe/src/components/common/menuItemEditor/ImageBox.tsx
  fe/src/components/common/menuItemEditor/MenuItemEditor.tsx
  fe/src/components/common/starRating/StarRating.tsx
  fe/src/hooks/useInput.ts
  fe/src/hooks/useMenuItem.ts
Labels: FE, feat, review

#111 [BE] 피브별 댓글 조회
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/com/foodymoody/be/comment/controller/FeedCommentController.java
  be/src/main/java/com/foodymoody/be/comment/controller/dto/CommentResponse.java
  be/src/main/java/com/foodymoody/be/comment/repository/CommentRepository.java
  be/src/main/java/com/foodymoody/be/comment/service/CommentMapper.java
  be/src/main/java/com/foodymoody/be/comment/service/CommentService.java
  be/src/main/java/com/foodymoody/be/comment/service/FeedCommentService.java
  be/src/test/java/com/foodymoody/be/acceptance/comment/CommentAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/comment/CommentSteps.java
  be/src/test/java/com/foodymoody/be/comment/service/CommentServiceTest.java
  be/src/test/java/com/foodymoody/be/comment/util/CommentFixture.java
  be/src/test/java/com/foodymoody/be/comment/util/CommentMapperTest.java
  be/src/test/resources/application-db.yml
Labels: BE, feat
