Repository foody-moody/foodymoody, pull requests merged in 2023-12, with the labels that each got.

#244 [BE] id Column 추가
  be/src/main/java/com/foodymoody/be/common/util/BaseId.java
Labels: BE, refactor

#251 docs: RestDocs 오타 수정
  be/src/docs/asciidoc/index.adoc
Labels: BE, docs

#265 [FE] Dev fe -> dev
  fe/index.html
  fe/public/logoSmall.svg
  fe/src/assets/santaHat.svg
  fe/src/components/comment/CommentList.tsx
  fe/src/components/common/headerMob/HeaderMob.tsx
  fe/src/components/common/icon/icons.ts
  fe/src/components/common/logo/Logo.tsx
  fe/src/components/common/skeleton/CommentSkeleton.tsx
  fe/src/components/feedMain/FeedMainList.tsx
  fe/src/pages/DetailFeedPage.tsx
  fe/src/service/queries/comment.ts
  fe/src/service/queries/reply.ts
Labels: FE

#266 [FE] Dev -> release
  fe/index.html
  fe/public/logoSmall.svg
  fe/src/assets/santaHat.svg
  fe/src/components/comment/CommentList.tsx
  fe/src/components/common/headerMob/HeaderMob.tsx
  fe/src/components/common/icon/icons.ts
  fe/src/components/common/logo/Logo.tsx
  fe/src/components/common/skeleton/CommentSkeleton.tsx
  fe/src/components/feedMain/FeedMainList.tsx
  fe/src/pages/DetailFeedPage.tsx
  fe/src/service/queries/comment.ts
  fe/src/service/queries/reply.ts
Labels: FE, release

#276 [BE] 댓글 및 대댓글 수정 요청 적용
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/com/foodymoody/be/collection/application/FeedCollectionWriterService.java
  be/src/main/java/com/foodymoody/be/collection/domain/CommentIds.java
  be/src/main/java/com/foodymoody/be/collection/domain/FeedCollection.java
  be/src/main/java/com/foodymoody/be/collection/domain/FeedCollectionRepository.java
  be/src/main/java/com/foodymoody/be/collection/domain/FeedIds.java
  be/src/main/java/com/foodymoody/be/collection/infra/persistence/FeedCollectionRepositoryImpl.java
  be/src/main/java/com/foodymoody/be/collection/infra/persistence/jpa/FeedCollectionJpaRepository.java
  be/src/main/java/com/foodymoody/be/collection/infra/usecase/CollectionWriteUseCase.java
  be/src/main/java/com/foodymoody/be/collection/presentation/CollectionCreateRequest.java
  be/src/main/java/com/foodymoody/be/collection/presentation/CollectionWriteController.java
  be/src/main/java/com/foodymoody/be/comment/application/CommentMapper.java
  be/src/main/java/com/foodymoody/be/comment/application/CommentWriteService.java
  be/src/main/java/com/foodymoody/be/comment/application/ReplyReadService.java
  be/src/main/java/com/foodymoody/be/comment/application/dto/response/MemberCommentSummaryResponse.java
  be/src/main/java/com/foodymoody/be/comment/application/dto/response/MemberReplySummaryResponse.java
  be/src/main/java/com/foodymoody/be/comment/domain/entity/CommentRepliedAddedEvent.java
  be/src/main/java/com/foodymoody/be/comment/domain/entity/Reply.java
  be/src/main/java/com/foodymoody/be/comment/domain/repository/ReplyRepository.java
  be/src/main/java/com/foodymoody/be/comment/infra/persistence/ReplyRepositoryImpl.java
  be/src/main/java/com/foodymoody/be/comment/infra/persistence/jpa/ReplyJpaRepository.java
  be/src/main/java/com/foodymoody/be/comment_heart/presentation/CommentHeartWriteController.java
  be/src/main/java/com/foodymoody/be/common/event/NotificationType.java
  be/src/main/java/com/foodymoody/be/common/util/ids/FeedCollectionId.java
  be/src/main/java/com/foodymoody/be/common/util/ids/IdFactory.java
  be/src/main/java/com/foodymoody/be/common/util/ids/ReplyId.java
  be/src/main/java/com/foodymoody/be/feed/repository/FeedRepository.java
  be/src/main/java/com/foodymoody/be/feed/service/FeedService.java
  be/src/main/java/com/foodymoody/be/reply_heart/application/ReplyHeartWriteService.java
  be/src/main/java/com/foodymoody/be/reply_heart/domain/ReplyHeart.java
  be/src/main/java/com/foodymoody/be/reply_heart/domain/ReplyHeartRepository.java
  be/src/main/java/com/foodymoody/be/reply_heart/infra/persistence/ReplyHeartRepositoryImpl.java
  be/src/main/java/com/foodymoody/be/reply_heart/infra/persistence/jpa/ReplyHeartJpaRepository.java
  be/src/main/java/com/foodymoody/be/reply_heart/infra/usecase/ReplyHeartAddedEvent.java
  be/src/main/java/com/foodymoody/be/reply_heart/infra/usecase/ReplyHeartWriteUseCase.java
  be/src/main/java/com/foodymoody/be/reply_heart_count/application/ReplyHeartCountWriteService.java
  be/src/main/java/com/foodymoody/be/reply_heart_count/domain/ReplyHeartCount.java
  be/src/main/java/com/foodymoody/be/reply_heart_count/domain/ReplyHeartCountRepository.java
  be/src/main/java/com/foodymoody/be/reply_heart_count/infra/persistence/ReplyHeartCountRepositoryImpl.java
  be/src/main/java/com/foodymoody/be/reply_heart_count/infra/persistence/jpa/ReplyHeartCountJpaRepository.java
  be/src/test/java/com/foodymoody/be/acceptance/collection/FeedCollectionAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/collection/FeedCollectionStep.java
  be/src/test/java/com/foodymoody/be/acceptance/comment/CommentAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/comment/CommentSteps.java
  be/src/test/java/com/foodymoody/be/acceptance/comment_heart/CommentHeartSteps.java
  be/src/test/java/com/foodymoody/be/acceptance/image/ImageAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/reply/ReplyAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/reply/ReplySteps.java
  be/src/test/java/com/foodymoody/be/acceptance/reply_heart/ReplyFeedHeartAcceptanceTest.java
Labels: BE, fix

#277 [BE] 대댓글 API 누락
  be/src/main/java/com/foodymoody/be/reply_heart/presentation/ReplyHeartWriteController.java
  be/src/test/java/com/foodymoody/be/acceptance/reply_heart/ReplyHeartSteps.java
Labels: BE, fix

#284 [FE] Modal 코드 분리
  fe/src/components/common/commentItem/CommentItem.tsx
  fe/src/components/common/modal/CommentAlert.tsx
  fe/src/components/common/modal/Modal.tsx
  fe/src/components/common/modal/TestModal.tsx
  fe/src/components/common/modal/index.tsx
  fe/src/components/common/modal/useModal.ts
  fe/src/pages/CollectionPage.tsx
  fe/src/pages/DetailFeedPage.tsx
  fe/src/recoil/modal/atom.ts
  fe/src/recoil/modal/selector.ts
  fe/src/types/modal.d.ts
Labels: FE, refactor, review

#288 상세 페이지 좋아요 조회 문제 해결 후 배포
  be/src/main/java/com/foodymoody/be/feed/application/FeedMapper.java
Labels: BE, fix

#290 [BE] 알림 오류 수정
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/com/foodymoody/be/collection/application/FeedCollectionWriterService.java
  be/src/main/java/com/foodymoody/be/collection/domain/FeedCollection.java
  be/src/main/java/com/foodymoody/be/collection/infra/persistence/jpa/FeedCollectionJpaRepository.java
  be/src/main/java/com/foodymoody/be/comment/application/dto/response/MemberReplySummaryResponse.java
  be/src/main/java/com/foodymoody/be/comment/domain/entity/CommentAddedEvent.java
  be/src/main/java/com/foodymoody/be/comment_heart/infra/usecase/CommentHeartWriteUseCase.java
  be/src/main/java/com/foodymoody/be/common/event/NotificationType.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/FeedCollectionReadService.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/FeedCollectionWriterService.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/CommentIds.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedCollection.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedCollectionDao.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedCollectionRepository.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedCollectionSummary.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedIds.java
  be/src/main/java/com/foodymoody/be/feed_collection/infra/persistence/FeedCollectionDaoImpl.java
  be/src/main/java/com/foodymoody/be/feed_collection/infra/persistence/FeedCollectionRepositoryImpl.java
  be/src/main/java/com/foodymoody/be/feed_collection/infra/persistence/jpa/FeedCollectionJpaRepository.java
  be/src/main/java/com/foodymoody/be/feed_collection/infra/usecase/AuthorSummaryResponse.java
  be/src/main/java/com/foodymoody/be/feed_collection/infra/usecase/FeedCollectionDetail.java
  be/src/main/java/com/foodymoody/be/feed_collection/infra/usecase/FeedCollectionReadUseCase.java
  be/src/main/java/com/foodymoody/be/feed_collection/infra/usecase/FeedCollectionWriteUseCase.java
  be/src/main/java/com/foodymoody/be/feed_collection/infra/usecase/FeedSummaryResponse.java
  be/src/main/java/com/foodymoody/be/feed_collection/presentation/FeedCollectionCreateRequest.java
  be/src/main/java/com/foodymoody/be/feed_collection/presentation/FeedCollectionReadController.java
  be/src/main/java/com/foodymoody/be/feed_collection/presentation/FeedCollectionWriteController.java
  be/src/main/java/com/foodymoody/be/notification/application/NotificationSpecs.java
  be/src/main/java/com/foodymoody/be/notification/application/NotificationSummaryReadService.java
  be/src/main/java/com/foodymoody/be/notification/application/NotificationSummarySpecs.java
  be/src/main/java/com/foodymoody/be/notification/domain/NotificationSummary.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/util/NotificationMapper.java
  be/src/main/java/com/foodymoody/be/notification/infra/usecase/NotificationSseReadUseCase.java
  be/src/main/java/com/foodymoody/be/notification/infra/usecase/NotificationUseCase.java
  be/src/main/java/com/foodymoody/be/notification_setting/application/NotificationMapper.java
  be/src/main/java/com/foodymoody/be/notification_setting/application/NotificationSettingWriteService.java
  be/src/main/java/com/foodymoody/be/notification_setting/application/dto/NotificationSettingUpdateRequest.java
  be/src/main/java/com/foodymoody/be/notification_setting/domain/NotificationSetting.java
  be/src/main/java/com/foodymoody/be/notification_setting/domain/NotificationSettingSummary.java
  be/src/main/java/com/foodymoody/be/notification_setting/infra/persistence/jpa/NotificationSettingJpaRepository.java
  be/src/main/java/com/foodymoody/be/reply_heart/infra/usecase/ReplyHeartWriteUseCase.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection/FeedCollectionAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection/FeedCollectionSteps.java
  be/src/test/java/com/foodymoody/be/acceptance/notification_setting/NotificationSettingSteps.java
  be/src/test/java/com/foodymoody/be/notification/util/NotificationFixture.java
Labels: BE, feat

#291 [BE] 알림 오류 수정
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/com/foodymoody/be/collection/application/FeedCollectionWriterService.java
  be/src/main/java/com/foodymoody/be/collection/domain/FeedCollection.java
  be/src/main/java/com/foodymoody/be/collection/infra/persistence/jpa/FeedCollectionJpaRepository.java
  be/src/main/java/com/foodymoody/be/comment/application/dto/response/MemberReplySummaryResponse.java
  be/src/main/java/com/foodymoody/be/comment/domain/entity/CommentAddedEvent.java
  be/src/main/java/com/foodymoody/be/comment_heart/infra/usecase/CommentHeartWriteUseCase.java
  be/src/main/java/com/foodymoody/be/common/event/NotificationType.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/FeedCollectionReadService.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/FeedCollectionWriterService.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/CommentIds.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedCollection.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedCollectionDao.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedCollectionRepository.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedCollectionSummary.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedIds.java
  be/src/main/java/com/foodymoody/be/feed_collection/infra/persistence/FeedCollectionDaoImpl.java
  be/src/main/java/com/foodymoody/be/feed_collection/infra/persistence/FeedCollectionRepositoryImpl.java
  be/src/main/java/com/foodymoody/be/feed_collection/infra/persistence/jpa/FeedCollectionJpaRepository.java
  be/src/main/java/com/foodymoody/be/feed_collection/infra/usecase/AuthorSummaryResponse.java
  be/src/main/java/com/foodymoody/be/feed_collection/infra/usecase/FeedCollectionDetail.java
  be/src/main/java/com/foodymoody/be/feed_collection/infra/usecase/FeedCollectionReadUseCase.java
  be/src/main/java/com/foodymoody/be/feed_collection/infra/usecase/FeedCollectionWriteUseCase.java
  be/src/main/java/com/foodymoody/be/feed_collection/infra/usecase/FeedSummaryResponse.java
  be/src/main/java/com/foodymoody/be/feed_collection/presentation/FeedCollectionCreateRequest.java
  be/src/main/java/com/foodymoody/be/feed_collection/presentation/FeedCollectionReadController.java
  be/src/main/java/com/foodymoody/be/feed_collection/presentation/FeedCollectionWriteController.java
  be/src/main/java/com/foodymoody/be/notification/application/NotificationSpecs.java
  be/src/main/java/com/foodymoody/be/notification/application/NotificationSummaryReadService.java
  be/src/main/java/com/foodymoody/be/notification/application/NotificationSummarySpecs.java
  be/src/main/java/com/foodymoody/be/notification/domain/NotificationSummary.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/util/NotificationMapper.java
  be/src/main/java/com/foodymoody/be/notification/infra/usecase/NotificationSseReadUseCase.java
  be/src/main/java/com/foodymoody/be/notification/infra/usecase/NotificationUseCase.java
  be/src/main/java/com/foodymoody/be/notification_setting/application/NotificationMapper.java
  be/src/main/java/com/foodymoody/be/notification_setting/application/NotificationSettingWriteService.java
  be/src/main/java/com/foodymoody/be/notification_setting/application/dto/NotificationSettingUpdateRequest.java
  be/src/main/java/com/foodymoody/be/notification_setting/domain/NotificationSetting.java
  be/src/main/java/com/foodymoody/be/notification_setting/domain/NotificationSettingSummary.java
  be/src/main/java/com/foodymoody/be/notification_setting/infra/persistence/jpa/NotificationSettingJpaRepository.java
  be/src/main/java/com/foodymoody/be/reply_heart/infra/usecase/ReplyHeartWriteUseCase.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection/FeedCollectionAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection/FeedCollectionSteps.java
  be/src/test/java/com/foodymoody/be/acceptance/notification_setting/NotificationSettingSteps.java
  be/src/test/java/com/foodymoody/be/notification/util/NotificationFixture.java
Labels: BE, fix

#292 [BE] 알림 오류 수정
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/com/foodymoody/be/collection/application/FeedCollectionWriterService.java
  be/src/main/java/com/foodymoody/be/collection/domain/FeedCollection.java
  be/src/main/java/com/foodymoody/be/collection/infra/persistence/jpa/FeedCollectionJpaRepository.java
  be/src/main/java/com/foodymoody/be/comment/application/dto/response/MemberReplySummaryResponse.java
  be/src/main/java/com/foodymoody/be/comment/domain/entity/CommentAddedEvent.java
  be/src/main/java/com/foodymoody/be/comment_heart/infra/usecase/CommentHeartWriteUseCase.java
  be/src/main/java/com/foodymoody/be/common/event/NotificationType.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/FeedCollectionReadService.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/FeedCollectionWriterService.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/CommentIds.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedCollection.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedCollectionDao.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedCollectionRepository.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedCollectionSummary.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedIds.java
  be/src/main/java/com/foodymoody/be/feed_collection/infra/persistence/FeedCollectionDaoImpl.java
  be/src/main/java/com/foodymoody/be/feed_collection/infra/persistence/FeedCollectionRepositoryImpl.java
  be/src/main/java/com/foodymoody/be/feed_collection/infra/persistence/jpa/FeedCollectionJpaRepository.java
  be/src/main/java/com/foodymoody/be/feed_collection/infra/usecase/AuthorSummaryResponse.java
  be/src/main/java/com/foodymoody/be/feed_collection/infra/usecase/FeedCollectionDetail.java
  be/src/main/java/com/foodymoody/be/feed_collection/infra/usecase/FeedCollectionReadUseCase.java
  be/src/main/java/com/foodymoody/be/feed_collection/infra/usecase/FeedCollectionWriteUseCase.java
  be/src/main/java/com/foodymoody/be/feed_collection/infra/usecase/FeedSummaryResponse.java
  be/src/main/java/com/foodymoody/be/feed_collection/presentation/FeedCollectionCreateRequest.java
  be/src/main/java/com/foodymoody/be/feed_collection/presentation/FeedCollectionReadController.java
  be/src/main/java/com/foodymoody/be/feed_collection/presentation/FeedCollectionWriteController.java
  be/src/main/java/com/foodymoody/be/notification/application/NotificationSpecs.java
  be/src/main/java/com/foodymoody/be/notification/application/NotificationSummaryReadService.java
  be/src/main/java/com/foodymoody/be/notification/application/NotificationSummarySpecs.java
  be/src/main/java/com/foodymoody/be/notification/domain/NotificationSummary.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/util/NotificationMapper.java
  be/src/main/java/com/foodymoody/be/notification/infra/usecase/NotificationSseReadUseCase.java
  be/src/main/java/com/foodymoody/be/notification/infra/usecase/NotificationUseCase.java
  be/src/main/java/com/foodymoody/be/notification_setting/application/NotificationMapper.java
  be/src/main/java/com/foodymoody/be/notification_setting/application/NotificationSettingWriteService.java
  be/src/main/java/com/foodymoody/be/notification_setting/application/dto/NotificationSettingUpdateRequest.java
  be/src/main/java/com/foodymoody/be/notification_setting/domain/NotificationSetting.java
  be/src/main/java/com/foodymoody/be/notification_setting/domain/NotificationSettingSummary.java
  be/src/main/java/com/foodymoody/be/notification_setting/infra/persistence/jpa/NotificationSettingJpaRepository.java
  be/src/main/java/com/foodymoody/be/reply_heart/infra/usecase/ReplyHeartWriteUseCase.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection/FeedCollectionAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection/FeedCollectionSteps.java
  be/src/test/java/com/foodymoody/be/acceptance/notification_setting/NotificationSettingSteps.java
  be/src/test/java/com/foodymoody/be/notification/util/NotificationFixture.java
Labels: BE, fix

#295 [BE] RestDocs 및 오타 수정
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/com/foodymoody/be/common/event/NotificationType.java
Labels: BE, feat

#296 [BE] RestDocs 및 오타 수정
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/com/foodymoody/be/common/event/NotificationType.java
Labels: BE, fix

#297 [BE] RestDocs 및 오타 수정
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/com/foodymoody/be/common/event/NotificationType.java
Labels: BE, fix

#300 [BE] 댓글 및 대댓글 좋아요 오류 수정
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/com/foodymoody/be/comment/infra/persistence/jpa/ReplyJpaRepository.java
  be/src/main/java/com/foodymoody/be/notification/presentation/NotificationReadController.java
  be/src/main/java/com/foodymoody/be/reply_heart/application/ReplyHeartWriteService.java
  be/src/main/java/com/foodymoody/be/reply_heart/domain/ReplyHeart.java
  be/src/main/java/com/foodymoody/be/reply_heart/domain/ReplyHeartRepository.java
  be/src/main/java/com/foodymoody/be/reply_heart/infra/persistence/ReplyHeartRepositoryImpl.java
  be/src/main/java/com/foodymoody/be/reply_heart/infra/persistence/jpa/ReplyHeartJpaRepository.java
  be/src/main/java/com/foodymoody/be/reply_heart/infra/usecase/ReplyHeartWriteUseCase.java
  be/src/test/java/com/foodymoody/be/acceptance/notification/NotificationSteps.java
Labels: BE, fix

#305 [BE] 알림 API 문서 수정
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/com/foodymoody/be/common/util/ids/IdFactory.java
  be/src/main/java/com/foodymoody/be/common/util/ids/NotificationId.java
  be/src/main/java/com/foodymoody/be/notification/application/FeedNotificationWriteService.java
  be/src/main/java/com/foodymoody/be/notification/application/NotificationMapper.java
  be/src/main/java/com/foodymoody/be/notification/application/NotificationWriteService.java
  be/src/main/java/com/foodymoody/be/notification/domain/FeedNotification.java
  be/src/main/java/com/foodymoody/be/notification/domain/NotificationIdFactory.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/CommentEventHandler.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/CommentHeartEventHandler.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/CommentRepliedEventHandler.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/CommentReplyHeartEventHandler.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/util/NotificationMapper.java
  be/src/main/java/com/foodymoody/be/notification/infra/persistence/jpa/NotificationJpaRepository.java
  be/src/main/java/com/foodymoody/be/notification/infra/usecase/NotificationUseCase.java
  be/src/main/java/com/foodymoody/be/notification/presentation/NotificationMapper.java
  be/src/main/java/com/foodymoody/be/notification/presentation/NotificationReadController.java
  be/src/main/java/com/foodymoody/be/notification/presentation/NotificationWriteController.java
  be/src/main/java/com/foodymoody/be/notification/presentation/dto/ChangeAllNotificationStatusRequest.java
  be/src/main/java/com/foodymoody/be/notification/presentation/dto/DeleteNotificationsRequest.java
  be/src/main/java/com/foodymoody/be/notification/presentation/dto/NotificationStatus.java
  be/src/test/java/com/foodymoody/be/acceptance/notification/FeedNotificationAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/notification/NotificationSteps.java
  be/src/test/java/com/foodymoody/be/notification/util/NotificationFixture.java
Labels: BE, refactor

#306 [BE] 알림 api 수정
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/com/foodymoody/be/common/util/ids/IdFactory.java
  be/src/main/java/com/foodymoody/be/common/util/ids/NotificationId.java
  be/src/main/java/com/foodymoody/be/notification/application/FeedNotificationWriteService.java
  be/src/main/java/com/foodymoody/be/notification/application/NotificationMapper.java
  be/src/main/java/com/foodymoody/be/notification/application/NotificationWriteService.java
  be/src/main/java/com/foodymoody/be/notification/domain/FeedNotification.java
  be/src/main/java/com/foodymoody/be/notification/domain/NotificationIdFactory.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/CommentEventHandler.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/CommentHeartEventHandler.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/CommentRepliedEventHandler.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/CommentReplyHeartEventHandler.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/util/NotificationMapper.java
  be/src/main/java/com/foodymoody/be/notification/infra/persistence/jpa/NotificationJpaRepository.java
  be/src/main/java/com/foodymoody/be/notification/infra/usecase/NotificationUseCase.java
  be/src/main/java/com/foodymoody/be/notification/presentation/NotificationMapper.java
  be/src/main/java/com/foodymoody/be/notification/presentation/NotificationReadController.java
  be/src/main/java/com/foodymoody/be/notification/presentation/NotificationWriteController.java
  be/src/main/java/com/foodymoody/be/notification/presentation/dto/ChangeAllNotificationStatusRequest.java
  be/src/main/java/com/foodymoody/be/notification/presentation/dto/DeleteNotificationsRequest.java
  be/src/main/java/com/foodymoody/be/notification/presentation/dto/NotificationStatus.java
  be/src/test/java/com/foodymoody/be/acceptance/notification/FeedNotificationAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/notification/NotificationSteps.java
  be/src/test/java/com/foodymoody/be/notification/util/NotificationFixture.java
Labels: BE, refactor

#308 [FE] 엔터시 인풋 포커스 이동 추가, input2에서 input으로 변경
  fe/src/components/commentInput/CommentInputContainer.tsx
  fe/src/components/common/button/Button.tsx
  fe/src/components/common/commentItem/CommentBox.tsx
  fe/src/components/common/commentItem/CommentItem.tsx
  fe/src/components/common/commentItem/ReplyItem.tsx
  fe/src/components/common/input/CommentInput.tsx
  fe/src/components/common/input/Input.tsx
  fe/src/components/common/input/Input2.tsx
  fe/src/components/common/menuItemEditor/MenuItemEditor.tsx
  fe/src/components/login/Login.tsx
  fe/src/components/register/Register.tsx
  fe/src/components/searchPanelInput/SearchPanelInput.tsx
  fe/src/components/validatedInput/ValidatedInput.tsx
  fe/src/pages/NewFeedPage.tsx
Labels: FE, feat

#310 [FE] 알림 페이지 UI 및 데이터 연동
  fe/src/components/common/skeleton/NotiSkeleton.tsx
  fe/src/components/notification/NotiItem.tsx
  fe/src/components/notification/NotiList.tsx
  fe/src/pages/NotiPage.tsx
  fe/src/service/axios/notifications/notifications.ts
  fe/src/service/constants/endpoint.ts
  fe/src/service/constants/queryKey.ts
  fe/src/service/queries/feed.ts
  fe/src/service/queries/notification.ts
  fe/src/types/notification.d.ts
Labels: FE, feat, review

#322 [BE] 컬렉션 댓글 기능 구현
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/com/foodymoody/be/comment/application/CommentWriteService.java
  be/src/main/java/com/foodymoody/be/comment/application/FeedCommentReadService.java
  be/src/main/java/com/foodymoody/be/comment/infra/usecase/CommentUseCase.java
  be/src/main/java/com/foodymoody/be/comment/infra/usecase/FeedCommentReadUseCase.java
  be/src/main/java/com/foodymoody/be/comment/infra/usecase/MemberReplyUseCase.java
  be/src/main/java/com/foodymoody/be/comment/persentation/CommentWriteController.java
  be/src/main/java/com/foodymoody/be/comment/persentation/FeedCommentController.java
  be/src/main/java/com/foodymoody/be/comment/persentation/ReplyController.java
  be/src/main/java/com/foodymoody/be/comment_heart/infra/usecase/CommentHeartWriteUseCase.java
  be/src/main/java/com/foodymoody/be/comment_heart/presentation/CommentHeartWriteController.java
  be/src/main/java/com/foodymoody/be/common/util/CommentContent.java
  be/src/main/java/com/foodymoody/be/common/util/IdResponse.java
  be/src/main/java/com/foodymoody/be/common/util/ids/BaseId.java
  be/src/main/java/com/foodymoody/be/common/util/ids/FeedCollectionCommentId.java
  be/src/main/java/com/foodymoody/be/common/util/ids/FeedCollectionReplyId.java
  be/src/main/java/com/foodymoody/be/common/util/ids/IdFactory.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/FeedCollectionWriterService.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/CommentIds.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedCollection.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedCollectionRepository.java
  be/src/main/java/com/foodymoody/be/feed_collection/infra/persistence/FeedCollectionRepositoryImpl.java
  be/src/main/java/com/foodymoody/be/feed_collection/infra/usecase/FeedCollectionReadUseCase.java
  be/src/main/java/com/foodymoody/be/feed_collection/infra/usecase/FeedCollectionWriteUseCase.java
  be/src/main/java/com/foodymoody/be/feed_collection/infra/usecase/FeedSummaryResponse.java
  be/src/main/java/com/foodymoody/be/feed_collection/presentation/FeedCollectionCreateRequest.java
  be/src/main/java/com/foodymoody/be/feed_collection/presentation/FeedCollectionReadController.java
  be/src/main/java/com/foodymoody/be/feed_collection/presentation/FeedCollectionWriteController.java
  be/src/main/java/com/foodymoody/be/feed_collection_comment/application/FeedCollectionCommentMapper.java
  be/src/main/java/com/foodymoody/be/feed_collection_comment/application/FeedCollectionCommentWriteService.java
  be/src/main/java/com/foodymoody/be/feed_collection_comment/domain/FeedCollectionComment.java
  be/src/main/java/com/foodymoody/be/feed_collection_comment/domain/FeedCollectionCommentRepository.java
  be/src/main/java/com/foodymoody/be/feed_collection_comment/domain/FeedCollectionReplyIds.java
  be/src/main/java/com/foodymoody/be/feed_collection_comment/infra/persistence/FeedCollectionCommentRepositoryImpl.java
  be/src/main/java/com/foodymoody/be/feed_collection_comment/infra/persistence/jpa/FeedCollectionCommentJpaRepository.java
  be/src/main/java/com/foodymoody/be/feed_collection_comment/infra/usecase/FeedCollectionCommentWriteUseCase.java
  be/src/main/java/com/foodymoody/be/feed_collection_comment/presentation/FeedCollectionCommentWriteController.java
  be/src/main/java/com/foodymoody/be/notification/infra/usecase/NotificationSseReadUseCase.java
  be/src/main/java/com/foodymoody/be/notification/presentation/NotificationMapper.java
  be/src/main/java/com/foodymoody/be/notification/presentation/NotificationReadController.java
  be/src/main/java/com/foodymoody/be/notification/presentation/NotificationWriteController.java
  be/src/main/java/com/foodymoody/be/notification_setting/application/NotificationSettingReadService.java
  be/src/main/java/com/foodymoody/be/notification_setting/application/NotificationSettingWriteService.java
  be/src/main/java/com/foodymoody/be/notification_setting/presentation/NotificationSettingReadController.java
  be/src/main/java/com/foodymoody/be/notification_setting/presentation/NotificationSettingWriteController.java
  be/src/main/java/com/foodymoody/be/reply_heart/infra/usecase/ReplyHeartWriteUseCase.java
  be/src/main/java/com/foodymoody/be/reply_heart/presentation/ReplyHeartWriteController.java
  be/src/main/java/com/foodymoody/be/sse/controller/SseController.java
  be/src/main/java/com/foodymoody/be/sse/service/SseAsyncService.java
  be/src/main/java/com/foodymoody/be/sse/service/SseService.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection/FeedCollectionAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection/FeedCollectionSteps.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection_comment/FeedCollectionCommentAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection_comment/FeedCollectionCommentSteps.java
Labels: BE, feat

#325 [FE] 알림 아이콘 sse 연동 추가
  fe/package-lock.json
  fe/package.json
  fe/src/assets/notiTrue.svg
  fe/src/assets/notification.svg
  fe/src/components/common/headerMob/HeaderMob.tsx
  fe/src/components/common/icon/NotiIcon.tsx
  fe/src/components/common/icon/icons.ts
  fe/src/components/common/navibar/NaviBar.tsx
  fe/src/components/common/notiIcon/NotiIcon.tsx
  fe/src/service/axios/fetcher.ts
Labels: FE, feat, review

#329 [FE] Button 컴포넌트 스타일 추가
  fe/src/components/common/button/Button.tsx
Labels: FE, feat, review

#314 [BE] 컬렉션 피드 조회
  be/src/main/java/com/foodymoody/be/common/util/ids/IdFactory.java
  be/src/main/java/com/foodymoody/be/common/util/ids/StoreMoodId.java
  be/src/main/java/com/foodymoody/be/feed/application/FeedMapper.java
  be/src/main/java/com/foodymoody/be/feed/application/FeedReadService.java
  be/src/main/java/com/foodymoody/be/feed/application/StoreMoodReadService.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/request/CollectionReadFeedListServiceRequest.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/request/FeedRegisterRequest.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/request/FeedServiceRegisterRequest.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/request/FeedServiceUpdateRequest.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/request/FeedUpdateRequest.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/CollectionReadAllFeedResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedStoreMoodResponse.java
  be/src/main/java/com/foodymoody/be/feed/domain/entity/Feed.java
  be/src/main/java/com/foodymoody/be/feed/domain/entity/FeedStoreMood.java
  be/src/main/java/com/foodymoody/be/feed/domain/entity/ImageMenu.java
  be/src/main/java/com/foodymoody/be/feed/domain/entity/StoreMood.java
  be/src/main/java/com/foodymoody/be/feed/domain/entity/StoreMoodId.java
  be/src/main/java/com/foodymoody/be/feed/domain/entity/StoreMoods.java
  be/src/main/java/com/foodymoody/be/feed/domain/repository/FeedRepository.java
  be/src/main/java/com/foodymoody/be/feed/domain/repository/StoreMoodRepository.java
  be/src/main/java/com/foodymoody/be/feed/infra/usecase/CollectionUseCase.java
  be/src/main/java/com/foodymoody/be/feed/infra/usecase/FeedUseCase.java
  be/src/main/java/com/foodymoody/be/feed/presentation/CollectionController.java
  be/src/main/java/com/foodymoody/be/feed/presentation/FeedController.java
  be/src/main/java/com/foodymoody/be/feed/presentation/StoreMoodController.java
  be/src/main/java/com/foodymoody/be/feed_collection/infra/usecase/FeedCollectionReadUseCase.java
  be/src/test/java/com/foodymoody/be/acceptance/feed/FeedSteps.java
  be/src/test/java/com/foodymoody/be/acceptance/member/MemberAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/feed/application/FeedHeartCountServiceTest.java
Labels: BE, feat

#333 [BE] 컬렉션 좋아요 기능
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/com/foodymoody/be/common/util/ids/FeedCollectionCommentLikeId.java
  be/src/main/java/com/foodymoody/be/common/util/ids/FeedCollectionLikeId.java
  be/src/main/java/com/foodymoody/be/common/util/ids/FeedCollectionReplyLikeId.java
  be/src/main/java/com/foodymoody/be/common/util/ids/IdFactory.java
  be/src/main/java/com/foodymoody/be/feed_collection_comment_like/application/FeedCollectionCommentLikeWriteService.java
  be/src/main/java/com/foodymoody/be/feed_collection_comment_like/domain/FeedCollectionCommentLike.java
  be/src/main/java/com/foodymoody/be/feed_collection_comment_like/domain/FeedCollectionCommentLikeRepository.java
  be/src/main/java/com/foodymoody/be/feed_collection_comment_like/infra/persistence/FeedCollectionCommentLikeRepositoryImpl.java
  be/src/main/java/com/foodymoody/be/feed_collection_comment_like/infra/persistence/jpa/FeedCollectionCommentLikeJpaRepository.java
  be/src/main/java/com/foodymoody/be/feed_collection_comment_like/infra/usecase/FeedCollectionCommentLikeUseCase.java
  be/src/main/java/com/foodymoody/be/feed_collection_comment_like/presentation/FeedCollectionCommentLikeWriteController.java
  be/src/main/java/com/foodymoody/be/feed_collection_like/application/FeedCollectionLikeWriteService.java
  be/src/main/java/com/foodymoody/be/feed_collection_like/domain/FeedCollectionLike.java
  be/src/main/java/com/foodymoody/be/feed_collection_like/domain/FeedCollectionLikeRepository.java
  be/src/main/java/com/foodymoody/be/feed_collection_like/infra/persistence/FeedCollectionLikeRepositoryImpl.java
  be/src/main/java/com/foodymoody/be/feed_collection_like/infra/persistence/jpa/FeedCollectionLikeJpaRepository.java
  be/src/main/java/com/foodymoody/be/feed_collection_like/infra/usecase/FeedCollectionLikeWriteUseCase.java
  be/src/main/java/com/foodymoody/be/feed_collection_like/presentation/FeedCollectionLikeWriteController.java
  be/src/main/java/com/foodymoody/be/feed_collection_reply_like/application/FeedCollectionReplyLikeWriteService.java
  be/src/main/java/com/foodymoody/be/feed_collection_reply_like/domain/FeedCollectionReplyLike.java
  be/src/main/java/com/foodymoody/be/feed_collection_reply_like/domain/FeedCollectionReplyLikeRepository.java
  be/src/main/java/com/foodymoody/be/feed_collection_reply_like/infra/persistence/FeedCollectionReplyLikeRepositoryImpl.java
  be/src/main/java/com/foodymoody/be/feed_collection_reply_like/infra/persistence/jpa/FeedCollectionReplyLikeJpaRepository.java
  be/src/main/java/com/foodymoody/be/feed_collection_reply_like/infra/usecase/FeedCollectionReplyLikeWriteUseCase.java
  be/src/main/java/com/foodymoody/be/feed_collection_reply_like/presentation/FeedCollectionReplyLikeWriteController.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection_comment_like/FeedCollectionCommentLikeAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection_comment_like/FeedCollectionCommentLikeSteps.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection_like/FeedCollectionLikeAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection_like/FeedCollectionLikeSteps.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection_reply_like/FeedCollectionReplyLikeAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection_reply_like/FeedCollectionReplyLikeSteps.java
Labels: BE, feat

#337 [BE] Response, Request 타입 / Entity 타입 / 리팩토링
  be/src/main/java/com/foodymoody/be/common/util/ids/IdFactory.java
  be/src/main/java/com/foodymoody/be/common/util/ids/ImageMenuId.java
  be/src/main/java/com/foodymoody/be/feed/application/FeedMapper.java
  be/src/main/java/com/foodymoody/be/feed/application/ImageMenuMapper.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/request/FeedRegisterRequest.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/request/FeedRegisterRequestMenu.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/request/FeedServiceDeleteRequest.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/request/FeedServiceRegisterRequest.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/request/FeedServiceUpdateRequest.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/request/FeedUpdateRequest.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/request/ImageMenuPair.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/CollectionReadAllFeedResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedImageMenuResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedImageResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedMemberResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedMenuResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedReadAllResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedReadResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedRegisterResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedStoreMoodResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedTasteMoodResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/StoreMoodResponse.java
  be/src/main/java/com/foodymoody/be/feed/domain/entity/Feed.java
  be/src/main/java/com/foodymoody/be/feed/domain/entity/ImageMenu.java
  be/src/main/java/com/foodymoody/be/feed/domain/entity/StoreMood.java
  be/src/main/java/com/foodymoody/be/feed/infra/persistence/jpa/FeedJpaRepository.java
  be/src/main/java/com/foodymoody/be/feed/infra/usecase/CollectionUseCase.java
  be/src/main/java/com/foodymoody/be/feed/infra/usecase/FeedUseCase.java
  be/src/main/java/com/foodymoody/be/feed/infra/usecase/dto/ImageIdNamePair.java
  be/src/main/java/com/foodymoody/be/feed/presentation/CollectionController.java
  be/src/main/java/com/foodymoody/be/feed/presentation/FeedController.java
  be/src/main/java/com/foodymoody/be/feed/service/FeedService.java
  be/src/main/java/com/foodymoody/be/feed_heart/application/FeedHeartMapper.java
  be/src/main/java/com/foodymoody/be/feed_heart/application/FeedHeartService.java
  be/src/main/java/com/foodymoody/be/feed_heart/application/dto/request/FeedHeartRequest.java
  be/src/main/java/com/foodymoody/be/feed_heart/application/dto/request/FeedHeartServiceRequest.java
  be/src/main/java/com/foodymoody/be/feed_heart/application/dto/response/FeedHeartResponse.java
  be/src/main/java/com/foodymoody/be/feed_heart/domain/FeedHeartRepository.java
  be/src/main/java/com/foodymoody/be/feed_heart/domain/entity/FeedHeart.java
  be/src/main/java/com/foodymoody/be/feed_heart/presentation/FeedHeartController.java
  be/src/main/java/com/foodymoody/be/feed_heart_count/application/FeedHeartCountService.java
  be/src/main/java/com/foodymoody/be/feed_heart_count/domain/FeedHeartCountRepository.java
  be/src/main/java/com/foodymoody/be/feed_heart_count/domain/entity/FeedHeartCount.java
  be/src/test/java/com/foodymoody/be/acceptance/member/MemberAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/feed/application/FeedHeartCountServiceTest.java
Labels: BE, feat, fix, refactor

#341 [FE] 알림 개별 읽음 확인 연동과 해당 피드, 프로필 이동 작업
  fe/src/components/common/button/Button.tsx
  fe/src/components/notification/NotiItem.tsx
  fe/src/components/notification/NotiList.tsx
  fe/src/constants/path.ts
  fe/src/hooks/usePageNavigator.ts
  fe/src/pages/DetailFeedPage.tsx
  fe/src/pages/NotiPage.tsx
  fe/src/routes/router.tsx
  fe/src/service/axios/notifications/notifications.ts
  fe/src/service/queries/notification.ts
Labels: FE, feat, review

#343 [FE] 알림 설정 페이지 구현 및 설정 페이지 수정
  fe/src/components/common/headerMob/HeaderMob.tsx
  fe/src/components/common/navibar/NaviBar.tsx
  fe/src/components/common/switch/Switch.tsx
  fe/src/components/notification/NotiItem.tsx
  fe/src/components/profileUserInfo/ProfileUserInfo.tsx
  fe/src/constants/path.ts
  fe/src/hooks/usePageNavigator.ts
  fe/src/pages/AccountSettingPage.tsx
  fe/src/pages/NotiSettingPage.tsx
  fe/src/pages/PasswordPage.tsx
  fe/src/pages/ProfileEditPage.tsx
  fe/src/pages/SettingPage.tsx
  fe/src/routes/router.tsx
Labels: FE, feat, refactor, review

#345 [BE] 단위 테스트 코드 작성
  be/src/main/java/com/foodymoody/be/feed/application/FeedMapper.java
  be/src/main/java/com/foodymoody/be/feed/application/FeedReadService.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedMemberResponse.java
  be/src/main/java/com/foodymoody/be/feed/domain/entity/StoreMood.java
  be/src/main/java/com/foodymoody/be/feed/infra/usecase/FeedUseCase.java
  be/src/test/java/com/foodymoody/be/feed/application/FeedMapperTest.java
  be/src/test/java/com/foodymoody/be/feed/application/FeedReadServiceTest.java
  be/src/test/java/com/foodymoody/be/feed/application/FeedWriteServiceTest.java
  be/src/test/java/com/foodymoody/be/feed/application/MenuMapperTest.java
Labels: BE, test
