Repository foody-moody/foodymoody, pull requests merged in 2023-11, with the labels that each got.

#112 [BE] Images, Menus 관계 수정
  be/src/main/java/com/foodymoody/be/feed/domain/Feed.java
  be/src/main/java/com/foodymoody/be/feed/domain/ImageMenu.java
  be/src/main/java/com/foodymoody/be/feed/domain/ImageMenus.java
  be/src/main/java/com/foodymoody/be/feed/domain/StoreMood.java
  be/src/main/java/com/foodymoody/be/feed/domain/util/ImageMenuMapper.java
  be/src/main/java/com/foodymoody/be/feed/service/FeedService.java
  be/src/main/java/com/foodymoody/be/feed/util/FeedMapper.java
  be/src/main/java/com/foodymoody/be/mood/domain/Mood.java
Labels: BE, refactor

#116 [BE] Mood DB 적용
  be/src/main/java/com/foodymoody/be/feed/domain/Feed.java
  be/src/main/java/com/foodymoody/be/feed/domain/StoreMood.java
  be/src/main/java/com/foodymoody/be/feed/dto/response/FeedReadAllResponse.java
  be/src/main/java/com/foodymoody/be/feed/dto/response/FeedReadResponse.java
  be/src/main/java/com/foodymoody/be/feed/service/FeedService.java
  be/src/main/java/com/foodymoody/be/feed/util/FeedMapper.java
  be/src/main/java/com/foodymoody/be/mood/repository/MoodRepository.java
  be/src/test/resources/application-db.yml
  be/src/test/resources/data.sql
Labels: BE, feat, fix, refactor

#120 [BE] Mood Response 수정 완료
  be/src/main/java/com/foodymoody/be/feed/domain/Feed.java
  be/src/main/java/com/foodymoody/be/feed/dto/response/FeedReadAllResponse.java
  be/src/main/java/com/foodymoody/be/feed/dto/response/FeedReadResponse.java
  be/src/main/java/com/foodymoody/be/feed/dto/response/FeedStoreMoodResponse.java
  be/src/main/java/com/foodymoody/be/feed/service/FeedService.java
  be/src/main/java/com/foodymoody/be/feed/util/FeedMapper.java
  be/src/test/java/com/foodymoody/be/feed/FeedSteps.java
Labels: BE, feat, refactor

#119 [FE] DeatilModalPage 구현
  fe/src/components/common/carousel/Carousel.tsx
  fe/src/components/common/dim/Dim.tsx
  fe/src/components/common/feedAction/FeedAction.tsx
  fe/src/components/common/headerMob/HeaderMob.tsx
  fe/src/components/common/input/Input.tsx
  fe/src/components/common/input/InputCore.tsx
  fe/src/components/common/navibar/NaviBar.tsx
  fe/src/components/common/textarea/Textarea.tsx
  fe/src/components/feedMain/FeedMainItem.tsx
  fe/src/hooks/useLockBodyScroll.ts
  fe/src/pages/DetailFeedPage.tsx
  fe/src/pages/HomePage.tsx
  fe/src/pages/Layout.tsx
  fe/src/pages/NewFeedPage.tsx
  fe/src/pages/ProfilePage.tsx
  fe/src/routes/router.tsx
  fe/src/styles/customScrollStyle.ts
  fe/src/types/feed.d.ts
Labels: FE, feat, review

#125 [BE] 백엔드 릴리즈
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/com/foodymoody/be/DocumentController.java
  be/src/main/java/com/foodymoody/be/comment/controller/FeedCommentController.java
  be/src/main/java/com/foodymoody/be/comment/controller/dto/CommentResponse.java
  be/src/main/java/com/foodymoody/be/comment/repository/CommentRepository.java
  be/src/main/java/com/foodymoody/be/comment/service/CommentMapper.java
  be/src/main/java/com/foodymoody/be/comment/service/CommentService.java
  be/src/main/java/com/foodymoody/be/comment/service/FeedCommentService.java
  be/src/main/java/com/foodymoody/be/common/exception/DuplicateMemberEmailException.java
  be/src/main/java/com/foodymoody/be/common/exception/DuplicateNicknameException.java
  be/src/main/java/com/foodymoody/be/common/exception/ErrorMessage.java
  be/src/main/java/com/foodymoody/be/common/exception/InvalidReconfirmPasswordException.java
  be/src/main/java/com/foodymoody/be/common/exception/MemberNotFoundException.java
  be/src/main/java/com/foodymoody/be/feed/domain/Feed.java
  be/src/main/java/com/foodymoody/be/feed/domain/ImageMenu.java
  be/src/main/java/com/foodymoody/be/feed/domain/ImageMenus.java
  be/src/main/java/com/foodymoody/be/feed/domain/StoreMood.java
  be/src/main/java/com/foodymoody/be/feed/domain/util/ImageMenuMapper.java
  be/src/main/java/com/foodymoody/be/feed/dto/response/FeedReadAllResponse.java
  be/src/main/java/com/foodymoody/be/feed/dto/response/FeedReadResponse.java
  be/src/main/java/com/foodymoody/be/feed/dto/response/FeedStoreMoodResponse.java
  be/src/main/java/com/foodymoody/be/feed/service/FeedService.java
  be/src/main/java/com/foodymoody/be/feed/util/FeedMapper.java
  be/src/main/java/com/foodymoody/be/member/controller/MemberController.java
  be/src/main/java/com/foodymoody/be/member/controller/dto/MemberProfileFeedPreviewResponse.java
  be/src/main/java/com/foodymoody/be/member/controller/dto/MemberProfileResponse.java
  be/src/main/java/com/foodymoody/be/member/controller/dto/MemberSignupRequest.java
  be/src/main/java/com/foodymoody/be/member/controller/dto/MemberSignupResponse.java
  be/src/main/java/com/foodymoody/be/member/domain/Member.java
  be/src/main/java/com/foodymoody/be/member/repository/MemberRepository.java
  be/src/main/java/com/foodymoody/be/member/service/MemberService.java
  be/src/main/java/com/foodymoody/be/member/util/MemberMapper.java
  be/src/main/java/com/foodymoody/be/mood/domain/Mood.java
  be/src/main/java/com/foodymoody/be/mood/repository/MoodRepository.java
  be/src/test/java/com/foodymoody/be/acceptance/comment/CommentAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/comment/CommentSteps.java
  be/src/test/java/com/foodymoody/be/acceptance/member/MemberSteps.java
  be/src/test/java/com/foodymoody/be/acceptance/member/MemberTest.java
  be/src/test/java/com/foodymoody/be/comment/service/CommentServiceTest.java
  be/src/test/java/com/foodymoody/be/comment/util/CommentFixture.java
  be/src/test/java/com/foodymoody/be/comment/util/CommentMapperTest.java
  be/src/test/java/com/foodymoody/be/docs/member/MemberAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/feed/FeedSteps.java
  be/src/test/java/com/foodymoody/be/member/util/MemberFixture.java
  be/src/test/resources/application-db.yml
  be/src/test/resources/data.sql
Labels: BE

#127 [FE] NewFeedPage 추가
  fe/src/pages/NewFeedPage.tsx
Labels: FE, feat

#126 [FE] newFeed/editFeed 기능
  fe/package-lock.json
  fe/package.json
  fe/src/api/auth/login.ts
  fe/src/api/feed/feed.ts
  fe/src/api/fetcher.ts
  fe/src/api/profile/profile.ts
  fe/src/assets/plus.svg
  fe/src/assets/plusOutline.svg
  fe/src/components/common/dropdown/Dropdown.tsx
  fe/src/components/common/feedUserInfo/FeedUserInfo.tsx
  fe/src/components/common/icon/icons.ts
  fe/src/components/common/input/Input.tsx
  fe/src/components/common/input/InputCore.tsx
  fe/src/components/common/menuItemEditor/ImageBox.tsx
  fe/src/components/common/menuItemEditor/MenuItemEditor.tsx
  fe/src/components/common/navibar/NaviBar.tsx
  fe/src/components/common/textarea/Textarea.tsx
  fe/src/components/login/Login.tsx
  fe/src/components/profileUserInfo/ProfileUserInfo.tsx
  fe/src/components/register/Register.tsx
  fe/src/constants/endpoint.ts
  fe/src/constants/path.ts
  fe/src/constants/queryKey.ts
  fe/src/hooks/auth/useAuth.ts
  fe/src/hooks/useMenuItem.ts
  fe/src/pages/DetailFeedPage.tsx
  fe/src/pages/NewFeedPage.tsx
  fe/src/queries/feed.ts
  fe/src/queries/profile.ts
  fe/src/routes/router.tsx
  fe/src/styles/customStyle.ts
  fe/src/types/auth.d.ts
  fe/src/types/badge.d.ts
  fe/src/types/feed.d.ts
  fe/src/types/profile.d.ts
Labels: FE, feat, review

#123 [BE] 로그인 API, 토큰 발급, 토큰 파싱
  be/build.gradle
  be/src/main/java/com/foodymoody/be/DocumentController.java
  be/src/main/java/com/foodymoody/be/auth/AuthController.java
  be/src/main/java/com/foodymoody/be/auth/controller/AuthController.java
  be/src/main/java/com/foodymoody/be/auth/controller/dto/LoginRequest.java
  be/src/main/java/com/foodymoody/be/auth/controller/dto/LoginResponse.java
  be/src/main/java/com/foodymoody/be/auth/domain/Principal.java
  be/src/main/java/com/foodymoody/be/auth/domain/RefreshToken.java
  be/src/main/java/com/foodymoody/be/auth/repository/RefreshTokenRepository.java
  be/src/main/java/com/foodymoody/be/auth/service/AuthService.java
  be/src/main/java/com/foodymoody/be/auth/service/TokenService.java
  be/src/main/java/com/foodymoody/be/auth/util/JwtUtil.java
  be/src/main/java/com/foodymoody/be/common/annotation/MemberEmail.java
  be/src/main/java/com/foodymoody/be/common/annotation/MemberEmailArgumentResolver.java
  be/src/main/java/com/foodymoody/be/common/annotation/MemberId.java
  be/src/main/java/com/foodymoody/be/common/annotation/MemberIdArgumentResolver.java
  be/src/main/java/com/foodymoody/be/common/config/WebConfig.java
  be/src/main/java/com/foodymoody/be/common/exception/ErrorMessage.java
  be/src/main/java/com/foodymoody/be/common/exception/IncorrectMemberPasswordException.java
  be/src/main/java/com/foodymoody/be/common/exception/InvalidAccessTokenException.java
  be/src/main/java/com/foodymoody/be/common/exception/InvalidTokenException.java
  be/src/main/java/com/foodymoody/be/member/controller/dto/MemberSignupRequest.java
  be/src/main/java/com/foodymoody/be/member/domain/Member.java
  be/src/main/java/com/foodymoody/be/member/repository/MemberJpaRepository.java
  be/src/main/java/com/foodymoody/be/member/repository/MemberRepository.java
  be/src/main/java/com/foodymoody/be/member/repository/dto/MemberCredential.java
  be/src/main/java/com/foodymoody/be/member/util/MemberMapper.java
  be/src/main/resources/application-jwt.yml
  be/src/main/resources/application-localdb.yml
  be/src/main/resources/application.yml
  be/src/test/java/com/foodymoody/be/acceptance/member/MemberSteps.java
  be/src/test/java/com/foodymoody/be/acceptance/member/MemberTest.java
  be/src/test/java/com/foodymoody/be/acceptance/util/DatabaseCleanup.java
  be/src/test/java/com/foodymoody/be/docs/auth/AuthSteps.java
  be/src/test/java/com/foodymoody/be/docs/auth/AuthTest.java
  be/src/test/resources/application-db.yml
  be/src/test/resources/application.yml
Labels: BE, feat

#143 [BE] Feed API Member 추가
  be/src/main/java/com/foodymoody/be/feed/controller/FeedController.java
  be/src/main/java/com/foodymoody/be/feed/domain/Feed.java
  be/src/main/java/com/foodymoody/be/feed/dto/request/FeedServiceRegisterRequest.java
  be/src/main/java/com/foodymoody/be/feed/dto/request/FeedServiceUpdateRequest.java
  be/src/main/java/com/foodymoody/be/feed/dto/response/FeedMemberResponse.java
  be/src/main/java/com/foodymoody/be/feed/dto/response/FeedReadResponse.java
  be/src/main/java/com/foodymoody/be/feed/dto/response/FeedTasteMoodResponse.java
  be/src/main/java/com/foodymoody/be/feed/service/FeedService.java
  be/src/main/java/com/foodymoody/be/feed/util/FeedMapper.java
  be/src/main/java/com/foodymoody/be/mood/service/MoodService.java
  be/src/test/java/com/foodymoody/be/feed/FeedSteps.java
  be/src/test/resources/data.sql
Labels: BE, feat

#146 [FE] comment 제한 사항 보완
  fe/package-lock.json
  fe/package.json
  fe/src/api/fetcher.ts
  fe/src/assets/face.svg
  fe/src/assets/userPlus.svg
  fe/src/components/common/Button/TextButton.tsx
  fe/src/components/common/commentItem/CommentItem.tsx
  fe/src/components/common/dropdown/Dropdown.tsx
  fe/src/components/common/icon/icons.ts
  fe/src/components/common/input/CommentInput.tsx
  fe/src/components/common/input/Input.tsx
  fe/src/components/common/navibar/NaviBar.tsx
  fe/src/components/profileUserInfo/ProfileUserInfo.tsx
  fe/src/hooks/useMenuItem.ts
  fe/src/pages/DetailFeedPage.tsx
  fe/src/pages/NewFeedPage.tsx
  fe/src/queries/auth.ts
  fe/src/utils/localStorage.ts
  fe/vite.config.ts
Labels: FE, feat

#157 [BE] Feed Member 인수테스트 적용
  be/src/main/java/com/foodymoody/be/feed/controller/FeedController.java
  be/src/test/java/com/foodymoody/be/acceptance/comment/CommentAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed/FeedAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed/FeedSteps.java
  be/src/test/java/com/foodymoody/be/member/util/MemberFixture.java
Labels: BE, feat

#161 [BE] 알람 조회,수정,삭제 기능
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/com/foodymoody/be/DocumentController.java
  be/src/main/java/com/foodymoody/be/auth/util/JwtUtil.java
  be/src/main/java/com/foodymoody/be/comment/domain/Comment.java
  be/src/main/java/com/foodymoody/be/comment/domain/CommentAddNotificationEvent.java
  be/src/main/java/com/foodymoody/be/comment/domain/CommentDomainMapper.java
  be/src/main/java/com/foodymoody/be/common/event/EventsConfiguration.java
  be/src/main/java/com/foodymoody/be/common/event/NotificationEvent.java
  be/src/main/java/com/foodymoody/be/common/event/NotificationEvents.java
  be/src/main/java/com/foodymoody/be/common/event/NotificationType.java
  be/src/main/java/com/foodymoody/be/common/filter/AccessTokenFilter.java
  be/src/main/java/com/foodymoody/be/common/util/HttpHeaderParser.java
  be/src/main/java/com/foodymoody/be/common/util/HttpHeaderType.java
  be/src/main/java/com/foodymoody/be/feed/domain/ImageMenus.java
  be/src/main/java/com/foodymoody/be/feed/domain/Menus.java
  be/src/main/java/com/foodymoody/be/feed/service/FeedService.java
  be/src/main/java/com/foodymoody/be/feed/util/FeedMapper.java
  be/src/main/java/com/foodymoody/be/member/controller/dto/MemberSignupRequest.java
  be/src/main/java/com/foodymoody/be/mood/controller/dto/MoodRegisterRequest.java
  be/src/main/java/com/foodymoody/be/notification/controller/NotificationController.java
  be/src/main/java/com/foodymoody/be/notification/controller/dto/ChangeAllNotificationStatusRequest.java
  be/src/main/java/com/foodymoody/be/notification/controller/dto/DeleteNotificationsRequest.java
  be/src/main/java/com/foodymoody/be/notification/controller/dto/NotificationResponse.java
  be/src/main/java/com/foodymoody/be/notification/controller/dto/NotificationStatus.java
  be/src/main/java/com/foodymoody/be/notification/domain/Notification.java
  be/src/main/java/com/foodymoody/be/notification/domain/NotificationId.java
  be/src/main/java/com/foodymoody/be/notification/repository/NotificationRepository.java
  be/src/main/java/com/foodymoody/be/notification/service/NotificationMapper.java
  be/src/main/java/com/foodymoody/be/notification/service/NotificationService.java
  be/src/main/java/com/foodymoody/be/sse/controller/SseController.java
  be/src/main/java/com/foodymoody/be/sse/service/SseAsyncService.java
  be/src/main/java/com/foodymoody/be/sse/service/SseService.java
  be/src/main/resources/application-auth.yml
  be/src/test/java/com/foodymoody/be/acceptance/AcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/member/MemberAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/member/MemberSteps.java
  be/src/test/java/com/foodymoody/be/acceptance/notification/NotificationAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/notification/NotificationSteps.java
  be/src/test/java/com/foodymoody/be/acceptance/util/DatabaseCleanup.java
  be/src/test/java/com/foodymoody/be/feed/mapper/FeedMapperTest.java
  be/src/test/java/com/foodymoody/be/notification/domain/NotificationTest.java
  be/src/test/java/com/foodymoody/be/notification/service/NotificationMapperTest.java
  be/src/test/java/com/foodymoody/be/notification/util/NotificationFixture.java
  be/src/test/resources/data.sql
Labels: BE, feat

#168 [FE] Toast 구현
  fe/package-lock.json
  fe/src/App.tsx
  fe/src/assets/toastError.svg
  fe/src/assets/toastNoti.svg
  fe/src/assets/toastSuccess.svg
  fe/src/components/common/icon/icons.ts
  fe/src/components/common/toast/Toast.tsx
  fe/src/recoil/toast/atom.ts
  fe/src/recoil/toast/useToast.ts
  fe/src/types/toast.d.ts
Labels: FE, feat, review

#171 [BE] 피드 이미지 관련 request, response 수정
  be/src/main/java/com/foodymoody/be/feed/controller/FeedController.java
  be/src/main/java/com/foodymoody/be/feed/domain/ImageMenu.java
  be/src/main/java/com/foodymoody/be/feed/domain/util/ImageMenuMapper.java
  be/src/main/java/com/foodymoody/be/feed/dto/response/FeedTasteMoodResponse.java
  be/src/main/java/com/foodymoody/be/feed/service/FeedService.java
  be/src/main/java/com/foodymoody/be/feed/service/dto/ImageIdNamePair.java
  be/src/main/java/com/foodymoody/be/feed/service/dto/MenuNameRatingPair.java
  be/src/main/java/com/foodymoody/be/feed/util/FeedMapper.java
  be/src/main/java/com/foodymoody/be/image/repository/ImageRepository.java
  be/src/main/java/com/foodymoody/be/image/service/ImageService.java
  be/src/main/java/com/foodymoody/be/image/util/ImageMapper.java
  be/src/main/java/com/foodymoody/be/menu/repository/MenuRepository.java
  be/src/main/java/com/foodymoody/be/menu/service/MenuService.java
  be/src/main/java/com/foodymoody/be/menu/util/MenuMapper.java
  be/src/main/java/com/foodymoody/be/mood/service/MoodService.java
  be/src/test/java/com/foodymoody/be/acceptance/feed/FeedAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed/FeedSteps.java
  be/src/test/java/com/foodymoody/be/feed/mapper/ImageMapperTest.java
  be/src/test/java/com/foodymoody/be/feed/mapper/MenuMapperTest.java
Labels: BE, feat, fix, refactor

#173 [BE] 댓글 리펙토링
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/com/foodymoody/be/comment/controller/CommentController.java
  be/src/main/java/com/foodymoody/be/comment/controller/dto/CommentResponse.java
  be/src/main/java/com/foodymoody/be/comment/controller/dto/EditCommentRequest.java
  be/src/main/java/com/foodymoody/be/comment/controller/dto/RegisterCommentRequest.java
  be/src/main/java/com/foodymoody/be/comment/domain/Comment.java
  be/src/main/java/com/foodymoody/be/comment/domain/CommentId.java
  be/src/main/java/com/foodymoody/be/comment/domain/ReplyComments.java
  be/src/main/java/com/foodymoody/be/comment/repository/CommentRepository.java
  be/src/main/java/com/foodymoody/be/comment/service/CommentMapper.java
  be/src/main/java/com/foodymoody/be/comment/service/CommentService.java
  be/src/main/java/com/foodymoody/be/comment/service/FeedCommentService.java
  be/src/main/resources/application-filter.yml
  be/src/test/java/com/foodymoody/be/acceptance/comment/CommentAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/comment/CommentSteps.java
  be/src/test/java/com/foodymoody/be/comment/util/CommentFixture.java
  be/src/test/java/com/foodymoody/be/comment/util/CommentMapperTest.java
  be/src/test/resources/application-filter.yml
  be/src/test/resources/data.sql
Labels: BE, feat

#172 [FE] 중간 머지
  fe/src/api/comment/comment.ts
  fe/src/api/feed/feed.ts
  fe/src/api/mood/mood.ts
  fe/src/assets/arrowUp.svg
  fe/src/components/common/Button/TextButton.tsx
  fe/src/components/common/commentItem/CommentBox.tsx
  fe/src/components/common/commentItem/CommentItem.tsx
  fe/src/components/common/dropdown/Dropdown.tsx
  fe/src/components/common/feedUserInfo/FeedUserInfo.tsx
  fe/src/components/common/icon/icons.ts
  fe/src/components/common/navibar/NaviBar.tsx
  fe/src/components/login/Login.tsx
  fe/src/components/register/Register.tsx
  fe/src/constants/endpoint.ts
  fe/src/constants/queryKey.ts
  fe/src/hooks/auth/useAuth.ts
  fe/src/hooks/useObserver.ts
  fe/src/pages/DetailFeedPage.tsx
  fe/src/pages/HomePage.tsx
  fe/src/pages/NewFeedPage.tsx
  fe/src/pages/ProfilePage.tsx
  fe/src/queries/auth.ts
  fe/src/queries/comment.ts
  fe/src/queries/feed.ts
  fe/src/queries/mood.ts
  fe/src/queries/profile.ts
  fe/src/types/comment.d.ts
  fe/src/types/error.d.ts
  fe/src/utils/formatTimeStamp.ts
Labels: FE, feat

#178 [FE] api -> service 폴더 구조 수정
  fe/src/components/common/commentItem/CommentItem.tsx
  fe/src/components/common/feedUserInfo/FeedUserInfo.tsx
  fe/src/components/common/navibar/NaviBar.tsx
  fe/src/components/login/Login.tsx
  fe/src/components/register/Register.tsx
  fe/src/hooks/auth/useAuth.ts
  fe/src/pages/DetailFeedPage.tsx
  fe/src/pages/NewFeedPage.tsx
  fe/src/service/axios/auth/comment/comment.ts
  fe/src/service/axios/auth/login.ts
  fe/src/service/axios/feed/feed.ts
  fe/src/service/axios/fetcher.ts
  fe/src/service/axios/mood/mood.ts
  fe/src/service/axios/profile/profile.ts
  fe/src/service/constants/endpoint.ts
  fe/src/service/constants/queryKey.ts
  fe/src/service/queries/auth.ts
  fe/src/service/queries/comment.ts
  fe/src/service/queries/feed.ts
  fe/src/service/queries/mood.ts
  fe/src/service/queries/profile.ts
Labels: FE, refactor, review

#188 [FE] dev-fe -> dev
  fe/src/components/common/commentItem/CommentBox.tsx
  fe/src/components/common/input/CommentInput.tsx
  fe/src/service/queries/mood.ts
  fe/src/service/queries/profile.ts
  fe/tsconfig.json
Labels: FE, fix

#189 [FE] Dev -> release
  fe/src/components/common/commentItem/CommentBox.tsx
  fe/src/components/common/input/CommentInput.tsx
  fe/src/service/queries/mood.ts
  fe/src/service/queries/profile.ts
  fe/tsconfig.json
Labels: FE, release

#191 [FE] dev-fe -> dev
  fe/src/components/common/button/Button.tsx
  fe/src/components/common/button/TextButton.tsx
Labels: FE, fix

#192 [FE] Dev -> release
  fe/src/components/common/button/Button.tsx
  fe/src/components/common/button/TextButton.tsx
Labels: FE, release

#194 [FE] 메인 피드 데이터 연동 및 무한 스크롤 추가
  fe/src/components/feedMain/FeedMainItem.tsx
  fe/src/pages/HomePage.tsx
  fe/src/service/queries/feed.ts
Labels: FE, feat, fix, review

#201 [BE] 댓글 리펙토링
  Dockerfile.fe
  be/src/main/java/com/foodymoody/be/comment/controller/CommentController.java
  be/src/main/java/com/foodymoody/be/comment/controller/ReplyController.java
  be/src/main/java/com/foodymoody/be/comment/controller/dto/CommentResponse.java
  be/src/main/java/com/foodymoody/be/comment/controller/dto/ReplyResponse.java
  be/src/main/java/com/foodymoody/be/comment/repository/CommentRepository.java
  be/src/main/java/com/foodymoody/be/comment/service/CommentService.java
  be/src/main/java/com/foodymoody/be/comment/service/FeedCommentService.java
  be/src/main/java/com/foodymoody/be/comment/service/ReplyService.java
  be/src/main/resources/application-filter.yml
  be/src/test/resources/application-db.yml
  be/src/test/resources/application-filter.yml
  be/src/test/resources/application.yml
Labels: BE, feat

#200 [FE] 더보기 버튼 오류 수정
  fe/src/components/common/carousel/Carousel.tsx
  fe/src/components/feedMain/FeedMainItem.tsx
  fe/src/hooks/useReadMore.ts
Labels: FE, feat, fix, review

#204 [FE] alert 연결
  fe/src/components/common/commentItem/CommentBox.tsx
  fe/src/components/common/commentItem/CommentItem.tsx
  fe/src/components/common/feedUserInfo/FeedUserInfo.tsx
  fe/src/components/common/input/Input.tsx
  fe/src/components/common/modal/Modal.tsx
  fe/src/components/feedMain/FeedMainItem.tsx
  fe/src/components/register/Register.tsx
  fe/src/constants/path.ts
  fe/src/hooks/useMenuItem.ts
  fe/src/pages/DetailFeedPage.tsx
  fe/src/pages/NewFeedPage.tsx
  fe/src/recoil/toast/useToast.ts
  fe/src/service/axios/auth/comment/reply.ts
  fe/src/service/constants/endpoint.ts
  fe/src/service/constants/queryKey.ts
  fe/src/service/queries/comment.ts
  fe/src/service/queries/reply.ts
  fe/src/types/auth.d.ts
  fe/src/types/comment.d.ts
  fe/tsconfig.json
Labels: FE, feat

#207 [FE] 프로필 페이지 프로필 영역 연동
  fe/src/components/profileUserInfo/ProfileUserInfo.tsx
  fe/src/pages/ProfilePage.tsx
  fe/src/service/queries/profile.ts
  fe/src/types/profile.d.ts
Labels: FE, feat, review

#210 [BE] 피드 좋아요 기능 구현
  be/src/main/java/com/foodymoody/be/feed/dto/response/FeedRegisterResponse.java
  be/src/main/java/com/foodymoody/be/feed/service/FeedService.java
  be/src/main/java/com/foodymoody/be/heart/controller/HeartController.java
  be/src/main/java/com/foodymoody/be/heart/domain/Heart.java
  be/src/main/java/com/foodymoody/be/heart/dto/request/HeartRequest.java
  be/src/main/java/com/foodymoody/be/heart/dto/request/HeartServiceRequest.java
  be/src/main/java/com/foodymoody/be/heart/dto/response/HeartResponse.java
  be/src/main/java/com/foodymoody/be/heart/repository/HeartRepository.java
  be/src/main/java/com/foodymoody/be/heart/service/HeartService.java
  be/src/main/java/com/foodymoody/be/heart/util/HeartMapper.java
  be/src/test/java/com/foodymoody/be/acceptance/heart/HeartAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/heart/HeartSteps.java
Labels: BE, feat, test

#216 [FE] Dev -> Release
  fe/src/components/common/badgeSelector/BadgeSelector.tsx
  fe/src/components/common/carousel/Carousel.tsx
  fe/src/components/common/commentItem/CommentBox.tsx
  fe/src/components/common/commentItem/CommentItem.tsx
  fe/src/components/common/feedUserInfo/FeedUserInfo.tsx
  fe/src/components/common/input/Input.tsx
  fe/src/components/common/modal/Modal.tsx
  fe/src/components/feedMain/FeedMainItem.tsx
  fe/src/components/profileUserInfo/ProfileUserInfo.tsx
  fe/src/components/register/Register.tsx
  fe/src/constants/path.ts
  fe/src/hooks/useMenuItem.ts
  fe/src/hooks/useReadMore.ts
  fe/src/pages/DetailFeedPage.tsx
  fe/src/pages/HomePage.tsx
  fe/src/pages/NewFeedPage.tsx
  fe/src/pages/ProfilePage.tsx
  fe/src/recoil/toast/useToast.ts
  fe/src/routes/router.tsx
  fe/src/service/axios/auth/comment/reply.ts
  fe/src/service/axios/mood/mood.ts
  fe/src/service/constants/endpoint.ts
  fe/src/service/constants/queryKey.ts
  fe/src/service/queries/comment.ts
  fe/src/service/queries/feed.ts
  fe/src/service/queries/mood.ts
  fe/src/service/queries/profile.ts
  fe/src/service/queries/reply.ts
  fe/src/types/auth.d.ts
  fe/src/types/comment.d.ts
  fe/src/types/feed.d.ts
  fe/src/types/profile.d.ts
  fe/tsconfig.json
Labels: FE, release

#217 [BE] 피드 Member 권한 수정
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/com/foodymoody/be/feed/controller/FeedController.java
  be/src/main/java/com/foodymoody/be/feed/dto/request/FeedServiceDeleteRequest.java
  be/src/main/java/com/foodymoody/be/feed/service/FeedService.java
  be/src/main/java/com/foodymoody/be/feed/util/FeedMapper.java
Labels: BE, fix

#221 [FE] 피드 오류 수정 및 라우터 수정
  fe/src/pages/NewFeedPage.tsx
  fe/src/routes/router.tsx
  fe/src/service/queries/feed.ts
  fe/src/types/error.d.ts
Labels: FE, fix, review

#222 dev-fe -> dev
  fe/src/pages/NewFeedPage.tsx
  fe/src/routes/router.tsx
  fe/src/service/queries/feed.ts
  fe/src/types/error.d.ts
Labels: FE, review

#227 [BE] 좋아요 등록, 취소 기능 구현 후 피드에 적용
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/com/foodymoody/be/feed/domain/Feed.java
  be/src/main/java/com/foodymoody/be/feed/service/FeedService.java
  be/src/main/java/com/foodymoody/be/heart/controller/HeartController.java
  be/src/main/java/com/foodymoody/be/heart/dto/response/HeartResponse.java
  be/src/main/java/com/foodymoody/be/heart/service/HeartService.java
  be/src/main/java/com/foodymoody/be/heart/util/HeartMapper.java
  be/src/main/java/com/foodymoody/be/member/domain/Member.java
  be/src/test/java/com/foodymoody/be/acceptance/heart/HeartAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/heart/HeartSteps.java
Labels: BE, feat, test

#233 [FE] 메인 피드 로딩 스켈레톤 추가
  fe/package-lock.json
  fe/package.json
  fe/src/components/common/skeleton/DeferredComponent.tsx
  fe/src/components/common/skeleton/FeedSkeleton.tsx
  fe/src/components/feedMain/FeedMainList.tsx
  fe/src/pages/HomePage.tsx
  fe/src/service/queries/feed.ts
  fe/src/styles/designSystem.ts
Labels: FE, feat

#234 [FE] dev-fe -> dev
  fe/package-lock.json
  fe/package.json
  fe/src/components/common/commentItem/CommentBox.tsx
  fe/src/components/common/commentItem/CommentItem.tsx
  fe/src/components/common/dim/Dim.tsx
  fe/src/components/common/feedAction/FeedAction.tsx
  fe/src/components/common/feedUserInfo/FeedUserInfo.tsx
  fe/src/components/common/loading/spinner.tsx
  fe/src/components/common/modal/Modal.tsx
  fe/src/components/common/skeleton/DeferredComponent.tsx
  fe/src/components/common/skeleton/FeedSkeleton.tsx
  fe/src/components/feedMain/FeedMainItem.tsx
  fe/src/components/feedMain/FeedMainList.tsx
  fe/src/components/register/Register.tsx
  fe/src/pages/DetailFeedPage.tsx
  fe/src/pages/HomePage.tsx
  fe/src/service/axios/fetcher.ts
  fe/src/service/axios/like/like.ts
  fe/src/service/constants/endpoint.ts
  fe/src/service/queries/auth.ts
  fe/src/service/queries/feed.ts
  fe/src/service/queries/like.ts
  fe/src/service/queries/reply.ts
  fe/src/styles/designSystem.ts
  fe/src/types/like.d.ts
Labels: FE, release

#235 [FE] Dev -> release
  fe/package-lock.json
  fe/package.json
  fe/src/components/common/commentItem/CommentBox.tsx
  fe/src/components/common/commentItem/CommentItem.tsx
  fe/src/components/common/dim/Dim.tsx
  fe/src/components/common/feedAction/FeedAction.tsx
  fe/src/components/common/feedUserInfo/FeedUserInfo.tsx
  fe/src/components/common/loading/spinner.tsx
  fe/src/components/common/modal/Modal.tsx
  fe/src/components/common/skeleton/DeferredComponent.tsx
  fe/src/components/common/skeleton/FeedSkeleton.tsx
  fe/src/components/feedMain/FeedMainItem.tsx
  fe/src/components/feedMain/FeedMainList.tsx
  fe/src/components/register/Register.tsx
  fe/src/pages/DetailFeedPage.tsx
  fe/src/pages/HomePage.tsx
  fe/src/service/axios/fetcher.ts
  fe/src/service/axios/like/like.ts
  fe/src/service/constants/endpoint.ts
  fe/src/service/queries/auth.ts
  fe/src/service/queries/feed.ts
  fe/src/service/queries/like.ts
  fe/src/service/queries/reply.ts
  fe/src/styles/designSystem.ts
  fe/src/types/like.d.ts
Labels: FE, release
