Repository foody-moody/foodymoody, pull requests merged in 2024-03, with the labels that each got.

#560 [BE] 피드 컬렉션 오류 수정
  be/src/main/java/com/foodymoody/be/common/exception/ErrorMessage.java
  be/src/main/java/com/foodymoody/be/common/exception/FeedCollectionLikeIsAlreadyExistException.java
  be/src/main/java/com/foodymoody/be/feed/application/FeedMapper.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/usecase/FeedCollectionMapper.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/usecase/FeedCollectionReadUseCase.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedCollectionDetail.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedSummaryResponse.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/StoreSummaryResponse.java
  be/src/main/java/com/foodymoody/be/feed_collection_like/application/service/FeedCollectionLikeReadService.java
  be/src/main/java/com/foodymoody/be/feed_collection_like/application/service/FeedCollectionLikeWriteService.java
  be/src/main/java/com/foodymoody/be/feed_collection_like/domain/FeedCollectionLikeRepository.java
  be/src/main/java/com/foodymoody/be/feed_collection_like/infra/persistence/FeedCollectionLikeRepositoryImpl.java
  be/src/main/java/com/foodymoody/be/feed_collection_like/infra/persistence/jpa/FeedCollectionLikeJpaRepository.java
Labels: BE, fix

#561 [BE] 피드 컬렉션 오류 수정
  be/src/main/java/com/foodymoody/be/common/exception/ErrorMessage.java
  be/src/main/java/com/foodymoody/be/common/exception/FeedCollectionLikeIsAlreadyExistException.java
  be/src/main/java/com/foodymoody/be/feed/application/FeedMapper.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/usecase/FeedCollectionMapper.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/usecase/FeedCollectionReadUseCase.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedCollectionDetail.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedSummaryResponse.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/StoreSummaryResponse.java
  be/src/main/java/com/foodymoody/be/feed_collection_like/application/service/FeedCollectionLikeReadService.java
  be/src/main/java/com/foodymoody/be/feed_collection_like/application/service/FeedCollectionLikeWriteService.java
  be/src/main/java/com/foodymoody/be/feed_collection_like/domain/FeedCollectionLikeRepository.java
  be/src/main/java/com/foodymoody/be/feed_collection_like/infra/persistence/FeedCollectionLikeRepositoryImpl.java
  be/src/main/java/com/foodymoody/be/feed_collection_like/infra/persistence/jpa/FeedCollectionLikeJpaRepository.java
Labels: BE, fix

#562 [BE] 피드 컬렉션 기본 썸네일url 변경
  be/src/main/java/com/foodymoody/be/common/exception/ErrorMessage.java
  be/src/main/java/com/foodymoody/be/common/exception/FeedCollectionLikeIsAlreadyExistException.java
  be/src/main/java/com/foodymoody/be/feed/application/FeedMapper.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/usecase/FeedCollectionMapper.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/usecase/FeedCollectionReadUseCase.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedCollectionDetail.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedSummaryResponse.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/StoreSummaryResponse.java
  be/src/main/java/com/foodymoody/be/feed_collection_like/application/service/FeedCollectionLikeReadService.java
  be/src/main/java/com/foodymoody/be/feed_collection_like/application/service/FeedCollectionLikeWriteService.java
  be/src/main/java/com/foodymoody/be/feed_collection_like/domain/FeedCollectionLikeRepository.java
  be/src/main/java/com/foodymoody/be/feed_collection_like/infra/persistence/FeedCollectionLikeRepositoryImpl.java
  be/src/main/java/com/foodymoody/be/feed_collection_like/infra/persistence/jpa/FeedCollectionLikeJpaRepository.java
Labels: BE, fix

#564 refactor: 피드 컬렉션 좋아요 취소 및 대댓글 좋아요 취소 API 리펙토링
  be/src/main/java/com/foodymoody/be/feed_collection_like/application/service/FeedCollectionLikeWriteService.java
  be/src/main/java/com/foodymoody/be/feed_collection_like/application/usecase/FeedCollectionLikeWriteUseCase.java
  be/src/main/java/com/foodymoody/be/feed_collection_like/domain/FeedCollectionLikeRepository.java
  be/src/main/java/com/foodymoody/be/feed_collection_like/infra/persistence/FeedCollectionLikeRepositoryImpl.java
  be/src/main/java/com/foodymoody/be/feed_collection_like/infra/persistence/jpa/FeedCollectionLikeJpaRepository.java
  be/src/main/java/com/foodymoody/be/feed_collection_like/presentation/FeedCollectionLikeWriteController.java
  be/src/main/java/com/foodymoody/be/feed_collection_reply_like/application/service/FeedCollectionReplyLikeWriteService.java
  be/src/main/java/com/foodymoody/be/feed_collection_reply_like/application/usecase/FeedCollectionReplyLikeWriteUseCase.java
  be/src/main/java/com/foodymoody/be/feed_collection_reply_like/domain/FeedCollectionReplyLikeRepository.java
  be/src/main/java/com/foodymoody/be/feed_collection_reply_like/infra/persistence/FeedCollectionReplyLikeRepositoryImpl.java
  be/src/main/java/com/foodymoody/be/feed_collection_reply_like/infra/persistence/jpa/FeedCollectionReplyLikeJpaRepository.java
  be/src/main/java/com/foodymoody/be/feed_collection_reply_like/presentation/FeedCollectionReplyLikeWriteController.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection_like/FeedCollectionLikeAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection_like/FeedCollectionLikeSteps.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection_reply_like/FeedCollectionReplyLikeAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection_reply_like/FeedCollectionReplyLikeSteps.java
Labels: BE, refactor

#565 dev be -> dev로 머지
  be/src/main/java/com/foodymoody/be/feed_collection_like/application/service/FeedCollectionLikeWriteService.java
  be/src/main/java/com/foodymoody/be/feed_collection_like/application/usecase/FeedCollectionLikeWriteUseCase.java
  be/src/main/java/com/foodymoody/be/feed_collection_like/domain/FeedCollectionLikeRepository.java
  be/src/main/java/com/foodymoody/be/feed_collection_like/infra/persistence/FeedCollectionLikeRepositoryImpl.java
  be/src/main/java/com/foodymoody/be/feed_collection_like/infra/persistence/jpa/FeedCollectionLikeJpaRepository.java
  be/src/main/java/com/foodymoody/be/feed_collection_like/presentation/FeedCollectionLikeWriteController.java
  be/src/main/java/com/foodymoody/be/feed_collection_reply_like/application/service/FeedCollectionReplyLikeWriteService.java
  be/src/main/java/com/foodymoody/be/feed_collection_reply_like/application/usecase/FeedCollectionReplyLikeWriteUseCase.java
  be/src/main/java/com/foodymoody/be/feed_collection_reply_like/domain/FeedCollectionReplyLikeRepository.java
  be/src/main/java/com/foodymoody/be/feed_collection_reply_like/infra/persistence/FeedCollectionReplyLikeRepositoryImpl.java
  be/src/main/java/com/foodymoody/be/feed_collection_reply_like/infra/persistence/jpa/FeedCollectionReplyLikeJpaRepository.java
  be/src/main/java/com/foodymoody/be/feed_collection_reply_like/presentation/FeedCollectionReplyLikeWriteController.java
  be/src/main/java/com/foodymoody/be/member/application/dto/response/MemberProfileImageResponse.java
  be/src/main/java/com/foodymoody/be/member/application/dto/response/TasteMoodResponse.java
  be/src/main/java/com/foodymoody/be/member/application/service/MemberReadService.java
  be/src/main/java/com/foodymoody/be/member/application/service/TasteMoodReadService.java
  be/src/main/java/com/foodymoody/be/member/domain/Member.java
  be/src/main/java/com/foodymoody/be/member/domain/MemberMapper.java
  be/src/main/java/com/foodymoody/be/member/domain/MemberRepository.java
  be/src/main/java/com/foodymoody/be/member/domain/MyFollowers.java
  be/src/main/java/com/foodymoody/be/member/domain/MyFollowings.java
  be/src/main/java/com/foodymoody/be/member/infra/persistence/MemberRepositoryImpl.java
  be/src/main/java/com/foodymoody/be/member/infra/persistence/jpa/MemberJpaRepository.java
  be/src/main/java/com/foodymoody/be/member/infra/persistence/jpa/MemberQueryDslRepository.java
  be/src/main/java/com/foodymoody/be/member/infra/persistence/jpa/MemberQueryDslRepositoryImpl.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection_like/FeedCollectionLikeAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection_like/FeedCollectionLikeSteps.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection_reply_like/FeedCollectionReplyLikeAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection_reply_like/FeedCollectionReplyLikeSteps.java
  be/src/test/java/com/foodymoody/be/member/util/MemberFixture.java
Labels: BE, refactor

#566 [BE] dev -> release
  be/src/main/java/com/foodymoody/be/feed_collection_like/application/service/FeedCollectionLikeWriteService.java
  be/src/main/java/com/foodymoody/be/feed_collection_like/application/usecase/FeedCollectionLikeWriteUseCase.java
  be/src/main/java/com/foodymoody/be/feed_collection_like/domain/FeedCollectionLikeRepository.java
  be/src/main/java/com/foodymoody/be/feed_collection_like/infra/persistence/FeedCollectionLikeRepositoryImpl.java
  be/src/main/java/com/foodymoody/be/feed_collection_like/infra/persistence/jpa/FeedCollectionLikeJpaRepository.java
  be/src/main/java/com/foodymoody/be/feed_collection_like/presentation/FeedCollectionLikeWriteController.java
  be/src/main/java/com/foodymoody/be/feed_collection_reply_like/application/service/FeedCollectionReplyLikeWriteService.java
  be/src/main/java/com/foodymoody/be/feed_collection_reply_like/application/usecase/FeedCollectionReplyLikeWriteUseCase.java
  be/src/main/java/com/foodymoody/be/feed_collection_reply_like/domain/FeedCollectionReplyLikeRepository.java
  be/src/main/java/com/foodymoody/be/feed_collection_reply_like/infra/persistence/FeedCollectionReplyLikeRepositoryImpl.java
  be/src/main/java/com/foodymoody/be/feed_collection_reply_like/infra/persistence/jpa/FeedCollectionReplyLikeJpaRepository.java
  be/src/main/java/com/foodymoody/be/feed_collection_reply_like/presentation/FeedCollectionReplyLikeWriteController.java
  be/src/main/java/com/foodymoody/be/member/application/dto/response/MemberProfileImageResponse.java
  be/src/main/java/com/foodymoody/be/member/application/dto/response/TasteMoodResponse.java
  be/src/main/java/com/foodymoody/be/member/application/service/MemberReadService.java
  be/src/main/java/com/foodymoody/be/member/application/service/TasteMoodReadService.java
  be/src/main/java/com/foodymoody/be/member/domain/Member.java
  be/src/main/java/com/foodymoody/be/member/domain/MemberMapper.java
  be/src/main/java/com/foodymoody/be/member/domain/MemberRepository.java
  be/src/main/java/com/foodymoody/be/member/domain/MyFollowers.java
  be/src/main/java/com/foodymoody/be/member/domain/MyFollowings.java
  be/src/main/java/com/foodymoody/be/member/infra/persistence/MemberRepositoryImpl.java
  be/src/main/java/com/foodymoody/be/member/infra/persistence/jpa/MemberJpaRepository.java
  be/src/main/java/com/foodymoody/be/member/infra/persistence/jpa/MemberQueryDslRepository.java
  be/src/main/java/com/foodymoody/be/member/infra/persistence/jpa/MemberQueryDslRepositoryImpl.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection_like/FeedCollectionLikeAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection_like/FeedCollectionLikeSteps.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection_reply_like/FeedCollectionReplyLikeAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection_reply_like/FeedCollectionReplyLikeSteps.java
  be/src/test/java/com/foodymoody/be/member/util/MemberFixture.java
Labels: BE, release

#568 [FE] dev-fe -> dev
  fe/package-lock.json
  fe/package.json
  fe/src/assets/bin.svg
  fe/src/assets/googleIcon.svg
  fe/src/components/collection/CollectionContainer.tsx
  fe/src/components/common/commentItem/ReplyItem.tsx
  fe/src/components/common/feedUserInfo/FeedUserInfo.tsx
  fe/src/components/common/icon/NotiIcon.tsx
  fe/src/components/common/icon/icons.ts
  fe/src/components/common/modal/CollectionAlert.tsx
  fe/src/components/common/modal/CollectionModal.tsx
  fe/src/components/common/modal/Modal.tsx
  fe/src/components/common/oauthButton/OAuthButton.tsx
  fe/src/components/feedMain/FeedMainItem.tsx
  fe/src/components/notification/NotiList.tsx
  fe/src/components/sort/SelectSort.tsx
  fe/src/constants/path.ts
  fe/src/pages/CollectionDetailPage.tsx
  fe/src/pages/DetailFeedPage.tsx
  fe/src/pages/HomePage.tsx
  fe/src/pages/LoginPage.tsx
  fe/src/pages/NotiPage.tsx
  fe/src/pages/OAuthRedirectPage.tsx
  fe/src/pages/ProfilePage.tsx
  fe/src/routes/router.tsx
  fe/src/service/axios/collection/collection.ts
  fe/src/service/constants/queryKey.ts
  fe/src/service/queries/auth.ts
  fe/src/service/queries/collection.ts
  fe/src/service/queries/follow.ts
  fe/src/service/queries/notification.ts
  fe/src/service/queries/reply.ts
  fe/src/types/modal.d.ts
  fe/vite.config.ts
Labels: FE

#569 [FE] dev -> release
  fe/package-lock.json
  fe/package.json
  fe/src/assets/bin.svg
  fe/src/assets/googleIcon.svg
  fe/src/components/collection/CollectionContainer.tsx
  fe/src/components/common/commentItem/ReplyItem.tsx
  fe/src/components/common/feedUserInfo/FeedUserInfo.tsx
  fe/src/components/common/icon/NotiIcon.tsx
  fe/src/components/common/icon/icons.ts
  fe/src/components/common/modal/CollectionAlert.tsx
  fe/src/components/common/modal/CollectionModal.tsx
  fe/src/components/common/modal/Modal.tsx
  fe/src/components/common/oauthButton/OAuthButton.tsx
  fe/src/components/feedMain/FeedMainItem.tsx
  fe/src/components/notification/NotiList.tsx
  fe/src/components/sort/SelectSort.tsx
  fe/src/constants/path.ts
  fe/src/pages/CollectionDetailPage.tsx
  fe/src/pages/DetailFeedPage.tsx
  fe/src/pages/HomePage.tsx
  fe/src/pages/LoginPage.tsx
  fe/src/pages/NotiPage.tsx
  fe/src/pages/OAuthRedirectPage.tsx
  fe/src/pages/ProfilePage.tsx
  fe/src/routes/router.tsx
  fe/src/service/axios/collection/collection.ts
  fe/src/service/constants/queryKey.ts
  fe/src/service/queries/auth.ts
  fe/src/service/queries/collection.ts
  fe/src/service/queries/follow.ts
  fe/src/service/queries/notification.ts
  fe/src/service/queries/reply.ts
  fe/src/types/modal.d.ts
  fe/vite.config.ts
Labels: FE

#574 [BE] 피드 컬렉션 좋아요 중복 문제 해결
  .github/workflows/coveralls-report.yml
  be/src/main/java/com/foodymoody/be/common/exception/ErrorMessage.java
  be/src/main/java/com/foodymoody/be/common/exception/FeedCollectionLikeIsNotExistException.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/service/FeedCollectionWriteService.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/usecase/FeedCollectionWriteUseCase.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedCollection.java
  be/src/main/java/com/foodymoody/be/feed_collection_like/application/service/FeedCollectionLikeWriteService.java
Labels: BE, fix

#575 [BE] 피드 컬렉션 좋아요 중복 문제 해결
  .github/workflows/coveralls-report.yml
  be/src/main/java/com/foodymoody/be/common/exception/ErrorMessage.java
  be/src/main/java/com/foodymoody/be/common/exception/FeedCollectionLikeIsNotExistException.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/service/FeedCollectionWriteService.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/usecase/FeedCollectionWriteUseCase.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedCollection.java
  be/src/main/java/com/foodymoody/be/feed_collection_like/application/service/FeedCollectionLikeWriteService.java
Labels: BE, fix

#581 [FE] 폰트 최적화 관련 작업
  fe/index.html
  fe/src/assets/font/IBMPlexSansKR-Medium.woff
  fe/src/assets/font/IBMPlexSansKR-Regular.woff
  fe/src/assets/font/IBMPlexSansKR-SemiBold.woff
  fe/src/styles/font.ts
  fe/src/styles/globalStyles.ts
Labels: FE, review

#583 [FE] Dev -> release
  fe/index.html
  fe/src/assets/font/IBMPlexSansKR-Medium.woff
  fe/src/assets/font/IBMPlexSansKR-Regular.woff
  fe/src/assets/font/IBMPlexSansKR-SemiBold.woff
  fe/src/components/collection/CollectionContainer.tsx
  fe/src/components/collection/detail/HeroImage.tsx
  fe/src/components/commentInput/CommentInput.tsx
  fe/src/components/common/input/Input.tsx
  fe/src/components/common/modal/CollectionAlert.tsx
  fe/src/components/common/modal/CollectionModal.tsx
  fe/src/components/common/modal/Modal.tsx
  fe/src/components/common/oauthButton/OAuthButton.tsx
  fe/src/components/feedMain/FeedMainList.tsx
  fe/src/components/profileEdit/ProfileEditForm.tsx
  fe/src/components/profileUserInfo/ProfileUserInfo.tsx
  fe/src/constants/path.ts
  fe/src/pages/CollectionDetailPage.tsx
  fe/src/pages/CollectionPage.tsx
  fe/src/pages/DetailFeedPage.tsx
  fe/src/pages/HomePage.tsx
  fe/src/pages/NotiPage.tsx
  fe/src/pages/OAuthRedirectPage.tsx
  fe/src/pages/ProfilePage.tsx
  fe/src/routes/router.tsx
  fe/src/service/axios/auth/login.ts
  fe/src/service/axios/collection/collection.ts
  fe/src/service/axios/fetcher.ts
  fe/src/service/axios/like/like.ts
  fe/src/service/constants/endpoint.ts
  fe/src/service/constants/queryKey.ts
  fe/src/service/queries/auth.ts
  fe/src/service/queries/collection.ts
  fe/src/service/queries/like.ts
  fe/src/styles/font.ts
  fe/src/styles/globalStyles.ts
  fe/src/types/profile.d.ts
Labels: FE, release

#584 [FE] 빌드오류 수정
  fe/src/components/common/oauthButton/OAuthButton.tsx
  fe/src/hooks/useProfileEditForm/usePofileEditForm.ts
  fe/src/service/axios/fetcher.ts
Labels: FE

#585 [FE] 빌드오류 수정 (#584)
  fe/src/components/common/oauthButton/OAuthButton.tsx
  fe/src/hooks/useProfileEditForm/usePofileEditForm.ts
  fe/src/service/axios/fetcher.ts
Labels: FE

#586 [FE] Dev -> release
  fe/src/components/common/oauthButton/OAuthButton.tsx
  fe/src/hooks/useProfileEditForm/usePofileEditForm.ts
  fe/src/service/axios/fetcher.ts
Labels: FE

#589 [FE] dev -> release
  fe/src/components/feedMain/FeedMainList.tsx
Labels: FE, release

#590 [FE] 핫픽스
  fe/src/service/axios/fetcher.ts
Labels: FE

#591 [FE] 핫픽스 (#590)
  fe/src/service/axios/fetcher.ts
Labels: FE

#592 [FE] dev->release
  fe/src/service/axios/fetcher.ts
Labels: FE, release

#594 [FE] devfe -> dev
  fe/src/components/common/oauthButton/OAuthButton.tsx
  fe/src/service/queries/auth.ts
Labels: FE

#595 [FE] Dev -> release
  fe/src/components/common/oauthButton/OAuthButton.tsx
  fe/src/service/queries/auth.ts
Labels: FE, release

#596 [FE] 핫픽스
  fe/src/service/axios/fetcher.ts
Labels: FE

#598 [FE] Dev -> release
  fe/src/service/axios/fetcher.ts
Labels: FE, release

#600 [FE] dev-fe -> dev
  fe/src/service/axios/fetcher.ts
Labels: FE, release

#601 [FE] Dev -> release
  fe/src/service/axios/fetcher.ts
Labels: FE, release

#604 [FE] 구글 콘솔 등록 태그 추가
  fe/index.html
Labels: FE

#605 [FE] dev fe->dev
  fe/index.html
Labels: FE, feat

#606 [FE] Dev -> release
  fe/index.html
Labels: FE, release

#608 [FE] dev fe -> dev
  fe/index.html
  fe/public/robots.txt
  fe/src/components/collection/ListItem.tsx
  fe/src/components/common/carousel/Carousel.tsx
  fe/src/components/common/feedUserInfo/FeedUserInfo.tsx
  fe/src/components/common/feedUserInfo/Share.tsx
  fe/src/components/common/navibar/NaviBar.tsx
  fe/src/components/feedMain/FeedMainItem.tsx
  fe/src/pages/CollectionDetailPage.tsx
  fe/src/pages/DetailFeedPage.tsx
Labels: FE, feat

#609 [FE] Dev -> release
  fe/index.html
  fe/public/robots.txt
  fe/src/components/collection/ListItem.tsx
  fe/src/components/common/carousel/Carousel.tsx
  fe/src/components/common/feedUserInfo/FeedUserInfo.tsx
  fe/src/components/common/feedUserInfo/Share.tsx
  fe/src/components/common/navibar/NaviBar.tsx
  fe/src/components/feedMain/FeedMainItem.tsx
  fe/src/pages/CollectionDetailPage.tsx
  fe/src/pages/DetailFeedPage.tsx
Labels: FE, release

#613 [FE] og img 경로 수정
  fe/src/pages/HomePage.tsx
Labels: FE, feat

#614 [FE] Dev fe -> dev
  fe/package-lock.json
  fe/package.json
  fe/src/App.tsx
  fe/src/components/common/helmet/Helmet.tsx
  fe/src/pages/DetailFeedPage.tsx
  fe/src/pages/HomePage.tsx
Labels: FE, feat

#615 [FE] Dev -> release
  fe/package-lock.json
  fe/package.json
  fe/src/App.tsx
  fe/src/components/common/helmet/Helmet.tsx
  fe/src/pages/DetailFeedPage.tsx
  fe/src/pages/HomePage.tsx
Labels: FE, feat

#616 [FE] 메타태그 수정
  fe/index.html
  fe/src/pages/DetailFeedPage.tsx
  fe/src/pages/HomePage.tsx
Labels: FE, feat

#617 [FE] dev fe-> dev
  fe/index.html
  fe/src/pages/DetailFeedPage.tsx
  fe/src/pages/HomePage.tsx
Labels: FE, feat

#618 [FE] Dev -> release
  fe/index.html
  fe/src/pages/DetailFeedPage.tsx
  fe/src/pages/HomePage.tsx
Labels: FE, release

#620 [BE] 피드 컬렌션 상세 조회에 팔로우 정보 추가 구현
  be/src/main/java/com/foodymoody/be/feed_collection/application/usecase/FeedCollectionReadUseCase.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedCollectionDetail.java
  be/src/main/java/com/foodymoody/be/member/application/service/FollowReadService.java
  be/src/main/java/com/foodymoody/be/member/domain/Member.java
  be/src/main/java/com/foodymoody/be/member/domain/MyFollowings.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection/FeedCollectionAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/member/MemberSteps.java
Labels: BE, feat

#621 [BE] 피드 컬렌션 상세 조회에 팔로우 정보 추가 구현 (#620)
  be/src/main/java/com/foodymoody/be/feed_collection/application/usecase/FeedCollectionReadUseCase.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedCollectionDetail.java
  be/src/main/java/com/foodymoody/be/member/application/service/FollowReadService.java
  be/src/main/java/com/foodymoody/be/member/domain/Member.java
  be/src/main/java/com/foodymoody/be/member/domain/MyFollowings.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection/FeedCollectionAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/member/MemberSteps.java
Labels: BE, feat

#622 [BE] 피드 컬렌션 상세 조회에 팔로우 정보 추가 구현 (#620)
  be/src/main/java/com/foodymoody/be/feed_collection/application/usecase/FeedCollectionReadUseCase.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedCollectionDetail.java
  be/src/main/java/com/foodymoody/be/member/application/service/FollowReadService.java
  be/src/main/java/com/foodymoody/be/member/domain/Member.java
  be/src/main/java/com/foodymoody/be/member/domain/MyFollowings.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection/FeedCollectionAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/member/MemberSteps.java
Labels: BE, feat

#624 [FE] 알림 설정 리팩토링
  fe/src/components/common/carousel/Carousel.tsx
  fe/src/components/feedMain/FeedMainList.tsx
  fe/src/pages/NotiSettingPage.tsx
  fe/src/service/axios/collection/collection.ts
  fe/src/utils/debounce.ts
Labels: FE, refactor
