Repository foody-moody/foodymoody, pull requests merged in 2024-02, with the labels that each got.

#491 test: 테스트 주석
  be/src/test/java/com/foodymoody/be/acceptance/store_like/StoreLikeAcceptanceTest.java
Labels: fix

#493 test: 오류 테스트 코드 주석
  be/src/test/java/com/foodymoody/be/acceptance/store_like/StoreLikeAcceptanceTest.java
Labels: BE, fix

#499 [BE] 컬렉션 조회 기능 개선
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/com/foodymoody/be/common/exception/ErrorMessage.java
  be/src/main/java/com/foodymoody/be/common/exception/FeedCollectionNotFoundException.java
  be/src/main/java/com/foodymoody/be/common/exception/FeedReplyNotFoundException.java
  be/src/main/java/com/foodymoody/be/common/exception/GlobalExceptionHandler.java
  be/src/main/java/com/foodymoody/be/common/exception/ReplyNotExistsException.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/service/FeedCollectionMoodReadService.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/service/FeedCollectionReadService.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/service/FeedCollectionWriteService.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/usecase/FeedCollectionMoodReadUseCase.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/usecase/FeedCollectionReadUseCase.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/usecase/FeedCollectionWriteUseCase.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/usecase/dto/FeedCollectionCreateRequest.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedCollection.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedCollectionMoodRepository.java
  be/src/main/java/com/foodymoody/be/feed_collection/infra/persistence/FeedCollectionDaoImpl.java
  be/src/main/java/com/foodymoody/be/feed_collection/infra/persistence/FeedCollectionMoodRepositoryImpl.java
  be/src/main/java/com/foodymoody/be/feed_collection/infra/persistence/jpa/FeedCollectionJpaRepository.java
  be/src/main/java/com/foodymoody/be/feed_collection/presentation/FeedCollectionMoodReadController.java
  be/src/main/java/com/foodymoody/be/feed_collection/presentation/FeedCollectionWriteController.java
  be/src/main/java/com/foodymoody/be/feed_comment/application/dto/data/UpdateFeedReplyData.java
  be/src/main/java/com/foodymoody/be/feed_comment/application/service/FeedReplyReadService.java
  be/src/main/java/com/foodymoody/be/feed_comment/application/service/FeedReplyWriteService.java
  be/src/main/java/com/foodymoody/be/feed_comment/domain/entity/FeedReply.java
  be/src/main/java/com/foodymoody/be/feed_comment/infra/persistence/FeedReplyRepositoryImpl.java
  be/src/main/java/com/foodymoody/be/feed_comment/infra/persistence/jpa/FeedReplyJpaRepository.java
  be/src/main/java/com/foodymoody/be/feed_comment/persentation/FeedCommentWriteController.java
  be/src/main/java/com/foodymoody/be/feed_comment/persentation/FeedReplyReadController.java
  be/src/main/java/com/foodymoody/be/feed_comment/persentation/FeedReplyWriteController.java
  be/src/main/java/com/foodymoody/be/feed_comment/persentation/dto/EditFeedCommentRequest.java
  be/src/main/java/com/foodymoody/be/feed_comment/persentation/dto/RegisterFeedCommentRequest.java
  be/src/main/java/com/foodymoody/be/feed_comment/persentation/dto/RegisterFeedReplyRequest.java
  be/src/main/java/com/foodymoody/be/feed_comment/persentation/dto/UpdateFeedReplyRequest.java
  be/src/main/java/com/foodymoody/be/feed_comment/persentation/translator/FeedCommentTranslator.java
  be/src/main/java/com/foodymoody/be/feed_comment/persentation/translator/FeedReplyTranslator.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/dto/MemberFollowedNotificationDetails.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection/FeedCollectionAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection/FeedCollectionSteps.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection_mood/FeedCollectionMoodAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_reply/FeedReplyAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_reply/FeedReplySteps.java
  be/src/test/java/com/foodymoody/be/acceptance/notification/NotificationAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/feed_comment/application/service/FeedFeedReplyReadServiceTest.java
  be/src/test/java/com/foodymoody/be/feed_comment/domain/entity/FeedReplyTest.java
Labels: BE, feat, refactor

#500 [BE] 컬렉션 개선
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/com/foodymoody/be/common/exception/ErrorMessage.java
  be/src/main/java/com/foodymoody/be/common/exception/FeedCollectionNotFoundException.java
  be/src/main/java/com/foodymoody/be/common/exception/FeedReplyNotFoundException.java
  be/src/main/java/com/foodymoody/be/common/exception/GlobalExceptionHandler.java
  be/src/main/java/com/foodymoody/be/common/exception/ReplyNotExistsException.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/service/FeedCollectionMoodReadService.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/service/FeedCollectionReadService.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/service/FeedCollectionWriteService.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/usecase/FeedCollectionMoodReadUseCase.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/usecase/FeedCollectionReadUseCase.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/usecase/FeedCollectionWriteUseCase.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/usecase/dto/FeedCollectionCreateRequest.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedCollection.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedCollectionMoodRepository.java
  be/src/main/java/com/foodymoody/be/feed_collection/infra/persistence/FeedCollectionDaoImpl.java
  be/src/main/java/com/foodymoody/be/feed_collection/infra/persistence/FeedCollectionMoodRepositoryImpl.java
  be/src/main/java/com/foodymoody/be/feed_collection/infra/persistence/jpa/FeedCollectionJpaRepository.java
  be/src/main/java/com/foodymoody/be/feed_collection/presentation/FeedCollectionMoodReadController.java
  be/src/main/java/com/foodymoody/be/feed_collection/presentation/FeedCollectionWriteController.java
  be/src/main/java/com/foodymoody/be/feed_comment/application/dto/data/UpdateFeedReplyData.java
  be/src/main/java/com/foodymoody/be/feed_comment/application/service/FeedReplyReadService.java
  be/src/main/java/com/foodymoody/be/feed_comment/application/service/FeedReplyWriteService.java
  be/src/main/java/com/foodymoody/be/feed_comment/domain/entity/FeedReply.java
  be/src/main/java/com/foodymoody/be/feed_comment/infra/persistence/FeedReplyRepositoryImpl.java
  be/src/main/java/com/foodymoody/be/feed_comment/infra/persistence/jpa/FeedReplyJpaRepository.java
  be/src/main/java/com/foodymoody/be/feed_comment/persentation/FeedCommentWriteController.java
  be/src/main/java/com/foodymoody/be/feed_comment/persentation/FeedReplyReadController.java
  be/src/main/java/com/foodymoody/be/feed_comment/persentation/FeedReplyWriteController.java
  be/src/main/java/com/foodymoody/be/feed_comment/persentation/dto/EditFeedCommentRequest.java
  be/src/main/java/com/foodymoody/be/feed_comment/persentation/dto/RegisterFeedCommentRequest.java
  be/src/main/java/com/foodymoody/be/feed_comment/persentation/dto/RegisterFeedReplyRequest.java
  be/src/main/java/com/foodymoody/be/feed_comment/persentation/dto/UpdateFeedReplyRequest.java
  be/src/main/java/com/foodymoody/be/feed_comment/persentation/translator/FeedCommentTranslator.java
  be/src/main/java/com/foodymoody/be/feed_comment/persentation/translator/FeedReplyTranslator.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/dto/MemberFollowedNotificationDetails.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection/FeedCollectionAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection/FeedCollectionSteps.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection_mood/FeedCollectionMoodAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_reply/FeedReplyAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_reply/FeedReplySteps.java
  be/src/test/java/com/foodymoody/be/acceptance/notification/NotificationAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/feed_comment/application/service/FeedFeedReplyReadServiceTest.java
  be/src/test/java/com/foodymoody/be/feed_comment/domain/entity/FeedReplyTest.java
Labels: BE, refactor

#501 [BE] 2월 8일
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/com/foodymoody/be/common/exception/ErrorMessage.java
  be/src/main/java/com/foodymoody/be/common/exception/FeedCollectionNotFoundException.java
  be/src/main/java/com/foodymoody/be/common/exception/FeedReplyNotFoundException.java
  be/src/main/java/com/foodymoody/be/common/exception/GlobalExceptionHandler.java
  be/src/main/java/com/foodymoody/be/common/exception/ReplyNotExistsException.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/service/FeedCollectionMoodReadService.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/service/FeedCollectionReadService.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/service/FeedCollectionWriteService.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/usecase/FeedCollectionMoodReadUseCase.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/usecase/FeedCollectionReadUseCase.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/usecase/FeedCollectionWriteUseCase.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/usecase/dto/FeedCollectionCreateRequest.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedCollection.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedCollectionMoodRepository.java
  be/src/main/java/com/foodymoody/be/feed_collection/infra/persistence/FeedCollectionDaoImpl.java
  be/src/main/java/com/foodymoody/be/feed_collection/infra/persistence/FeedCollectionMoodRepositoryImpl.java
  be/src/main/java/com/foodymoody/be/feed_collection/infra/persistence/jpa/FeedCollectionJpaRepository.java
  be/src/main/java/com/foodymoody/be/feed_collection/presentation/FeedCollectionMoodReadController.java
  be/src/main/java/com/foodymoody/be/feed_collection/presentation/FeedCollectionWriteController.java
  be/src/main/java/com/foodymoody/be/feed_comment/application/dto/data/UpdateFeedReplyData.java
  be/src/main/java/com/foodymoody/be/feed_comment/application/service/FeedReplyReadService.java
  be/src/main/java/com/foodymoody/be/feed_comment/application/service/FeedReplyWriteService.java
  be/src/main/java/com/foodymoody/be/feed_comment/domain/entity/FeedReply.java
  be/src/main/java/com/foodymoody/be/feed_comment/infra/persistence/FeedReplyRepositoryImpl.java
  be/src/main/java/com/foodymoody/be/feed_comment/infra/persistence/jpa/FeedReplyJpaRepository.java
  be/src/main/java/com/foodymoody/be/feed_comment/persentation/FeedCommentWriteController.java
  be/src/main/java/com/foodymoody/be/feed_comment/persentation/FeedReplyReadController.java
  be/src/main/java/com/foodymoody/be/feed_comment/persentation/FeedReplyWriteController.java
  be/src/main/java/com/foodymoody/be/feed_comment/persentation/dto/EditFeedCommentRequest.java
  be/src/main/java/com/foodymoody/be/feed_comment/persentation/dto/RegisterFeedCommentRequest.java
  be/src/main/java/com/foodymoody/be/feed_comment/persentation/dto/RegisterFeedReplyRequest.java
  be/src/main/java/com/foodymoody/be/feed_comment/persentation/dto/UpdateFeedReplyRequest.java
  be/src/main/java/com/foodymoody/be/feed_comment/persentation/translator/FeedCommentTranslator.java
  be/src/main/java/com/foodymoody/be/feed_comment/persentation/translator/FeedReplyTranslator.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/dto/MemberFollowedNotificationDetails.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection/FeedCollectionAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection/FeedCollectionSteps.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection_mood/FeedCollectionMoodAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_reply/FeedReplyAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_reply/FeedReplySteps.java
  be/src/test/java/com/foodymoody/be/acceptance/notification/NotificationAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/feed_comment/application/service/FeedFeedReplyReadServiceTest.java
  be/src/test/java/com/foodymoody/be/feed_comment/domain/entity/FeedReplyTest.java
Labels: BE, feat

#503 [BE] 피드 업데이트
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/com/foodymoody/be/feed/application/FeedMapper.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/CollectionReadFeedDetailsResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedImageMenuResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedImageResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedMemberResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedMenuResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedReadAllResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedReadResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedRegisterResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedStoreMoodResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedTasteMoodResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/StoreMoodResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/StoreResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/service/FeedReadService.java
  be/src/main/java/com/foodymoody/be/feed/application/usecase/FeedUseCase.java
  be/src/main/java/com/foodymoody/be/feed/application/usecase/dto/ImageIdNamePair.java
  be/src/main/java/com/foodymoody/be/feed/application/usecase/dto/MenuNameRatingPair.java
  be/src/main/java/com/foodymoody/be/feed/domain/entity/Feed.java
  be/src/main/java/com/foodymoody/be/feed/presentation/FeedController.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/usecase/FeedCollectionMapper.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/usecase/FeedCollectionReadUseCase.java
  be/src/main/java/com/foodymoody/be/feed_like/application/FeedLikeMapper.java
  be/src/main/java/com/foodymoody/be/feed_like/application/dto/response/FeedLikeResponse.java
  be/src/main/java/com/foodymoody/be/feed_like/application/service/FeedLikeService.java
  be/src/test/java/com/foodymoody/be/acceptance/member/MemberAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/feed/application/FeedMapperTest.java
Labels: BE, fix, refactor

#504 dev-be to dev
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/com/foodymoody/be/feed/application/FeedMapper.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/CollectionReadFeedDetailsResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedImageMenuResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedImageResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedMemberResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedMenuResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedReadAllResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedReadResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedRegisterResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedStoreMoodResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedTasteMoodResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/StoreMoodResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/StoreResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/service/FeedReadService.java
  be/src/main/java/com/foodymoody/be/feed/application/usecase/FeedUseCase.java
  be/src/main/java/com/foodymoody/be/feed/application/usecase/dto/ImageIdNamePair.java
  be/src/main/java/com/foodymoody/be/feed/application/usecase/dto/MenuNameRatingPair.java
  be/src/main/java/com/foodymoody/be/feed/domain/entity/Feed.java
  be/src/main/java/com/foodymoody/be/feed/presentation/FeedController.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/usecase/FeedCollectionMapper.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/usecase/FeedCollectionReadUseCase.java
  be/src/main/java/com/foodymoody/be/feed_like/application/FeedLikeMapper.java
  be/src/main/java/com/foodymoody/be/feed_like/application/dto/response/FeedLikeResponse.java
  be/src/main/java/com/foodymoody/be/feed_like/application/service/FeedLikeService.java
  be/src/test/java/com/foodymoody/be/acceptance/member/MemberAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/feed/application/FeedMapperTest.java
Labels: BE, release

#505 dev to release
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/com/foodymoody/be/feed/application/FeedMapper.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/CollectionReadFeedDetailsResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedImageMenuResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedImageResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedMemberResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedMenuResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedReadAllResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedReadResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedRegisterResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedStoreMoodResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedTasteMoodResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/StoreMoodResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/StoreResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/service/FeedReadService.java
  be/src/main/java/com/foodymoody/be/feed/application/usecase/FeedUseCase.java
  be/src/main/java/com/foodymoody/be/feed/application/usecase/dto/ImageIdNamePair.java
  be/src/main/java/com/foodymoody/be/feed/application/usecase/dto/MenuNameRatingPair.java
  be/src/main/java/com/foodymoody/be/feed/domain/entity/Feed.java
  be/src/main/java/com/foodymoody/be/feed/presentation/FeedController.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/usecase/FeedCollectionMapper.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/usecase/FeedCollectionReadUseCase.java
  be/src/main/java/com/foodymoody/be/feed_like/application/FeedLikeMapper.java
  be/src/main/java/com/foodymoody/be/feed_like/application/dto/response/FeedLikeResponse.java
  be/src/main/java/com/foodymoody/be/feed_like/application/service/FeedLikeService.java
  be/src/test/java/com/foodymoody/be/acceptance/member/MemberAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/feed/application/FeedMapperTest.java
Labels: BE, release

#511 [BE] 대댓글 조회시 삭제한 대댓글도 함께 조회되는 에러
  be/src/main/java/com/foodymoody/be/feed_collection_comment/infra/persistence/jpa/FeedCollectionCommentJpaRepository.java
  be/src/main/java/com/foodymoody/be/feed_collection_reply/infra/persistence/jpa/FeedCollectionReplyJpaRepository.java
  be/src/main/java/com/foodymoody/be/feed_comment/infra/persistence/jpa/FeedReplyJpaRepository.java
Labels: BE, fix

#498 [FE] 컬렉션 추가 기능
  fe/src/components/common/modal/CollectionModal.tsx
  fe/src/components/profileUserInfo/ProfileUserInfo.tsx
  fe/src/service/axios/collection/collection.ts
  fe/src/service/constants/queryKey.ts
  fe/src/service/queries/collection.ts
  fe/src/types/collection.d.ts
  fe/src/types/modal.d.ts
Labels: FE, feat

#518 docs: coveralls report 구현
  .github/workflows/coveralls-report.yml
Labels: BE, chore

#520 [FE] 팔로우시 데이터 갱신 버그수정
  fe/src/components/collection/GridItem.tsx
  fe/src/components/collection/ListItem.tsx
  fe/src/components/common/commentItem/CommentItem.tsx
  fe/src/components/common/feedUserInfo/FeedUserInfo.tsx
  fe/src/components/feedProfile/FeedProfleItem.tsx
  fe/src/components/follow/followButton/FollowListButton.tsx
  fe/src/components/follow/followList/FollowListRow.tsx
  fe/src/components/notification/NotiItem.tsx
  fe/src/service/queries/follow.ts
Labels: FE, fix

#522 [FE] dev -> release
  .github/workflows/coveralls-report.yml
  be/src/main/java/com/foodymoody/be/feed_collection_comment/infra/persistence/jpa/FeedCollectionCommentJpaRepository.java
  be/src/main/java/com/foodymoody/be/feed_collection_reply/infra/persistence/jpa/FeedCollectionReplyJpaRepository.java
  be/src/main/java/com/foodymoody/be/feed_comment/infra/persistence/jpa/FeedReplyJpaRepository.java
  be/src/main/resources/application-localdb.yml
  be/src/main/resources/static/docs/index.html
  be/src/test/java/com/foodymoody/be/store_like/application/StoreLikeCountWriteFacadeTest.java
  fe/src/components/collection/GridItem.tsx
  fe/src/components/collection/ListItem.tsx
  fe/src/components/common/commentItem/CommentItem.tsx
  fe/src/components/common/feedUserInfo/FeedUserInfo.tsx
  fe/src/components/feedProfile/FeedProfleItem.tsx
  fe/src/components/follow/followButton/FollowListButton.tsx
  fe/src/components/follow/followList/FollowListRow.tsx
  fe/src/components/notification/NotiItem.tsx
  fe/src/service/queries/follow.ts
Labels: FE, release

#523 [FE] 알림 페이지 수정 작업
  fe/src/components/notification/NotiItem.tsx
  fe/src/components/notification/NotiList.tsx
  fe/src/routes/router.tsx
  fe/src/service/constants/notificationTextMessage.ts
  fe/src/types/notification.d.ts
Labels: FE, refactor

#529 [FE] 버그픽스
  fe/src/components/collection/GridItem.tsx
  fe/src/components/collection/ListItem.tsx
  fe/src/components/collection/profile/Collection.tsx
  fe/src/components/common/feedUserInfo/FeedUserInfo.tsx
  fe/src/components/common/userImage/UserImageEdit.tsx
  fe/src/components/feedProfile/FeedPofileList.tsx
  fe/src/components/follow/followList/FollowList.tsx
  fe/src/components/profileEdit/ProfileEditForm.tsx
  fe/src/components/profileUserInfo/ProfileUserInfo.tsx
  fe/src/service/axios/feed/feed.ts
  fe/src/service/queries/feed.ts
  fe/src/types/collection.d.ts
Labels: FE, fix

#530 [FE]Dev fe->dev
  fe/src/components/collection/GridItem.tsx
  fe/src/components/collection/ListItem.tsx
  fe/src/components/collection/profile/Collection.tsx
  fe/src/components/common/feedUserInfo/FeedUserInfo.tsx
  fe/src/components/common/userImage/UserImageEdit.tsx
  fe/src/components/feedProfile/FeedPofileList.tsx
  fe/src/components/follow/followList/FollowList.tsx
  fe/src/components/notification/NotiItem.tsx
  fe/src/components/notification/NotiList.tsx
  fe/src/components/profileEdit/ProfileEditForm.tsx
  fe/src/components/profileUserInfo/ProfileUserInfo.tsx
  fe/src/routes/router.tsx
  fe/src/service/axios/feed/feed.ts
  fe/src/service/constants/notificationTextMessage.ts
  fe/src/service/queries/feed.ts
  fe/src/types/collection.d.ts
  fe/src/types/notification.d.ts
Labels: FE

#531 [FE] Dev -> release
  fe/src/components/collection/GridItem.tsx
  fe/src/components/collection/ListItem.tsx
  fe/src/components/collection/profile/Collection.tsx
  fe/src/components/common/feedUserInfo/FeedUserInfo.tsx
  fe/src/components/common/userImage/UserImageEdit.tsx
  fe/src/components/feedProfile/FeedPofileList.tsx
  fe/src/components/follow/followList/FollowList.tsx
  fe/src/components/notification/NotiItem.tsx
  fe/src/components/notification/NotiList.tsx
  fe/src/components/profileEdit/ProfileEditForm.tsx
  fe/src/components/profileUserInfo/ProfileUserInfo.tsx
  fe/src/routes/router.tsx
  fe/src/service/axios/feed/feed.ts
  fe/src/service/constants/notificationTextMessage.ts
  fe/src/service/queries/feed.ts
  fe/src/types/collection.d.ts
  fe/src/types/notification.d.ts
Labels: FE, release

#533 [FE] 프로필페이지 이미지 클릭시 alert창이 무조건 열리던 버그 수정
  fe/src/components/common/userImage/UserImageEdit.tsx
Labels: FE, fix

#534 [FE] dev fe -> dev
  fe/src/components/common/userImage/UserImageEdit.tsx
Labels: FE, fix

#535 [FE] Dev -> release
  fe/src/components/common/userImage/UserImageEdit.tsx
Labels: FE, release

#537 [FE] dev fe-> dev
  fe/src/service/queries/follow.ts
Labels: FE, fix

#540 fix #539: deleted가 false일 때 count를 가져오도록 변경
  be/src/main/java/com/foodymoody/be/feed_comment/infra/persistence/jpa/FeedCommentJpaRepository.java
  be/src/test/java/com/foodymoody/be/acceptance/feed/FeedAcceptanceTest.java
Labels: BE, fix

#543 [BE] 오류 수정
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/com/foodymoody/be/feed_collection/application/service/FeedCollectionWriteService.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/usecase/FeedCollectionWriteScheduler.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/usecase/FeedCollectionWriteUseCase.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/usecase/dto/FeedCollectionAddFeedRequest.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/usecase/dto/FeedCollectionResponse.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedCollection.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedCollectionDetail.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedCollectionSummary.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedIds.java
  be/src/main/java/com/foodymoody/be/feed_collection/infra/persistence/FeedCollectionDaoImpl.java
  be/src/main/java/com/foodymoody/be/feed_collection/presentation/FeedCollectionWriteController.java
  be/src/main/java/com/foodymoody/be/feed_collection_like_count/application/service/FeedCollectionLikeCountReadService.java
  be/src/main/java/com/foodymoody/be/feed_collection_like_count/domain/FeedCollectionLikeCount.java
  be/src/main/java/com/foodymoody/be/feed_collection_like_count/domain/FeedCollectionLikeCountRepository.java
  be/src/main/java/com/foodymoody/be/feed_collection_like_count/infra/persistence/FeedCollectionLikeCountRepositoryImpl.java
  be/src/main/java/com/foodymoody/be/feed_comment/application/service/FeedCommentWriteService.java
  be/src/main/java/com/foodymoody/be/feed_comment/application/usecase/FeedCommentWriteUseCase.java
  be/src/main/java/com/foodymoody/be/feed_comment/domain/entity/FeedComment.java
  be/src/main/java/com/foodymoody/be/feed_comment/domain/entity/FeedReplyComments.java
  be/src/main/java/com/foodymoody/be/feed_comment/infra/persistence/FeedReplyRepositoryImpl.java
  be/src/main/java/com/foodymoody/be/feed_comment/infra/persistence/jpa/FeedReplyJpaRepository.java
  be/src/main/java/com/foodymoody/be/feed_comment/persentation/FeedCommentWriteController.java
  be/src/main/java/com/foodymoody/be/feed_comment/persentation/FeedReplyWriteController.java
  be/src/main/java/com/foodymoody/be/member/domain/Member.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/MemberFollowedEventHandler.java
  be/src/main/java/com/foodymoody/be/sse/application/service/SseAsyncService.java
  be/src/main/resources/application-localdb.yml
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection/FeedCollectionAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection/FeedCollectionSteps.java
  be/src/test/java/com/foodymoody/be/acceptance/notification/NotificationAcceptanceTest.java
Labels: BE, feat, fix

#544 [BE] 오류 수정
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/com/foodymoody/be/feed_collection/application/service/FeedCollectionWriteService.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/usecase/FeedCollectionWriteScheduler.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/usecase/FeedCollectionWriteUseCase.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/usecase/dto/FeedCollectionAddFeedRequest.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/usecase/dto/FeedCollectionResponse.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedCollection.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedCollectionDetail.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedCollectionSummary.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedIds.java
  be/src/main/java/com/foodymoody/be/feed_collection/infra/persistence/FeedCollectionDaoImpl.java
  be/src/main/java/com/foodymoody/be/feed_collection/presentation/FeedCollectionWriteController.java
  be/src/main/java/com/foodymoody/be/feed_collection_like_count/application/service/FeedCollectionLikeCountReadService.java
  be/src/main/java/com/foodymoody/be/feed_collection_like_count/domain/FeedCollectionLikeCount.java
  be/src/main/java/com/foodymoody/be/feed_collection_like_count/domain/FeedCollectionLikeCountRepository.java
  be/src/main/java/com/foodymoody/be/feed_collection_like_count/infra/persistence/FeedCollectionLikeCountRepositoryImpl.java
  be/src/main/java/com/foodymoody/be/feed_comment/application/service/FeedCommentWriteService.java
  be/src/main/java/com/foodymoody/be/feed_comment/application/usecase/FeedCommentWriteUseCase.java
  be/src/main/java/com/foodymoody/be/feed_comment/domain/entity/FeedComment.java
  be/src/main/java/com/foodymoody/be/feed_comment/domain/entity/FeedReplyComments.java
  be/src/main/java/com/foodymoody/be/feed_comment/infra/persistence/FeedReplyRepositoryImpl.java
  be/src/main/java/com/foodymoody/be/feed_comment/infra/persistence/jpa/FeedCommentJpaRepository.java
  be/src/main/java/com/foodymoody/be/feed_comment/infra/persistence/jpa/FeedReplyJpaRepository.java
  be/src/main/java/com/foodymoody/be/feed_comment/persentation/FeedCommentWriteController.java
  be/src/main/java/com/foodymoody/be/feed_comment/persentation/FeedReplyWriteController.java
  be/src/main/java/com/foodymoody/be/member/domain/Member.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/MemberFollowedEventHandler.java
  be/src/main/java/com/foodymoody/be/sse/application/service/SseAsyncService.java
  be/src/main/resources/application-localdb.yml
  be/src/test/java/com/foodymoody/be/acceptance/feed/FeedAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection/FeedCollectionAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection/FeedCollectionSteps.java
  be/src/test/java/com/foodymoody/be/acceptance/notification/NotificationAcceptanceTest.java
Labels: BE, fix

#545 [BE] 2월 20일 배포
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/com/foodymoody/be/feed_collection/application/service/FeedCollectionWriteService.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/usecase/FeedCollectionWriteScheduler.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/usecase/FeedCollectionWriteUseCase.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/usecase/dto/FeedCollectionAddFeedRequest.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/usecase/dto/FeedCollectionResponse.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedCollection.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedCollectionDetail.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedCollectionSummary.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedIds.java
  be/src/main/java/com/foodymoody/be/feed_collection/infra/persistence/FeedCollectionDaoImpl.java
  be/src/main/java/com/foodymoody/be/feed_collection/presentation/FeedCollectionWriteController.java
  be/src/main/java/com/foodymoody/be/feed_collection_like_count/application/service/FeedCollectionLikeCountReadService.java
  be/src/main/java/com/foodymoody/be/feed_collection_like_count/domain/FeedCollectionLikeCount.java
  be/src/main/java/com/foodymoody/be/feed_collection_like_count/domain/FeedCollectionLikeCountRepository.java
  be/src/main/java/com/foodymoody/be/feed_collection_like_count/infra/persistence/FeedCollectionLikeCountRepositoryImpl.java
  be/src/main/java/com/foodymoody/be/feed_comment/application/service/FeedCommentWriteService.java
  be/src/main/java/com/foodymoody/be/feed_comment/application/usecase/FeedCommentWriteUseCase.java
  be/src/main/java/com/foodymoody/be/feed_comment/domain/entity/FeedComment.java
  be/src/main/java/com/foodymoody/be/feed_comment/domain/entity/FeedReplyComments.java
  be/src/main/java/com/foodymoody/be/feed_comment/infra/persistence/FeedReplyRepositoryImpl.java
  be/src/main/java/com/foodymoody/be/feed_comment/infra/persistence/jpa/FeedCommentJpaRepository.java
  be/src/main/java/com/foodymoody/be/feed_comment/infra/persistence/jpa/FeedReplyJpaRepository.java
  be/src/main/java/com/foodymoody/be/feed_comment/persentation/FeedCommentWriteController.java
  be/src/main/java/com/foodymoody/be/feed_comment/persentation/FeedReplyWriteController.java
  be/src/main/java/com/foodymoody/be/member/domain/Member.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/MemberFollowedEventHandler.java
  be/src/main/java/com/foodymoody/be/sse/application/service/SseAsyncService.java
  be/src/main/resources/application-localdb.yml
  be/src/test/java/com/foodymoody/be/acceptance/feed/FeedAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection/FeedCollectionAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection/FeedCollectionSteps.java
  be/src/test/java/com/foodymoody/be/acceptance/notification/NotificationAcceptanceTest.java
Labels: BE, fix

#551 [FE] 알림 없을 때 읽음/삭제 요청 안되게 리팩토링
  fe/src/components/common/icon/NotiIcon.tsx
  fe/src/components/notification/NotiList.tsx
  fe/src/service/queries/follow.ts
  fe/src/service/queries/notification.ts
Labels: FE, refactor

#553 [FE] 컬렉션 내에 유저 피드 추가/삭제 기능 구현
  fe/src/assets/bin.svg
  fe/src/components/common/feedUserInfo/FeedUserInfo.tsx
  fe/src/components/common/icon/icons.ts
  fe/src/components/common/modal/CollectionAlert.tsx
  fe/src/components/common/modal/CollectionModal.tsx
  fe/src/components/common/modal/Modal.tsx
  fe/src/pages/CollectionDetailPage.tsx
  fe/src/service/axios/collection/collection.ts
  fe/src/service/constants/queryKey.ts
  fe/src/service/queries/collection.ts
  fe/src/types/modal.d.ts
Labels: FE, feat

#555 refactor: 피드 컬렉션 기본 페이지 변경
  be/src/main/java/com/foodymoody/be/feed_collection/application/service/FeedCollectionWriteService.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/usecase/FeedCollectionWriteUseCase.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedCollection.java
  be/src/test/java/com/foodymoody/be/feed_collection/domain/FeedCollectionRepositoryTest.java
  be/src/test/resources/data.sql
Labels: BE, fix

#556 refactor: 피드 컬렉션 기본 페이지 null로 변경
  be/src/main/java/com/foodymoody/be/feed_collection/application/service/FeedCollectionWriteService.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/usecase/FeedCollectionWriteUseCase.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedCollection.java
  be/src/test/java/com/foodymoody/be/feed_collection/domain/FeedCollectionRepositoryTest.java
  be/src/test/resources/data.sql
Labels: BE, feat

#557 dev -> release
  be/src/main/java/com/foodymoody/be/feed_collection/application/service/FeedCollectionWriteService.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/usecase/FeedCollectionWriteUseCase.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedCollection.java
  be/src/test/java/com/foodymoody/be/feed_collection/domain/FeedCollectionRepositoryTest.java
  be/src/test/resources/data.sql
Labels: BE
