Repository foody-moody/foodymoody, pull requests merged in 2024-01, with the labels that each got.

#369 [BE] 전체 알림 on/off 기능 구현
  be/src/main/java/com/foodymoody/be/notification_setting/application/NotificationSettingWriteService.java
  be/src/main/java/com/foodymoody/be/notification_setting/domain/NotificationSetting.java
  be/src/main/java/com/foodymoody/be/notification_setting/domain/NotificationSettingSummary.java
  be/src/main/java/com/foodymoody/be/notification_setting/infra/persistence/jpa/NotificationSettingJpaRepository.java
  be/src/main/java/com/foodymoody/be/notification_setting/infra/usecase/NotificationSettingReadUseCase.java
  be/src/main/java/com/foodymoody/be/notification_setting/infra/usecase/NotificationSettingResponse.java
  be/src/main/java/com/foodymoody/be/notification_setting/presentation/AllAllowRequest.java
  be/src/main/java/com/foodymoody/be/notification_setting/presentation/NotificationSettingReadController.java
  be/src/main/java/com/foodymoody/be/notification_setting/presentation/NotificationSettingWriteController.java
  be/src/test/java/com/foodymoody/be/acceptance/notification_setting/FeedNotificationSettingAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/notification_setting/NotificationSettingSteps.java
Labels: BE, feat

#374 [BE] dev-be -> dev
  be/src/main/java/com/foodymoody/be/notification_setting/application/NotificationSettingWriteService.java
  be/src/main/java/com/foodymoody/be/notification_setting/domain/NotificationSetting.java
  be/src/main/java/com/foodymoody/be/notification_setting/domain/NotificationSettingSummary.java
  be/src/main/java/com/foodymoody/be/notification_setting/infra/persistence/jpa/NotificationSettingJpaRepository.java
  be/src/main/java/com/foodymoody/be/notification_setting/infra/usecase/NotificationSettingReadUseCase.java
  be/src/main/java/com/foodymoody/be/notification_setting/infra/usecase/NotificationSettingResponse.java
  be/src/main/java/com/foodymoody/be/notification_setting/presentation/AllAllowRequest.java
  be/src/main/java/com/foodymoody/be/notification_setting/presentation/NotificationSettingReadController.java
  be/src/main/java/com/foodymoody/be/notification_setting/presentation/NotificationSettingWriteController.java
  be/src/test/java/com/foodymoody/be/acceptance/notification_setting/FeedNotificationSettingAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/notification_setting/NotificationSettingSteps.java
Labels: BE, fix

#375 [BE] dev -> release
  be/src/main/java/com/foodymoody/be/notification_setting/application/NotificationSettingWriteService.java
  be/src/main/java/com/foodymoody/be/notification_setting/domain/NotificationSetting.java
  be/src/main/java/com/foodymoody/be/notification_setting/domain/NotificationSettingSummary.java
  be/src/main/java/com/foodymoody/be/notification_setting/infra/persistence/jpa/NotificationSettingJpaRepository.java
  be/src/main/java/com/foodymoody/be/notification_setting/infra/usecase/NotificationSettingReadUseCase.java
  be/src/main/java/com/foodymoody/be/notification_setting/infra/usecase/NotificationSettingResponse.java
  be/src/main/java/com/foodymoody/be/notification_setting/presentation/AllAllowRequest.java
  be/src/main/java/com/foodymoody/be/notification_setting/presentation/NotificationSettingReadController.java
  be/src/main/java/com/foodymoody/be/notification_setting/presentation/NotificationSettingWriteController.java
  be/src/test/java/com/foodymoody/be/acceptance/notification_setting/FeedNotificationSettingAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/notification_setting/NotificationSettingSteps.java
Labels: BE, fix

#356 [FE] 컬렉션 등록 수정 관련 modal 컴포넌트, MoodBadge 관련 리팩토링
  fe/src/assets/plusSquare.svg
  fe/src/components/common/badge/Badge.tsx
  fe/src/components/common/badge/StoreMoodBadge.tsx
  fe/src/components/common/badge/StoreMoodSelector.tsx
  fe/src/components/common/badge/TasteMoodBadge.tsx
  fe/src/components/common/badgeSelector/BadgeSelector.tsx
  fe/src/components/common/checkbox/CheckBox.tsx
  fe/src/components/common/feedUserInfo/FeedUserInfo.tsx
  fe/src/components/common/icon/icons.ts
  fe/src/components/common/modal/CollectionModal.tsx
  fe/src/components/common/modal/Modal.tsx
  fe/src/components/feedEditor/FeedEditor.tsx
  fe/src/components/feedMain/FeedMainItem.tsx
  fe/src/components/profileUserInfo/ProfileUserInfo.tsx
  fe/src/pages/DetailFeedPage.tsx
  fe/src/styles/designSystem.ts
  fe/src/types/modal.d.ts
  fe/src/types/mood.d.ts
Labels: FE, feat, refactor, review

#380 [BE] isLiked 로직 수정 후 FeedCollection 인수 테스트 작성
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/com/foodymoody/be/common/exception/ErrorMessage.java
  be/src/main/java/com/foodymoody/be/common/exception/IsLikedNotExistsException.java
  be/src/main/java/com/foodymoody/be/feed/application/FeedMapper.java
  be/src/main/java/com/foodymoody/be/feed/application/FeedReadService.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/request/CollectionReadFeedDetailsServiceRequest.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/CollectionReadFeedDetailsResponse.java
  be/src/main/java/com/foodymoody/be/feed/domain/entity/Feed.java
  be/src/main/java/com/foodymoody/be/feed/infra/persistence/jpa/FeedJpaRepository.java
  be/src/main/java/com/foodymoody/be/feed/infra/usecase/CollectionUseCase.java
  be/src/main/java/com/foodymoody/be/feed/infra/usecase/FeedUseCase.java
  be/src/main/java/com/foodymoody/be/feed/presentation/CollectionController.java
  be/src/main/java/com/foodymoody/be/feed/presentation/FeedController.java
  be/src/main/java/com/foodymoody/be/feed_heart/application/FeedHeartMapper.java
  be/src/main/java/com/foodymoody/be/feed_heart/application/FeedHeartService.java
  be/src/main/java/com/foodymoody/be/feed_heart/domain/entity/FeedHeart.java
  be/src/main/resources/application-filter.yml
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection/FeedCollectionAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection/FeedCollectionSteps.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_heart/FeedHeartAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_heart/FeedHeartSteps.java
  be/src/test/java/com/foodymoody/be/feed/application/FeedMapperTest.java
Labels: BE, fix, test

#389 [BE] 피드 삭제 시에 이미지도 soft delete로 삭제되도록 구현
  be/src/main/java/com/foodymoody/be/feed/application/FeedMapper.java
  be/src/main/java/com/foodymoody/be/feed/infra/usecase/FeedUseCase.java
  be/src/test/java/com/foodymoody/be/acceptance/comment/CommentAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/comment_heart/CommentFeedHeartAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed/FeedAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed/FeedSteps.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection/FeedCollectionAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection_comment/FeedCollectionCommentAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection_comment_like/FeedCollectionCommentLikeAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection_like/FeedCollectionLikeAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection_reply/FeedCollectionReplyAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection_reply_like/FeedCollectionReplyLikeAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_heart/FeedHeartAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/member/MemberAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/notification/FeedNotificationAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/reply/ReplyAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/reply_heart/ReplyFeedHeartAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/sse/SseAcceptanceTest.java
Labels: BE, feat, test

#392 [BE] 피드 리팩토링
  be/src/main/java/com/foodymoody/be/common/exception/ErrorMessage.java
  be/src/main/java/com/foodymoody/be/common/exception/FeedHeartAlreadyExistsException.java
  be/src/main/java/com/foodymoody/be/common/exception/NotFoundFeedHeartException.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedReadAllResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedReadResponse.java
  be/src/main/java/com/foodymoody/be/feed/domain/entity/FeedStoreMood.java
  be/src/main/java/com/foodymoody/be/feed_heart/application/FeedHeartService.java
  be/src/main/java/com/foodymoody/be/feed_heart/application/dto/request/FeedHeartRequest.java
  be/src/main/java/com/foodymoody/be/feed_heart/application/dto/request/FeedHeartServiceRequest.java
  be/src/main/java/com/foodymoody/be/feed_heart/application/dto/response/FeedHeartResponse.java
  be/src/main/java/com/foodymoody/be/feed_heart/presentation/FeedHeartController.java
  be/src/test/java/com/foodymoody/be/acceptance/feed/FeedAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed/FeedSteps.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_heart/FeedHeartSteps.java
Labels: BE, refactor

#395 [BE] feedId에 따른 Comment의 개수를 Response에 추가
  be/src/main/java/com/foodymoody/be/comment/application/CommentReadService.java
  be/src/main/java/com/foodymoody/be/comment/domain/repository/CommentRepository.java
  be/src/main/java/com/foodymoody/be/comment/infra/persistence/jpa/CommentJpaRepository.java
  be/src/main/java/com/foodymoody/be/feed/application/FeedCommentCountReadService.java
  be/src/main/java/com/foodymoody/be/feed/application/FeedMapper.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/CollectionReadFeedDetailsResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedReadAllResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedReadResponse.java
  be/src/main/java/com/foodymoody/be/feed/infra/usecase/CollectionUseCase.java
  be/src/main/java/com/foodymoody/be/feed/infra/usecase/FeedUseCase.java
  be/src/main/java/com/foodymoody/be/feed/presentation/FeedController.java
  be/src/test/java/com/foodymoody/be/feed/application/FeedMapperTest.java
Labels: BE, feat

#396 [BE] 피드 댓글(대댓글) 테스트 구현
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/com/foodymoody/be/comment/application/CommentReadService.java
  be/src/main/java/com/foodymoody/be/comment/application/CommentWriteService.java
  be/src/main/java/com/foodymoody/be/comment/application/ReplyReadService.java
  be/src/main/java/com/foodymoody/be/comment/domain/entity/Comment.java
  be/src/main/java/com/foodymoody/be/comment/domain/entity/CommentAddedEvent.java
  be/src/main/java/com/foodymoody/be/comment/domain/entity/Reply.java
  be/src/main/java/com/foodymoody/be/comment/domain/entity/ReplyComments.java
  be/src/main/java/com/foodymoody/be/comment/domain/repository/CommentRepository.java
  be/src/main/java/com/foodymoody/be/comment/infra/persistence/CommentRepositoryImpl.java
  be/src/main/java/com/foodymoody/be/comment/infra/persistence/jpa/CommentJpaRepository.java
  be/src/main/java/com/foodymoody/be/comment/persentation/CommentWriteController.java
  be/src/main/java/com/foodymoody/be/common/annotation/MemberId.java
  be/src/main/java/com/foodymoody/be/common/annotation/MemberIdArgumentResolver.java
  be/src/main/java/com/foodymoody/be/common/config/ArgumentResolverConfig.java
  be/src/main/java/com/foodymoody/be/common/exception/ErrorMessage.java
  be/src/main/java/com/foodymoody/be/common/exception/ReplyNotExistsException.java
  be/src/main/java/com/foodymoody/be/common/util/ids/BaseId.java
  be/src/main/java/com/foodymoody/be/common/util/ids/ReplyId.java
  be/src/test/java/com/foodymoody/be/acceptance/comment/CommentAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/comment/CommentSteps.java
  be/src/test/java/com/foodymoody/be/acceptance/notification/FeedNotificationAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/reply/ReplyAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/reply/ReplySteps.java
  be/src/test/java/com/foodymoody/be/acceptance/reply_heart/ReplyFeedHeartAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/reply_heart/ReplyHeartSteps.java
  be/src/test/java/com/foodymoody/be/acceptance/sse/SseAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/sse/SseSteps.java
  be/src/test/java/com/foodymoody/be/comment/application/CommentWriteServiceTest.java
  be/src/test/java/com/foodymoody/be/comment/application/ReplyReadServiceTest.java
  be/src/test/java/com/foodymoody/be/comment/domain/CommentTest.java
  be/src/test/java/com/foodymoody/be/comment/domain/entity/ReplyTest.java
  be/src/test/java/com/foodymoody/be/comment/util/CommentFixture.java
  be/src/test/java/com/foodymoody/be/comment/util/CommentMapperTest.java
  be/src/test/java/com/foodymoody/be/comment/util/CommentValidatorTest.java
  be/src/test/java/com/foodymoody/be/common/util/ids/ReplyIdTest.java
  be/src/test/java/com/foodymoody/be/sse/controller/SseControllerTest.java
Labels: BE, refactor

#399 [FE] 읽은 알림 삭제, 전체 읽음 및 알림 설정 업데이트 관련 api 연동 작업
  fe/src/components/common/switch/Switch.tsx
  fe/src/pages/NotiPage.tsx
  fe/src/pages/NotiSettingPage.tsx
  fe/src/service/axios/notifications/notifications.ts
  fe/src/service/constants/endpoint.ts
  fe/src/service/constants/queryKey.ts
  fe/src/service/queries/notification.ts
  fe/src/types/notification.d.ts
Labels: FE, feat

#401 [BE] hot fix 피드 컬렉션 조회
  be/src/main/java/com/foodymoody/be/feed/application/FeedMapper.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/request/CollectionReadFeedDetailsServiceRequest.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/CollectionReadFeedDetailsResponse.java
  be/src/main/java/com/foodymoody/be/feed/infra/usecase/CollectionUseCase.java
  be/src/main/java/com/foodymoody/be/feed/presentation/CollectionController.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection/FeedCollectionAcceptanceTest.java
Labels: BE, fix

#397 [BE] 가게 프로토타입
  be/build.gradle
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/com/foodymoody/be/common/exception/ErrorMessage.java
  be/src/main/java/com/foodymoody/be/common/exception/StoreNotFoundException.java
  be/src/main/java/com/foodymoody/be/common/util/ids/StoreId.java
  be/src/main/java/com/foodymoody/be/store/application/StoreReadService.java
  be/src/main/java/com/foodymoody/be/store/application/dto/response/StoreDetailsResponse.java
  be/src/main/java/com/foodymoody/be/store/application/dto/response/StoreSearchResponse.java
  be/src/main/java/com/foodymoody/be/store/domain/LocalDataKey.java
  be/src/main/java/com/foodymoody/be/store/domain/Store.java
  be/src/main/java/com/foodymoody/be/store/domain/StoreRepository.java
  be/src/main/java/com/foodymoody/be/store/domain/StoreStatus.java
  be/src/main/java/com/foodymoody/be/store/infra/StoreJpaRepository.java
  be/src/main/java/com/foodymoody/be/store/infra/StoreQueryDslRepository.java
  be/src/main/java/com/foodymoody/be/store/infra/StoreQueryDslRepositoryImpl.java
  be/src/main/java/com/foodymoody/be/store/presentation/StoreController.java
  be/src/main/resources/application-filter.yml
  be/src/test/java/com/foodymoody/be/acceptance/store/StoreAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/store/StoreSteps.java
  be/src/test/java/com/foodymoody/be/image/infra/ImageRepositoryTest.java
  be/src/test/java/com/foodymoody/be/store/StoreRepositoryTest.java
  be/src/test/resources/data.sql
Labels: BE, feat

#404 [FE] 컬렉션 메인페이지 api 인터페이스 수정, 드롭다운 추가
  fe/package.json
  fe/src/assets/santaHat.svg
  fe/src/components/collection/CollectionContainer.tsx
  fe/src/components/collection/GridItem.tsx
  fe/src/components/collection/GridLayout.tsx
  fe/src/components/collection/ListItem.tsx
  fe/src/components/collection/ListLayout.tsx
  fe/src/components/common/headerMob/HeaderMob.tsx
  fe/src/components/common/icon/icons.ts
  fe/src/components/common/logo/Logo.tsx
  fe/src/components/common/modal/CollectionModal.tsx
  fe/src/components/notification/NotiItem.tsx
  fe/src/components/profileUserInfo/ProfileUserInfo.tsx
  fe/src/components/register/RegisterForm.tsx
  fe/src/components/searchPanelInput/SearchPanelInput.tsx
  fe/src/hooks/auth/useAuth.ts
  fe/src/pages/CollectionPage.tsx
  fe/src/pages/HomePage.tsx
  fe/src/service/axios/collection/collection.ts
  fe/src/service/constants/endpoint.ts
  fe/src/service/queries/collection.ts
  fe/src/service/queries/notification.ts
  fe/src/types/collection.d.ts
  fe/vite.config.ts.timestamp-1702496076404-afa74354b96ab.mjs
Labels: FE, feat, fix

#408 [FE] dev-fe -> dev
  fe/src/service/queries/auth.ts
Labels: FE

#409 [FE] Dev -> release
  fe/src/service/queries/auth.ts
Labels: FE, release

#411 [FE] dev-fe -> dev
  fe/src/components/common/menuItemEditor/ImageBox.tsx
  fe/src/components/common/userImage/UserImage.tsx
  fe/src/components/common/userImage/UserImageEdit.tsx
Labels: FE

#412 [FE] dev -> release
  fe/src/components/common/menuItemEditor/ImageBox.tsx
  fe/src/components/common/userImage/UserImage.tsx
  fe/src/components/common/userImage/UserImageEdit.tsx
Labels: FE, release

#414 [FE] headerMob에 있는 알림아이콘에 notipage navigate추가 (#413)
  fe/src/components/common/headerMob/HeaderMob.tsx
Labels: FE, fix

#415 [FE] dev -> release
  fe/src/components/common/headerMob/HeaderMob.tsx
Labels: FE, release

#417 [BE] Feed에 Store API 연동
  be/src/main/java/com/foodymoody/be/common/util/ids/IdFactory.java
  be/src/main/java/com/foodymoody/be/feed/application/FeedMapper.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/request/FeedRegisterRequest.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/request/FeedServiceRegisterRequest.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/request/FeedServiceUpdateRequest.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/request/FeedUpdateRequest.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedReadAllResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedReadResponse.java
  be/src/main/java/com/foodymoody/be/feed/domain/entity/Feed.java
  be/src/main/java/com/foodymoody/be/feed/infra/usecase/CollectionUseCase.java
  be/src/main/java/com/foodymoody/be/feed/infra/usecase/FeedUseCase.java
  be/src/main/java/com/foodymoody/be/feed/presentation/FeedController.java
  be/src/test/java/com/foodymoody/be/acceptance/feed/FeedSteps.java
  be/src/test/java/com/foodymoody/be/feed/application/FeedHeartCountServiceTest.java
  be/src/test/java/com/foodymoody/be/feed/application/FeedMapperTest.java
Labels: BE, feat, test

#426 [FE] 메인 컬렉션 페이지 캐러셀 구현
  fe/src/components/collection/GridItem.tsx
  fe/src/components/common/carousel/CollectionCarousel.tsx
  fe/src/pages/CollectionPage.tsx
  fe/src/types/collection.d.ts
Labels: FE, feat

#422 [BE] 피드 컬렉션에 thumbnailUrl 구현
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/com/foodymoody/be/comment/domain/entity/Comment.java
  be/src/main/java/com/foodymoody/be/comment/domain/entity/Reply.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/FeedCollectionWriterService.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedCollection.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedCollectionDetail.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedCollectionSummary.java
  be/src/main/java/com/foodymoody/be/feed_collection/infra/persistence/FeedCollectionDaoImpl.java
  be/src/main/java/com/foodymoody/be/feed_collection/infra/usecase/FeedCollectionMapper.java
  be/src/main/java/com/foodymoody/be/feed_collection/infra/usecase/FeedCollectionWriteUseCase.java
  be/src/main/java/com/foodymoody/be/feed_collection/infra/usecase/dto/FeedCollectionFeedsUpdateRequest.java
  be/src/main/java/com/foodymoody/be/feed_collection/infra/usecase/dto/FeedCollectionResponse.java
  be/src/main/java/com/foodymoody/be/feed_collection/presentation/FeedCollectionWriteController.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection/FeedCollectionAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection/FeedCollectionSteps.java
  be/src/test/java/com/foodymoody/be/feed_collection/domain/FeedCollectionRepositoryTest.java
Labels: BE, feat

#430 [BE] StoreMood, Menu 리팩토링
  be/src/main/java/com/foodymoody/be/feed/application/FeedMapper.java
  be/src/main/java/com/foodymoody/be/feed/application/FeedValidator.java
  be/src/main/java/com/foodymoody/be/feed/application/ImageMenuMapper.java
  be/src/main/java/com/foodymoody/be/feed/application/StoreMoodReadService.java
  be/src/main/java/com/foodymoody/be/feed/domain/entity/Feed.java
  be/src/main/java/com/foodymoody/be/feed/domain/entity/ImageMenus.java
  be/src/main/java/com/foodymoody/be/feed/domain/entity/Menus.java
  be/src/main/java/com/foodymoody/be/feed/domain/repository/StoreMoodRepository.java
  be/src/main/java/com/foodymoody/be/feed/infra/persistence/jpa/StoreMoodJpaRepository.java
  be/src/main/java/com/foodymoody/be/feed/infra/persistence/jpa/StoreMoodRepositoryImpl.java
  be/src/main/java/com/foodymoody/be/feed/infra/usecase/FeedUseCase.java
  be/src/main/java/com/foodymoody/be/menu/application/MenuMapper.java
  be/src/main/java/com/foodymoody/be/menu/application/MenuService.java
  be/src/main/java/com/foodymoody/be/menu/domain/entity/Menu.java
  be/src/main/java/com/foodymoody/be/menu/domain/repository/MenuRepository.java
  be/src/main/java/com/foodymoody/be/menu/infra/persistence/MenuRepositoryImpl.java
  be/src/main/java/com/foodymoody/be/menu/infra/persistence/jpa/MenuJpaRepository.java
  be/src/main/java/com/foodymoody/be/menu/repository/MenuRepository.java
  be/src/main/java/com/foodymoody/be/menu/service/MenuService.java
  be/src/test/java/com/foodymoody/be/feed/application/FeedHeartCountServiceTest.java
  be/src/test/java/com/foodymoody/be/feed/application/FeedMapperTest.java
  be/src/test/java/com/foodymoody/be/feed/application/MenuMapperTest.java
Labels: BE, refactor

#444 [BE] 피드 개별 조회, 전체 조회 Store Response 수정
  be/src/main/java/com/foodymoody/be/feed/application/FeedMapper.java
  be/src/main/java/com/foodymoody/be/feed/application/StoreMoodReadService.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedReadAllResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedReadResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/StoreResponse.java
  be/src/main/java/com/foodymoody/be/feed/domain/repository/StoreMoodRepository.java
  be/src/main/java/com/foodymoody/be/feed/infra/persistence/jpa/StoreMoodJpaRepository.java
  be/src/main/java/com/foodymoody/be/feed/infra/persistence/jpa/StoreMoodRepositoryImpl.java
  be/src/main/java/com/foodymoody/be/feed/infra/usecase/FeedUseCase.java
  be/src/test/java/com/foodymoody/be/feed/application/FeedMapperTest.java
Labels: BE, fix

#448 [FE] 컬렉션 디테일 페이지 UI
  fe/src/assets/share.svg
  fe/src/assets/store.svg
  fe/src/components/common/badge/StoreMoodBadge.tsx
  fe/src/components/common/icon/icons.ts
  fe/src/pages/CollectionDetailPage.tsx
  fe/src/routes/router.tsx
  fe/src/service/axios/collection/collection.ts
Labels: design, FE, feat

#449 [Be] Feed request 검증 추가
  be/src/main/java/com/foodymoody/be/feed/application/dto/request/FeedRegisterRequest.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/request/FeedUpdateRequest.java
Labels: BE, feat

#451 [FE] dev-fe -> dev
  fe/index.html
  fe/package-lock.json
  fe/package.json
  fe/src/assets/copyS.svg
  fe/src/assets/phone.svg
  fe/src/assets/share.svg
  fe/src/assets/store.svg
  fe/src/components/collection/CollectionContainer.tsx
  fe/src/components/collection/GridItem.tsx
  fe/src/components/collection/ListItem.tsx
  fe/src/components/collection/profile/Collection.tsx
  fe/src/components/common/badge/StoreMoodBadge.tsx
  fe/src/components/common/carousel/CollectionCarousel.tsx
  fe/src/components/common/commentItem/CommentBox.tsx
  fe/src/components/common/commentItem/CommentItem.tsx
  fe/src/components/common/feedAction/FeedAction.tsx
  fe/src/components/common/feedUserInfo/FeedUserInfo.tsx
  fe/src/components/common/feedUserInfo/Share.tsx
  fe/src/components/common/help/EmptyProfileFeeds.tsx
  fe/src/components/common/icon/icons.ts
  fe/src/components/feedEditor/FeedEditor.tsx
  fe/src/components/feedLike/FeedLikeList.tsx
  fe/src/components/feedMain/FeedMainItem.tsx
  fe/src/components/feedProfile/FeedPofileList.tsx
  fe/src/components/feedProfile/FeedProfleItem.tsx
  fe/src/components/follow/followList/FollowListRow.tsx
  fe/src/components/layoutButton/LayoutButton.tsx
  fe/src/components/map/Map.tsx
  fe/src/components/notification/NotiItem.tsx
  fe/src/components/profileUserInfo/ProfileUserInfo.tsx
  fe/src/components/searchLocation/SearchLocation.tsx
  fe/src/components/searchPanelInput/SearchPanelInput.tsx
  fe/src/components/sort/SelectSort.tsx
  fe/src/hooks/useDebounce.ts
  fe/src/pages/CollectionDetailPage.tsx
  fe/src/pages/CollectionPage.tsx
  fe/src/pages/DetailFeedPage.tsx
  fe/src/pages/HomePage.tsx
  fe/src/pages/ProfilePage.tsx
  fe/src/pages/StorePage.tsx
  fe/src/recoil/localStorage/atom.ts
  fe/src/recoil/localStorage/useLoginInfo.ts
  fe/src/recoil/sortState/atom.ts
  fe/src/recoil/sortState/useSort.ts
  fe/src/routes/router.tsx
  fe/src/service/axios/collection/collection.ts
  fe/src/service/axios/feed/feed.ts
  fe/src/service/axios/store/store.ts
  fe/src/service/constants/endpoint.ts
  fe/src/service/constants/queryKey.ts
  fe/src/service/queries/auth.ts
  fe/src/service/queries/collection.ts
  fe/src/service/queries/feed.ts
  fe/src/service/queries/store.ts
  fe/src/types/collection.d.ts
  fe/src/types/comment.d.ts
  fe/src/types/feed.d.ts
  fe/src/types/naver.d.ts
  fe/src/types/store.d.ts
  fe/src/utils/formatPhoneNum.ts
Labels: FE, release

#454 [FE] 공유하기 핫픽스
  fe/src/components/common/feedUserInfo/Share.tsx
  fe/src/pages/HomePage.tsx
Labels: FE, fix

#455 [FE] dev-fe -> dev
  fe/src/components/common/feedUserInfo/Share.tsx
  fe/src/pages/HomePage.tsx
Labels: feat, release

#456 [FE] Dev-> release
  fe/src/components/common/feedUserInfo/Share.tsx
  fe/src/pages/HomePage.tsx
Labels: FE, release

#457 [BE] 알림 Details Map을 객체로 변경
  be/src/main/java/com/foodymoody/be/feed_comment/domain/entity/FeedComment.java
  be/src/main/java/com/foodymoody/be/feed_comment/domain/entity/FeedCommentReplyAddedEvent.java
  be/src/main/java/com/foodymoody/be/feed_like/domain/FeedLikeRepository.java
  be/src/main/java/com/foodymoody/be/feed_like_count/application/FeedLikeCountService.java
  be/src/main/java/com/foodymoody/be/feed_like_count/domain/FeedLikeCountRepository.java
  be/src/main/java/com/foodymoody/be/feed_reply_like/domain/FeedReplyLike.java
  be/src/main/java/com/foodymoody/be/feed_reply_like/domain/FeedReplyLikeAddedEvent.java
  be/src/main/java/com/foodymoody/be/feed_reply_like_count/infra/event/ReplyHeartCountReplyEventHandler.java
  be/src/main/java/com/foodymoody/be/notification/domain/Notification.java
  be/src/main/java/com/foodymoody/be/notification/domain/NotificationDetails.java
  be/src/main/java/com/foodymoody/be/notification/domain/NotificationDetailsConverter.java
  be/src/main/java/com/foodymoody/be/notification/domain/NotificationSummary.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/FeedCollectionCommentEventHandler.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/FeedCollectionCommentLikeEventHandler.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/FeedCollectionEventHandler.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/FeedCollectionLikeAddedEventHandler.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/FeedCollectionReplyEventHandler.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/FeedCollectionReplyLikeEventHandler.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/FeedCommentEventHandler.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/FeedCommentLikedEventHandler.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/FeedCommentReplyEventHandler.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/FeedCommentReplyLikeEventHandler.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/FeedEventHandler.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/FeedLikeAddedEventHandler.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/MemberFollowedEventHandler.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/dto/FeedCollectionCommentLikeNotificationDetails.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/dto/FeedCollectionCommentNotificationDetails.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/dto/FeedCollectionLikeNotificationDetails.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/dto/FeedCollectionNotificationDetails.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/dto/FeedCollectionReplyLikeNotificationDetails.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/dto/FeedCollectionReplyNotificationDetails.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/dto/FeedCommentLikeNotificationDetails.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/dto/FeedCommentNotificationDetails.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/dto/FeedCommentReplyLikeNotificationDetails.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/dto/FeedCommentReplyNotificationDetails.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/dto/FeedLikeNotificationDetails.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/dto/FeedNotificationDetails.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/dto/MemberFollowedNotificationDetails.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/util/NotificationMapper.java
  be/src/main/java/com/foodymoody/be/notification/infra/persistence/jpa/NotificationJpaRepository.java
  be/src/main/java/com/foodymoody/be/notification/infra/usecase/NotificationUseCase.java
  be/src/main/java/com/foodymoody/be/notification/infra/usecase/dto/NotificationResponse.java
  be/src/main/java/com/foodymoody/be/notification/presentation/NotificationWriteController.java
  be/src/test/java/com/foodymoody/be/feed/application/FeedLikeCountServiceTest.java
  be/src/test/java/com/foodymoody/be/feed_comment/domain/FeedCommentTest.java
  be/src/test/java/com/foodymoody/be/notification/util/NotificationFixture.java
Labels: BE, feat

#458 [BE] 피드 request 검증 테스트 코드 작성
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/com/foodymoody/be/feed/presentation/FeedController.java
  be/src/test/java/com/foodymoody/be/acceptance/feed/FeedAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed/FeedSteps.java
Labels: BE, test

#468 [BE] Feed isLiked false로만 들어오는 문제 해결
  be/src/main/java/com/foodymoody/be/feed/application/FeedReadService.java
  be/src/main/java/com/foodymoody/be/feed/application/StoreMoodReadService.java
  be/src/main/java/com/foodymoody/be/feed/domain/repository/FeedRepository.java
  be/src/main/java/com/foodymoody/be/feed/infra/persistence/FeedRepositoryImpl.java
  be/src/main/java/com/foodymoody/be/feed/infra/persistence/jpa/FeedJpaRepository.java
  be/src/main/java/com/foodymoody/be/feed/infra/usecase/CollectionUseCase.java
  be/src/main/java/com/foodymoody/be/feed/infra/usecase/FeedUseCase.java
  be/src/main/java/com/foodymoody/be/feed_like/application/FeedLikeService.java
  be/src/main/java/com/foodymoody/be/feed_like/domain/FeedLikeRepository.java
  be/src/main/java/com/foodymoody/be/feed_like/infra/persistence/FeedLikeRepositoryImpl.java
  be/src/main/java/com/foodymoody/be/feed_like/infra/persistence/jpa/FeedLikeJpaRepository.java
  be/src/test/java/com/foodymoody/be/acceptance/feed/FeedAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed/FeedSteps.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_like/FeedLikeAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_like/FeedLikeSteps.java
  be/src/test/java/com/foodymoody/be/acceptance/notification/NotificationAcceptanceTest.java
Labels: BE, fix, test

#470 dev-be to dev
  be/src/main/java/com/foodymoody/be/feed/application/FeedReadService.java
  be/src/main/java/com/foodymoody/be/feed/application/StoreMoodReadService.java
  be/src/main/java/com/foodymoody/be/feed/domain/repository/FeedRepository.java
  be/src/main/java/com/foodymoody/be/feed/infra/persistence/FeedRepositoryImpl.java
  be/src/main/java/com/foodymoody/be/feed/infra/persistence/jpa/FeedJpaRepository.java
  be/src/main/java/com/foodymoody/be/feed/infra/usecase/CollectionUseCase.java
  be/src/main/java/com/foodymoody/be/feed/infra/usecase/FeedUseCase.java
  be/src/main/java/com/foodymoody/be/feed_like/application/FeedLikeService.java
  be/src/main/java/com/foodymoody/be/feed_like/domain/FeedLikeRepository.java
  be/src/main/java/com/foodymoody/be/feed_like/infra/persistence/FeedLikeRepositoryImpl.java
  be/src/main/java/com/foodymoody/be/feed_like/infra/persistence/jpa/FeedLikeJpaRepository.java
  be/src/test/java/com/foodymoody/be/acceptance/feed/FeedAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed/FeedSteps.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_like/FeedLikeAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_like/FeedLikeSteps.java
  be/src/test/java/com/foodymoody/be/acceptance/notification/NotificationAcceptanceTest.java
Labels: BE, fix, test, release

#471 dev to release
  be/src/main/java/com/foodymoody/be/feed/application/FeedReadService.java
  be/src/main/java/com/foodymoody/be/feed/application/StoreMoodReadService.java
  be/src/main/java/com/foodymoody/be/feed/domain/repository/FeedRepository.java
  be/src/main/java/com/foodymoody/be/feed/infra/persistence/FeedRepositoryImpl.java
  be/src/main/java/com/foodymoody/be/feed/infra/persistence/jpa/FeedJpaRepository.java
  be/src/main/java/com/foodymoody/be/feed/infra/usecase/CollectionUseCase.java
  be/src/main/java/com/foodymoody/be/feed/infra/usecase/FeedUseCase.java
  be/src/main/java/com/foodymoody/be/feed_like/application/FeedLikeService.java
  be/src/main/java/com/foodymoody/be/feed_like/domain/FeedLikeRepository.java
  be/src/main/java/com/foodymoody/be/feed_like/infra/persistence/FeedLikeRepositoryImpl.java
  be/src/main/java/com/foodymoody/be/feed_like/infra/persistence/jpa/FeedLikeJpaRepository.java
  be/src/test/java/com/foodymoody/be/acceptance/feed/FeedAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed/FeedSteps.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_like/FeedLikeAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_like/FeedLikeSteps.java
  be/src/test/java/com/foodymoody/be/acceptance/notification/NotificationAcceptanceTest.java
Labels: BE, fix, test, release

#472 refactor: 알림 응답 통일
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedCollection.java
  be/src/main/java/com/foodymoody/be/feed_collection/domain/FeedCollectionAddedEvent.java
  be/src/main/java/com/foodymoody/be/feed_comment/domain/entity/FeedComment.java
  be/src/main/java/com/foodymoody/be/feed_comment/domain/entity/FeedCommentReplyAddedEvent.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/FeedCollectionCommentEventHandler.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/FeedCollectionCommentLikeEventHandler.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/FeedCollectionEventHandler.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/FeedCollectionLikeAddedEventHandler.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/FeedCollectionReplyEventHandler.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/FeedCollectionReplyLikeEventHandler.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/FeedCommentReplyEventHandler.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/FeedCommentReplyLikeEventHandler.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/dto/FeedCollectionCommentLikeNotificationDetails.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/dto/FeedCollectionCommentNotificationDetails.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/dto/FeedCollectionLikeNotificationDetails.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/dto/FeedCollectionNotificationDetails.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/dto/FeedCollectionReplyLikeNotificationDetails.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/dto/FeedCollectionReplyNotificationDetails.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/dto/FeedCommentLikeNotificationDetails.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/dto/FeedCommentNotificationDetails.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/dto/FeedCommentReplyLikeNotificationDetails.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/dto/FeedCommentReplyNotificationDetails.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/dto/FeedNotificationDetails.java
  be/src/test/java/com/foodymoody/be/notification/util/NotificationFixture.java
Labels: BE, fix

#475 [BE] 알림 리펙토링
  be/src/main/java/com/foodymoody/be/common/exception/ErrorMessage.java
  be/src/main/java/com/foodymoody/be/common/exception/PermissionDeniedAccessNotificationException.java
  be/src/main/java/com/foodymoody/be/notification/application/NotificationWriteService.java
  be/src/main/java/com/foodymoody/be/notification/domain/Notification.java
  be/src/main/java/com/foodymoody/be/notification/domain/NotificationDetailsConverter.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/FeedCollectionCommentEventHandler.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/FeedCollectionCommentLikeEventHandler.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/FeedCollectionEventHandler.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/FeedCollectionLikeAddedEventHandler.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/FeedCollectionReplyEventHandler.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/FeedCollectionReplyLikeEventHandler.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/FeedCommentEventHandler.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/FeedCommentLikedEventHandler.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/FeedCommentReplyEventHandler.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/FeedCommentReplyLikeEventHandler.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/FeedEventHandler.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/FeedLikeEventHandler.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/MemberFollowedEventHandler.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/util/NotificationDetailsFactory.java
  be/src/main/java/com/foodymoody/be/notification/infra/usecase/NotificationReadUseCase.java
  be/src/main/java/com/foodymoody/be/notification/infra/usecase/NotificationResponseMapper.java
  be/src/main/java/com/foodymoody/be/notification/infra/usecase/dto/NotificationResponse.java
  be/src/test/java/com/foodymoody/be/notification/domain/NotificationTest.java
Labels: BE, refactor

#479 [FE] dev-fe -> dev
  fe/src/components/common/commentItem/CommentItem.tsx
  fe/src/components/common/commentItem/ReplyItem.tsx
  fe/src/components/common/input/Input.tsx
  fe/src/components/common/input/InputHelperText.tsx
  fe/src/components/common/userImage/UserImage.tsx
  fe/src/components/feedMain/FeedMainItem.tsx
  fe/src/components/profileEdit/ProfileEditForm.tsx
  fe/src/components/profileUserInfo/ProfileUserInfo.tsx
  fe/src/components/validatedInput/ValidatedInput.tsx
  fe/src/pages/DetailFeedPage.tsx
  fe/src/service/axios/fetcher.ts
  fe/src/service/queries/comment.ts
  fe/src/service/queries/feed.ts
  fe/src/service/queries/like.ts
  fe/src/service/queries/reply.ts
  fe/src/types/feed.d.ts
Labels: FE, release

#480 [FE] dev->release
  fe/src/components/common/commentItem/CommentItem.tsx
  fe/src/components/common/commentItem/ReplyItem.tsx
  fe/src/components/common/input/Input.tsx
  fe/src/components/common/input/InputHelperText.tsx
  fe/src/components/common/userImage/UserImage.tsx
  fe/src/components/feedMain/FeedMainItem.tsx
  fe/src/components/profileEdit/ProfileEditForm.tsx
  fe/src/components/profileUserInfo/ProfileUserInfo.tsx
  fe/src/components/validatedInput/ValidatedInput.tsx
  fe/src/pages/DetailFeedPage.tsx
  fe/src/service/axios/fetcher.ts
  fe/src/service/queries/comment.ts
  fe/src/service/queries/feed.ts
  fe/src/service/queries/like.ts
  fe/src/service/queries/reply.ts
  fe/src/types/feed.d.ts
Labels: FE, release

#483 [BE] 리팩토링
  be/src/main/java/com/foodymoody/be/feed/application/FeedMapper.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/request/CollectionReadFeedDetailsServiceRequest.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/request/FeedRegisterRequest.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/request/FeedServiceRegisterRequest.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/request/FeedServiceUpdateRequest.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/request/FeedUpdateRequest.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/CollectionReadFeedDetailsResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedImageMenuResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedMemberResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedReadAllResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/dto/response/FeedReadResponse.java
  be/src/main/java/com/foodymoody/be/feed/application/usecase/CollectionUseCase.java
  be/src/main/java/com/foodymoody/be/feed/application/usecase/FeedUseCase.java
  be/src/main/java/com/foodymoody/be/feed/domain/entity/Feed.java
  be/src/main/java/com/foodymoody/be/feed/domain/entity/ImageMenu.java
  be/src/main/java/com/foodymoody/be/feed/domain/entity/StoreMood.java
  be/src/main/java/com/foodymoody/be/feed/infra/persistence/jpa/FeedJpaRepository.java
  be/src/main/java/com/foodymoody/be/feed/infra/persistence/jpa/StoreMoodJpaRepository.java
  be/src/main/java/com/foodymoody/be/feed/presentation/CollectionController.java
  be/src/main/java/com/foodymoody/be/feed/presentation/FeedController.java
  be/src/main/java/com/foodymoody/be/feed/presentation/StoreMoodController.java
  be/src/main/java/com/foodymoody/be/feed_like/application/FeedLikeMapper.java
  be/src/main/java/com/foodymoody/be/feed_like/application/service/FeedLikeService.java
  be/src/main/java/com/foodymoody/be/feed_like/domain/entity/FeedLike.java
  be/src/main/java/com/foodymoody/be/feed_like/domain/entity/FeedLikeAddedEvent.java
  be/src/main/java/com/foodymoody/be/feed_like/infra/persistence/jpa/FeedLikeJpaRepository.java
  be/src/main/java/com/foodymoody/be/feed_like/presentation/FeedLikeController.java
  be/src/main/java/com/foodymoody/be/feed_like_count/domain/entity/FeedLikeCount.java
  be/src/main/java/com/foodymoody/be/feed_like_count/infra/persistence/jpa/FeedLikeCountJpaRepository.java
  be/src/main/java/com/foodymoody/be/menu/domain/entity/Menu.java
  be/src/test/java/com/foodymoody/be/acceptance/member/MemberAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/feed/application/FeedMapperTest.java
Labels: BE, refactor

#484 [BE] 피드 컬렉션 커멘트 조회 구현
  be/src/docs/asciidoc/index.adoc
  be/src/main/java/com/foodymoody/be/common/exception/ErrorMessage.java
  be/src/main/java/com/foodymoody/be/feed_collection/application/usecase/FeedCollectionReadUseCase.java
  be/src/main/java/com/foodymoody/be/feed_collection/presentation/FeedCollectionReadController.java
  be/src/main/java/com/foodymoody/be/feed_collection_like/domain/FeedCollectionLikeRepository.java
  be/src/main/java/com/foodymoody/be/feed_collection_like/infra/persistence/FeedCollectionLikeRepositoryImpl.java
  be/src/main/java/com/foodymoody/be/feed_comment/persentation/FeedCommentReadController.java
  be/src/main/java/com/foodymoody/be/feed_comment_like/application/exception/FeedCommentIsAlreadyLikedException.java
  be/src/main/java/com/foodymoody/be/feed_comment_like/application/exception/FeedCommentIsNotLikedException.java
  be/src/main/java/com/foodymoody/be/feed_comment_like/application/service/CommentHeartWriteService.java
  be/src/main/java/com/foodymoody/be/feed_comment_like/application/service/FeedCommentLikeWriteService.java
  be/src/main/java/com/foodymoody/be/feed_comment_like/application/usecase/CommentLikeWriteUseCase.java
  be/src/main/java/com/foodymoody/be/feed_comment_like/application/usecase/FeedCommentLikeWriteUseCase.java
  be/src/main/java/com/foodymoody/be/feed_comment_like/domain/FeedCommentLike.java
  be/src/main/java/com/foodymoody/be/feed_comment_like/domain/FeedCommentLikeAddedEvent.java
  be/src/main/java/com/foodymoody/be/feed_comment_like/domain/FeedCommentLikeRepository.java
  be/src/main/java/com/foodymoody/be/feed_comment_like/infra/persistence/FeedCommentLikeRepositoryImpl.java
  be/src/main/java/com/foodymoody/be/feed_comment_like/infra/persistence/jpa/FeedCommentLikeJpaRepository.java
  be/src/main/java/com/foodymoody/be/feed_comment_like/presentation/FeedCommentLikeWriteController.java
  be/src/main/java/com/foodymoody/be/feed_comment_like_count/application/service/FeedCommentLikeCountWriteService.java
  be/src/main/java/com/foodymoody/be/feed_comment_like_count/infra/event/CommentHeartCountCommentEventHandler.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/FeedCommentLikedEventHandler.java
  be/src/main/java/com/foodymoody/be/notification/infra/event/util/NotificationDetailsFactory.java
  be/src/main/resources/application-filter.yml
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection/FeedCollectionAcceptanceTest.java
  be/src/test/java/com/foodymoody/be/acceptance/feed_collection/FeedCollectionSteps.java
  be/src/test/java/com/foodymoody/be/feed_comment/application/service/FeedFeedReplyReadServiceTest.java
  be/src/test/java/com/foodymoody/be/feed_comment_like/application/service/FeedCommentLikeWriteServiceTest.java
  be/src/test/java/com/foodymoody/be/feed_comment_like_count/application/FeedCommentFeedLikeCountWriteServiceTest.java
Labels: BE, feat
